/* RH v80 - provisoes oficiais por competencia, conciliadas com o relatorio contabil. */
(function(){
'use strict';
window.RH_OFFICIAL_PROVISIONS_V80=true;
var V80={key:'',records:null,pending:null};
function E80(id){return document.getElementById(id)}
function x80(v){try{return esc(v==null?'':v)}catch(e){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}}
function n80(v){var n=Number(v);return isFinite(n)?n:0}
function m80(v){try{return fmt(n80(v))}catch(e){return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(n80(v))}}
function comp80(){
  var c=S.competencia||{};
  if(c._periodConsolidated&&Array.isArray(c._periodCompetencias)){
    var dates=c._periodCompetencias.map(function(x){return String(x&&x.competencia||'').slice(0,10)}).filter(function(x){return /^\d{4}-\d{2}-\d{2}$/.test(x)&&x.slice(5,7)!=='00'}).sort();
    if(dates.length)return dates[dates.length-1]
  }
  return String(c.competencia||'').slice(0,10)
}
function label80(){try{return formatCompetence(comp80())}catch(e){return comp80()||'—'}}
function sum80(a,from,to){a=a||[];var s=0;for(var i=from||0;i<(to==null?a.length:to);i++)s+=n80(a[i]);return Math.round((s+Number.EPSILON)*100)/100}
function people80(){var m={};(S.colaboradores||[]).forEach(function(p){if(p.matricula)m[String(p.matricula)]=p});return m}
function active80(p){if(!p)return true;try{if(typeof window.rhRosterIsActive==='function')return!!window.rhRosterIsActive(p)}catch(e){}var s=String(p.situacao||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();return !/deslig|demit|rescind|inativ/.test(s)}
function dept80(p){try{return departmentName(p&&p.departamento)}catch(e){return String(p&&p.departamento||'—')}}
function kind80(k){return k==='13'?'decimo_terceiro':'ferias'}
function title80(k){return k==='13'?'13º salário':'Férias'}
function row80(raw,map){var p=map[String(raw.m)]||{},s=raw.s||[],pm=raw.pm||[],prov=raw.p||pm;return{m:String(raw.m||p.matricula||''),name:String(p.nome||'Dados protegidos'),dep:dept80(p),cc:String(p.centro_custo||'Sem CC'),link:String(p.vinculo||'—'),pm:pm,prov:prov,s:s,enc:sum80(s,1,6)}}
async function load80(force){
  var k=comp80();if(!k)return null;if(!force&&V80.key===k&&V80.records)return V80.records;if(V80.pending)return V80.pending;
  V80.pending=api('rh_provisoes_oficiais?competencia=eq.'+encodeURIComponent(k)+'&select=competencia,tipo,arquivo_nome,totais,colaboradores,origem').then(function(rows){var out={};(rows||[]).forEach(function(r){out[r.tipo]=r});V80.key=k;V80.records=out;return out}).catch(function(e){console.warn('RH v80:',e);return null}).finally(function(){V80.pending=null});return V80.pending
}
function cards80(k,r){var t=r.totais||{},s=t.saldo||[],p=t.provisionado||t.mes||[],reg=t.mes||[],aj=t.ajuste||[],enc=sum80(s,1,6);return '<div class="kpi-grid slim rh26-kpis rh80-kpis">'+
  '<button class="kpi" type="button" data-rh80-card="saldo" data-rh80-kind="'+k+'"><span>Saldo provisionado</span><strong>'+m80(s[0])+'</strong><small>saldo oficial em '+label80()+'</small></button>'+
  '<button class="kpi" type="button" data-rh80-card="mes" data-rh80-kind="'+k+'"><span>Provisão do mês</span><strong>'+m80(p[0])+'</strong><small>'+m80(reg[0])+' regular + '+m80(aj[0])+' ajuste</small></button>'+
  '<button class="kpi" type="button" data-rh80-card="encargos" data-rh80-kind="'+k+'"><span>Encargos sobre saldo</span><strong>'+m80(enc)+'</strong><small>INSS Emp. + RAT + Terceiros + FGTS + PIS</small></button>'+
  '<button class="kpi featured" type="button" data-rh80-card="custo" data-rh80-kind="'+k+'"><span>Custo provisionado</span><strong>'+m80(s[6])+'</strong><small>saldo + encargos</small></button></div>'}
function table80(k,rows,r){var t=r.totais||{},s=t.saldo||[];return '<article class="panel table-panel rh80-official"><div class="panel-head"><div><span class="panel-kicker">COMPOSIÇÃO OFICIAL POR COLABORADOR</span><h2>'+title80(k)+' · '+label80()+'</h2><p class="detail-note">Fonte: '+x80(r.arquivo_nome)+' · clique no colaborador para a memória completa.</p></div><span class="status success">Conciliado com o Domínio</span></div><div class="table-wrap"><table class="rh80-table"><thead><tr><th>Colaborador</th><th>Matrícula</th><th>Departamento</th><th>Vínculo</th><th class="money">Base provisionada</th><th class="money">INSS Empresa</th><th class="money">RAT</th><th class="money">Terceiros</th><th class="money">FGTS</th><th class="money">PIS</th><th class="money">Custo total</th></tr></thead><tbody>'+rows.map(function(x,i){return '<tr class="rh80-row" data-rh80-row="'+i+'" data-rh80-kind="'+k+'"><td><b>'+x80(x.name)+'</b><small>'+x80(x.cc)+'</small></td><td>'+x80(x.m)+'</td><td>'+x80(x.dep)+'</td><td>'+x80(x.link)+'</td>'+x.s.map(function(v){return '<td class="money">'+m80(v)+'</td>'}).join('')+'</tr>'}).join('')+'</tbody><tfoot><tr><td><b>TOTAL OFICIAL</b></td><td></td><td></td><td></td>'+s.map(function(v){return '<td class="money"><b>'+m80(v)+'</b></td>'}).join('')+'</tr></tfoot></table></div></article>'}
function root80(pane,k){var root=pane.querySelector(':scope > .rh80-official-root');if(!root){root=document.createElement('div');root.className='rh80-official-root';root.dataset.rh80Kind=k;pane.appendChild(root)}Array.from(pane.children).forEach(function(child){if(child===root||child.id==='rh70-vacation-simulator'||child.classList.contains('rh41-export-bar'))return;if(child.matches('.rh26-kpis,article.table-panel,[id^="rh-plan-'+k+'-"]'))child.dataset.rh80Legacy='1'});return root}
function render80(k,r){var pane=document.querySelector('[data-plan-pane="'+k+'"]');if(!pane||!r)return false;var map=people80(),rows=(r.colaboradores||[]).filter(function(q){return active80(map[String(q.m)])}).map(function(q){return row80(q,map)}),root=root80(pane,k);root.innerHTML=cards80(k,r)+table80(k,rows,r);pane.dataset.rh80Official='1';r._rows=rows;return true}
async function refresh80(force){var rec=await load80(!!force);if(!rec)return false;var a=rec.decimo_terceiro&&render80('13',rec.decimo_terceiro),b=rec.ferias&&render80('ferias',rec.ferias);if(a||b)window.RH_V80_LAST={competencia:comp80(),decimo:rec.decimo_terceiro||null,ferias:rec.ferias||null};return !!(a||b)}
function close80(){var m=E80('rh80-modal');if(m)m.remove()}
function line80(label,a){a=a||[];return '<tr><td>'+x80(label)+'</td>'+a.map(function(v){return '<td class="money">'+m80(v)+'</td>'}).join('')+'</tr>'}
function openRow80(k,index){var r=V80.records&&V80.records[kind80(k)],x=r&&r._rows&&r._rows[index];if(!r||!x)return;var adj=x.prov.map(function(v,i){return n80(v)-n80(x.pm[i])});var body='<div class="rh80-source"><b>Parâmetro oficial</b><span>'+x80(r.arquivo_nome)+' · competência '+label80()+'</span></div><div class="rh80-scroll"><table class="rh80-memory"><thead><tr><th>Movimento</th><th class="money">Base</th><th class="money">INSS Emp.</th><th class="money">RAT</th><th class="money">Terceiros</th><th class="money">FGTS</th><th class="money">PIS</th><th class="money">Total</th></tr></thead><tbody>'+line80('Provisão regular do mês',x.pm)+line80('Ajuste / diferença',adj)+line80('Provisionado no mês',x.prov)+line80('Saldo atual',x.s)+'</tbody></table></div>';modal80(x.name,title80(k)+' · matrícula '+x.m,body)}
function openCard80(k,card){var r=V80.records&&V80.records[kind80(k)],rows=r&&r._rows||[],t=r&&r.totais||{};if(!r)return;var headers=[],body='',foot=[],sub='';if(card==='encargos'){headers=['Colaborador','INSS Empresa','RAT','Terceiros','FGTS','PIS','Total encargos'];body=rows.map(function(x){return '<tr><td>'+x80(x.name)+'</td>'+x.s.slice(1,6).map(function(v){return '<td class="money">'+m80(v)+'</td>'}).join('')+'<td class="money"><b>'+m80(x.enc)+'</b></td></tr>'}).join('');var s=t.saldo||[];foot=['TOTAL',s[1],s[2],s[3],s[4],s[5],sum80(s,1,6)];sub='Encargos oficiais incidentes sobre o saldo, respeitando o vínculo de cada colaborador.'}else{var mode=card==='mes'?'prov':card==='custo'?'s':'s',idx=card==='custo'?6:0;headers=['Colaborador',card==='mes'?'Provisionado no mês':card==='custo'?'Custo provisionado':'Saldo provisionado'];body=rows.map(function(x){return '<tr><td>'+x80(x.name)+'</td><td class="money">'+m80(x[mode][idx])+'</td></tr>'}).join('');var total=card==='mes'?(t.provisionado||[])[0]:(t.saldo||[])[idx];foot=['TOTAL',total];sub=card==='mes'?'Provisão regular acrescida dos ajustes e diferenças reconhecidos no relatório oficial.':card==='custo'?'Custo provisionado = base do saldo + encargos oficiais.':'Base acumulada da provisão, sem somar novamente seus encargos.'}var head='<tr>'+headers.map(function(h){return '<th>'+x80(h)+'</th>'}).join('')+'</tr>',f='<tr>'+foot.map(function(v,i){return '<td'+(i?' class="money"':'')+'><b>'+(i?m80(v):x80(v))+'</b></td>'}).join('')+'</tr>';modal80(headers[headers.length-1],title80(k)+' · composição do card','<p class="rh80-sub">'+x80(sub)+'</p><div class="rh80-scroll"><table class="rh80-memory"><thead>'+head+'</thead><tbody>'+body+'</tbody><tfoot>'+f+'</tfoot></table></div>')}
function modal80(title,sub,body){close80();document.body.insertAdjacentHTML('beforeend','<div class="rh80-modal" id="rh80-modal" role="dialog" aria-modal="true"><section><header><div><span>RH & FOLHA · CONTROLE AUDITADO</span><h2>'+x80(title)+'</h2><p>'+x80(sub)+'</p></div><button type="button" data-rh80-close aria-label="Fechar">×</button></header><div class="rh80-body">'+body+'</div></section></div>')}
function style80(){if(E80('_rh80'))return;var s=document.createElement('style');s.id='_rh80';s.textContent='#page-planejamento [data-plan-pane="13"][data-rh80-official="1"]>[data-rh80-legacy],#page-planejamento [data-plan-pane="ferias"][data-rh80-official="1"]>[data-rh80-legacy]{display:none!important}#page-planejamento article.rh80-official{display:block!important}.rh80-official-root{display:block}.rh80-kpis .kpi{appearance:none;text-align:left;color:inherit;cursor:pointer}.rh80-official{margin-top:16px}.rh80-table{min-width:1480px}.rh80-table td small{display:block;margin-top:3px;color:var(--muted)}.rh80-row{cursor:pointer}.rh80-row:hover{background:color-mix(in srgb,var(--gold) 8%,transparent)}.rh80-modal{position:fixed;inset:0;z-index:13000;display:grid;place-items:center;padding:18px;background:rgba(2,12,23,.76);backdrop-filter:blur(5px)}.rh80-modal>section{width:min(1240px,calc(100vw - 24px));max-height:calc(100vh - 24px);overflow:auto;border:1px solid var(--line);border-radius:18px;background:var(--surface);box-shadow:0 28px 80px rgba(0,0,0,.46)}.rh80-modal header{position:sticky;top:0;z-index:2;display:flex;justify-content:space-between;gap:18px;padding:20px 22px;border-bottom:1px solid var(--line-soft);background:var(--surface)}.rh80-modal header span{color:var(--gold);font-size:.68rem;font-weight:950;letter-spacing:.08em}.rh80-modal header h2{margin:4px 0;font-size:1.45rem}.rh80-modal header p{margin:0;color:var(--muted)}.rh80-modal header button{width:40px;height:40px;border:1px solid var(--line);border-radius:11px;background:var(--surface-2);color:var(--text);font-size:24px;cursor:pointer}.rh80-body{padding:20px 22px 24px}.rh80-source{display:flex;justify-content:space-between;gap:16px;padding:12px 14px;margin-bottom:14px;border:1px solid color-mix(in srgb,var(--gold) 42%,var(--line-soft));border-radius:12px;background:color-mix(in srgb,var(--gold) 8%,var(--surface-2))}.rh80-source span,.rh80-sub{color:var(--muted)}.rh80-scroll{overflow:auto}.rh80-memory{width:100%;min-width:880px}.rh80-memory td,.rh80-memory th{padding:11px 12px;border-bottom:1px solid var(--line-soft)}.rh80-memory tfoot{background:color-mix(in srgb,var(--gold) 8%,var(--surface-2))}@media(max-width:700px){.rh80-source{flex-direction:column}.rh80-modal{padding:6px}.rh80-body{padding:14px}}';document.head.appendChild(s)}
var baseRefresh80=window.rhProvisionRefresh;window.rhProvisionRefresh=async function(force){var official=await refresh80(force);if(official)return true;if(typeof baseRefresh80==='function')return baseRefresh80(force);return false};
document.addEventListener('click',function(e){var t=e.target&&e.target.closest&&e.target.closest('[data-rh80-row],[data-rh80-card],[data-rh80-close]');if(!t)return;e.preventDefault();e.stopImmediatePropagation();if(t.hasAttribute('data-rh80-close'))close80();else if(t.dataset.rh80Row!=null)openRow80(t.dataset.rh80Kind,Number(t.dataset.rh80Row));else openCard80(t.dataset.rh80Kind,t.dataset.rh80Card)},true);
document.addEventListener('click',function(e){if(e.target&&e.target.closest&&e.target.closest('[data-plan-tab="13"],[data-plan-tab="ferias"]'))setTimeout(function(){refresh80(false)},180)},true);
function init80(){style80();[180,520,1200].forEach(function(ms){setTimeout(function(){refresh80(false)},ms)})}
window.rhV80Refresh=refresh80;
window.rhV80OpenCard=openCard80;
window.rhV80OfficialCompetence=comp80;
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init80);else init80();
})();
