/* RH & Folha — hotfix v24: Planejamento & Provisões (13º, férias, próxima folha e rescisões) */
(function(){
  'use strict';
  var PLAN={lastTermination:null};
  function arr(x){return Array.prototype.slice.call(x||[]);}
  function asDate(v){if(!v)return null;var d=new Date(String(v).slice(0,10)+'T12:00:00');return isNaN(d.getTime())?null:d;}
  function iso(d){return d?d.toISOString().slice(0,10):'';}
  function money(v){return typeof fmt==='function'?fmt(v):new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v)||0);}
  function num(v){return typeof nfmt==='function'?nfmt(v):new Intl.NumberFormat('pt-BR').format(Number(v)||0);}
  function clt(p){try{return rhVinculoCategory(p)==='clt';}catch(e){return /clt|celet/i.test(String(p&&p.vinculo||''));}}
  function currentActive(){return (window.RH_PERIOD&&RH_PERIOD.active&&RH_PERIOD.active.length?RH_PERIOD.active:(S.competencia?[S.competencia]:[])).slice().sort(function(a,b){return String(a.competencia||'').localeCompare(String(b.competencia||''));});}
  function latestComp(){var a=currentActive();return a[a.length-1]||null;}
  function anchorDate(){var c=latestComp(),d=asDate(c&&c.competencia);if(d){d=new Date(d.getFullYear(),d.getMonth()+1,0,12);return d;}return new Date();}
  function nextCompetence(){var d=anchorDate(),n=new Date(d.getFullYear(),d.getMonth()+1,1,12);return String(n.getMonth()+1).padStart(2,'0')+'/'+n.getFullYear();}
  function personKey(p){return String(p&&p.colaborador_id||p&&p.id||'');}
  function latestPayrollRows(){
    var comps=currentActive(),order={};comps.forEach(function(c){order[String(c.id)]=String(c.competencia||'');});var by={};
    (S.folhas||[]).forEach(function(f){var k=String(f.colaborador_id||''),cur=by[k],d=order[String(f.competencia_id)]||'';if(!cur||d>(order[String(cur.competencia_id)]||''))by[k]=f;});
    return by;
  }
  function planPeople(){
    var latest=latestPayrollRows(),meta={};(S.colaboradores||[]).forEach(function(c){meta[String(c.id)]=c;});
    var src=(S.pessoas||[]),seen={};return src.map(function(p){var k=personKey(p),f=latest[k],m=meta[k]||{};var out=Object.assign({},m,p,f||{});out.id=k;out.colaborador_id=k;seen[k]=1;return out;}).filter(function(p){return p.id;});
  }
  function rates(){
    var e=(S.competencia&&S.competencia.encargos)||{},base=Number(e.base_total_inss)||0;
    var rat=base>0&&Number(e.rat)>0?Number(e.rat)/base:.01;
    var third=base>0&&Number(e.terceiros)>0?Number(e.terceiros)/base:.058;
    var pis=base>0&&Number(e.valor_pis)>0?Number(e.valor_pis)/base:.01;
    return {fgts:.08,inss:.20,rat:rat,terceiros:third,pis:pis,total:.08+.20+rat+third+pis};
  }
  function fullMonthsWith15Days(year,adm,dem,throughMonth){
    var count=0;adm=asDate(adm);dem=asDate(dem);throughMonth=Math.max(1,Math.min(12,throughMonth||12));
    for(var m=0;m<throughMonth;m++){
      var start=new Date(year,m,1,12),end=new Date(year,m+1,0,12),s=start,e=end;if(adm&&adm>s)s=adm;if(dem&&dem<e)e=dem;if(e<s)continue;var days=Math.floor((e-s)/86400000)+1;if(days>=15)count++;
    }return count;
  }
  function serviceYears(adm,end){adm=asDate(adm);end=asDate(end);if(!adm||!end||end<adm)return 0;var y=end.getFullYear()-adm.getFullYear();var ann=new Date(end.getFullYear(),adm.getMonth(),adm.getDate(),12);if(end<ann)y--;return Math.max(0,y);}
  function vacationAvo(adm,end){
    adm=asDate(adm);end=asDate(end);if(!adm||!end||end<adm)return 0;var ann=new Date(end.getFullYear(),adm.getMonth(),adm.getDate(),12);if(ann>end)ann.setFullYear(ann.getFullYear()-1);if(ann<adm)ann=adm;var count=0,cursor=new Date(ann.getFullYear(),ann.getMonth(),ann.getDate(),12);
    while(cursor<=end&&count<12){var next=new Date(cursor.getFullYear(),cursor.getMonth()+1,cursor.getDate(),12),periodEnd=new Date(next.getTime()-86400000);if(periodEnd>end)periodEnd=end;var days=Math.floor((periodEnd-cursor)/86400000)+1;if(days>=15)count++;cursor=next;}return Math.min(12,count);
  }
  function thirteenthPaid(p,year){
    var sum=0;(p.lancamentos||[]).forEach(function(l){var name=String((l.rubrica_codigo||l.codigo||'')+' '+(l.rubrica_nome||l.nome||''));if(!/13.?\s*(sal|sal[aá]rio)|d[eé]cimo\s*terceiro/i.test(name))return;var cid=String(l.competencia_id||''),c=(S.competencias||[]).find(function(x){return String(x.id)===cid;});if(c&&String(c.competencia||'').slice(0,4)!==String(year))return;if(String(l.tipo||'').toLowerCase()==='d'||String(l.tipo||'').toLowerCase()==='desconto')return;sum+=Number(l.valor)||0;});return sum;
  }
  function calc13(){
    var a=anchorDate(),year=a.getFullYear(),month=a.getMonth()+1,r=rates();return planPeople().filter(clt).map(function(p){var sal=Number(p.salario)||0,avos=fullMonthsWith15Days(year,p.admissao,p.demissao||p.desligamento,month),gross=sal/12*avos,monthly=sal/12,paid=thirteenthPaid(p,year),balance=Math.max(0,gross-paid),charges=balance*r.total;return {id:p.id,nome:p.nome||'—',departamento:departmentName(p.departamento),salario:sal,avos:avos,mensal:monthly,provisionado:gross,pago:paid,saldo:balance,encargos:charges,total:balance+charges};}).sort(function(a,b){return b.total-a.total;});
  }
  function calcVacations(){
    var a=anchorDate(),r=rates();return planPeople().filter(clt).map(function(p){var sal=Number(p.salario)||0,avos=vacationAvo(p.admissao,a),base=sal/12*avos,third=base/3,gross=base+third,charges=gross*r.total;return {id:p.id,nome:p.nome||'—',departamento:departmentName(p.departamento),salario:sal,avos:avos,base:base,terco:third,provisao:gross,encargos:charges,total:gross+charges};}).sort(function(a,b){return b.total-a.total;});
  }
  function benefitFor(p){try{var b=rhPersonBenefit(p)||{};return (Number(b.seguro_vida)||0)+(Number(b.assistencia_medica||b.assist_medica)||0)+(Number(b.vr_caixa)||0)+(Number(b.vale_transporte)||0);}catch(e){return 0;}}
  function vacationPreviousMonth(p){
    var sit=String(p&&p.situacao_snapshot||p&&p.situacao||''),rub=(p&&p.lancamentos||[]).map(function(l){return String((l.rubrica_codigo||l.codigo||'')+' '+(l.rubrica_nome||l.nome||''));}).join(' | '),text=(sit+' | '+rub).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
    return /ferias/.test(String(sit).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase())||/(dias ferias|adiantamento de ferias|desconto de ferias|inss ferias|irrf ferias|dias abono pecuniario|1\/3.*ferias|abono.*ferias)/.test(text);
  }
  function forecastRows(){
    var pct=Number(($('rh-plan-adjust')||{}).value)||0,mult=1+pct/100,r=rates();return planPeople().map(function(p){
      var vacation=vacationPreviousMonth(p),salary=Number(p.salario)||Number(p.proventos)||0,actualGross=Number(p.proventos)||salary,referenceGross=vacation?actualGross:salary,prov=referenceGross*mult,disc=Number(p.descontos)||0,liq=Math.max(0,prov-disc);
      var historicGross=actualGross||salary||1,factor=historicGross>0?prov/historicGross:mult,baseRef=Number(p.base_inss)||actualGross||salary,base=baseRef*factor,fgts=Number(p.valor_fgts)>0?Number(p.valor_fgts)*factor:base*.08,enc=base*(r.inss+r.rat+r.terceiros+r.pis),ben=benefitFor(p),cost=prov+fgts+enc+ben;
      return {id:p.id,nome:p.nome||'—',departamento:departmentName(p.departamento),proventos:prov,descontos:disc,liquido:liq,encargos:fgts+enc,beneficios:ben,custo:cost,fonteProjecao:vacation?'folha de férias da competência anterior':'salário vigente',feriasAnterior:vacation};
    }).sort(function(a,b){return b.custo-a.custo;});
  }
  function sumRows(rows,key){return rows.reduce(function(a,x){return a+(Number(x[key])||0);},0);}
  function kpi(label,value,small,cls){return '<div class="kpi '+(cls||'')+'"><span>'+esc(label)+'</span><strong>'+esc(value)+'</strong><small>'+esc(small||'')+'</small></div>';}
  function table13(rows){return '<div class="table-wrap"><table><thead><tr><th>Colaborador</th><th>Departamento</th><th class="money">Salário</th><th class="money">Avos</th><th class="money">Provisão acumulada</th><th class="money">Já pago</th><th class="money">Saldo</th><th class="money">Encargos estimados</th><th class="money">Custo provisionado</th></tr></thead><tbody>'+rows.map(function(x){return '<tr><td><b>'+esc(x.nome)+'</b></td><td>'+esc(x.departamento)+'</td><td class="money">'+money(x.salario)+'</td><td class="money">'+x.avos+'/12</td><td class="money">'+money(x.provisionado)+'</td><td class="money">'+money(x.pago)+'</td><td class="money"><b>'+money(x.saldo)+'</b></td><td class="money">'+money(x.encargos)+'</td><td class="money"><b>'+money(x.total)+'</b></td></tr>';}).join('')+'</tbody><tfoot><tr><td><b>TOTAL</b></td><td></td><td></td><td></td><td class="money"><b>'+money(sumRows(rows,'provisionado'))+'</b></td><td class="money"><b>'+money(sumRows(rows,'pago'))+'</b></td><td class="money"><b>'+money(sumRows(rows,'saldo'))+'</b></td><td class="money"><b>'+money(sumRows(rows,'encargos'))+'</b></td><td class="money"><b>'+money(sumRows(rows,'total'))+'</b></td></tr></tfoot></table></div>';}
  function tableVac(rows){return '<div class="table-wrap"><table><thead><tr><th>Colaborador</th><th>Departamento</th><th class="money">Avos estimados</th><th class="money">Férias</th><th class="money">1/3</th><th class="money">Provisão</th><th class="money">Encargos estimados</th><th class="money">Custo provisionado</th></tr></thead><tbody>'+rows.map(function(x){return '<tr><td><b>'+esc(x.nome)+'</b></td><td>'+esc(x.departamento)+'</td><td class="money">'+x.avos+'/12</td><td class="money">'+money(x.base)+'</td><td class="money">'+money(x.terco)+'</td><td class="money">'+money(x.provisao)+'</td><td class="money">'+money(x.encargos)+'</td><td class="money"><b>'+money(x.total)+'</b></td></tr>';}).join('')+'</tbody><tfoot><tr><td><b>TOTAL</b></td><td></td><td></td><td class="money"><b>'+money(sumRows(rows,'base'))+'</b></td><td class="money"><b>'+money(sumRows(rows,'terco'))+'</b></td><td class="money"><b>'+money(sumRows(rows,'provisao'))+'</b></td><td class="money"><b>'+money(sumRows(rows,'encargos'))+'</b></td><td class="money"><b>'+money(sumRows(rows,'total'))+'</b></td></tr></tfoot></table></div>';}
  function tableForecast(rows){return '<div class="table-wrap"><table><thead><tr><th>Colaborador</th><th>Departamento</th><th class="money">Proventos previstos</th><th class="money">Descontos base</th><th class="money">Líquido previsto</th><th class="money">Encargos</th><th class="money">Benefícios</th><th class="money">Custo previsto</th></tr></thead><tbody>'+rows.map(function(x){return '<tr><td><b>'+esc(x.nome)+'</b></td><td>'+esc(x.departamento)+'</td><td class="money">'+money(x.proventos)+'</td><td class="money">'+money(x.descontos)+'</td><td class="money">'+money(x.liquido)+'</td><td class="money">'+money(x.encargos)+'</td><td class="money">'+money(x.beneficios)+'</td><td class="money"><b>'+money(x.custo)+'</b></td></tr>';}).join('')+'</tbody><tfoot><tr><td><b>TOTAL</b></td><td></td><td class="money"><b>'+money(sumRows(rows,'proventos'))+'</b></td><td class="money"><b>'+money(sumRows(rows,'descontos'))+'</b></td><td class="money"><b>'+money(sumRows(rows,'liquido'))+'</b></td><td class="money"><b>'+money(sumRows(rows,'encargos'))+'</b></td><td class="money"><b>'+money(sumRows(rows,'beneficios'))+'</b></td><td class="money"><b>'+money(sumRows(rows,'custo'))+'</b></td></tr></tfoot></table></div>';}
  function ensurePage(){
    if($('page-planejamento'))return;
    var nav=$('nav'),cfg=nav&&nav.querySelector('[data-view="configuracoes"]'),btn=document.createElement('button');btn.className='nav-item';btn.dataset.view='planejamento';btn.innerHTML='<span>◫</span>Planejamento & Provisões';if(nav)nav.insertBefore(btn,cfg||null);
    var main=document.querySelector('#app main.content');if(!main)return;var page=document.createElement('section');page.className='page';page.id='page-planejamento';page.innerHTML='\
      <div class="page-head"><div><span class="eyebrow">PLANEJAMENTO FINANCEIRO DE PESSOAS</span><h1>Planejamento & Provisões</h1><p>Antecipe 13º, férias, próxima folha e cenários de desligamento com base no histórico importado.</p></div><div class="head-actions"><button class="button ghost export-only" id="rh-plan-export">Exportar planejamento</button></div></div>\
      <div class="rh-plan-warning"><b>Estimativa gerencial</b><span>As simulações não substituem o cálculo oficial da folha, a conferência contábil ou a validação trabalhista. Parâmetros devem ser revisados antes de qualquer pagamento.</span></div>\
      <div class="rh-plan-tabs"><button class="active" data-plan-tab="13">13º salário</button><button data-plan-tab="ferias">Férias</button><button data-plan-tab="folha">Próxima folha</button><button data-plan-tab="rescisao">Rescisões</button></div>\
      <section class="rh-plan-pane active" data-plan-pane="13"><div id="rh-plan-13-kpis" class="kpi-grid slim"></div><article class="panel table-panel"><div class="panel-head"><div><span class="panel-kicker">PROVISÃO DO ANO</span><h2>13º salário por colaborador</h2></div><span class="source-badge" id="rh-plan-13-ref">—</span></div><div id="rh-plan-13-table"></div></article></section>\
      <section class="rh-plan-pane" data-plan-pane="ferias"><div id="rh-plan-ferias-kpis" class="kpi-grid slim"></div><article class="panel table-panel"><div class="panel-head"><div><span class="panel-kicker">PROVISÃO ESTIMADA</span><h2>Férias + 1/3 por colaborador</h2></div><span class="source-badge">Base salarial atual</span></div><div id="rh-plan-ferias-table"></div><p class="detail-note">O saldo de férias é uma estimativa pelo tempo transcorrido no período aquisitivo. Férias gozadas/pagas que não estejam estruturadas na base podem exigir ajuste.</p></article></section>\
      <section class="rh-plan-pane" data-plan-pane="folha"><div class="rh-plan-forecast-controls"><label>Ajuste geral de proventos (%)<input id="rh-plan-adjust" type="number" step="0.1" value="0"></label><button class="button secondary" id="rh-plan-recalc">Recalcular previsão</button></div><div id="rh-plan-folha-kpis" class="kpi-grid slim"></div><article class="panel table-panel"><div class="panel-head"><div><span class="panel-kicker">PROJEÇÃO</span><h2 id="rh-plan-next-title">Próxima folha</h2></div><span class="source-badge">Última competência importada</span></div><div id="rh-plan-folha-table"></div></article></section>\
      <section class="rh-plan-pane" data-plan-pane="rescisao"><div class="grid two rh-plan-res-grid"><article class="panel"><div class="panel-head"><div><span class="panel-kicker">SIMULADOR</span><h2>Rescisão individual</h2></div></div><div class="rh-plan-form"><label>Colaborador<select id="rh-res-person"></select></label><label>Data de desligamento<input id="rh-res-date" type="date"></label><label>Modalidade<select id="rh-res-type"><option value="sem_justa">Sem justa causa</option><option value="justa">Justa causa</option><option value="acordo">Acordo entre as partes</option><option value="pedido">Pedido de demissão</option></select></label><label>Aviso prévio<select id="rh-res-notice"><option value="indenizado">Indenizado</option><option value="trabalhado">Trabalhado</option><option value="desconto">Desconto do empregado</option><option value="na">Não aplicável</option></select></label><label>Períodos de férias vencidas<input id="rh-res-overdue" type="number" min="0" step="1" value="0"></label><label>Saldo FGTS conhecido<input id="rh-res-fgts" inputmode="decimal" placeholder="0,00"></label><label>Outros créditos<input id="rh-res-credits" inputmode="decimal" placeholder="0,00"></label><label>Outros descontos<input id="rh-res-discounts" inputmode="decimal" placeholder="0,00"></label><button class="button primary" id="rh-res-calc">Calcular cenário</button></div></article><article class="panel" id="rh-res-result"><div class="empty-state"><h2>Selecione um cenário</h2><p>A memória de cálculo aparecerá aqui.</p></div></article></div></section>';
    var importPage=$('page-importacao');main.insertBefore(page,importPage||null);
    btn.onclick=function(){go('planejamento');renderPlanning();};
    page.querySelectorAll('[data-plan-tab]').forEach(function(b){b.onclick=function(){page.querySelectorAll('[data-plan-tab]').forEach(function(x){x.classList.toggle('active',x===b);});page.querySelectorAll('[data-plan-pane]').forEach(function(x){x.classList.toggle('active',x.dataset.planPane===b.dataset.planTab);});};});
    $('rh-plan-recalc').onclick=renderForecast;$('rh-res-calc').onclick=renderTermination;$('rh-plan-export').onclick=exportPlanning;
    addStyles();
  }
  function render13(){var rows=calc13(),a=anchorDate();$('rh-plan-13-ref').textContent='Até '+String(a.getMonth()+1).padStart(2,'0')+'/'+a.getFullYear();$('rh-plan-13-kpis').innerHTML=kpi('Provisão acumulada',money(sumRows(rows,'provisionado')),rows.length+' CLT')+kpi('Já pago identificado',money(sumRows(rows,'pago')),'rubricas de 13º detectadas')+kpi('Saldo a provisionar',money(sumRows(rows,'saldo')),'antes de encargos','featured')+kpi('Custo provisionado',money(sumRows(rows,'total')),'saldo + encargos estimados');$('rh-plan-13-table').innerHTML=rows.length?table13(rows):'<div class="empty-state"><p>Nenhum vínculo CLT disponível no período.</p></div>';}
  function renderVac(){var rows=calcVacations();$('rh-plan-ferias-kpis').innerHTML=kpi('Férias provisionadas',money(sumRows(rows,'base')),rows.length+' CLT')+kpi('1/3 constitucional',money(sumRows(rows,'terco')),'estimativa acumulada')+kpi('Encargos estimados',money(sumRows(rows,'encargos')),'sobre férias + 1/3')+kpi('Custo provisionado',money(sumRows(rows,'total')),'estimativa gerencial','featured');$('rh-plan-ferias-table').innerHTML=rows.length?tableVac(rows):'<div class="empty-state"><p>Nenhum vínculo CLT disponível no período.</p></div>';}
  function renderForecast(){var rows=forecastRows();$('rh-plan-next-title').textContent='Previsão da folha · '+nextCompetence();$('rh-plan-folha-kpis').innerHTML=kpi('Proventos previstos',money(sumRows(rows,'proventos')),nextCompetence())+kpi('Líquido previsto',money(sumRows(rows,'liquido')),'antes de novas variáveis')+kpi('Encargos + benefícios',money(sumRows(rows,'encargos')+sumRows(rows,'beneficios')),'estimativa patronal')+kpi('Custo previsto',money(sumRows(rows,'custo')),'próxima competência','featured');$('rh-plan-folha-table').innerHTML=rows.length?tableForecast(rows):'<div class="empty-state"><p>Importe ao menos uma competência para projetar a próxima folha.</p></div>';}
  function parseBR(v){v=String(v||'').trim().replace(/R\$\s?/g,'').replace(/\./g,'').replace(',','.');var n=Number(v);return isFinite(n)?n:0;}
  function terminationCalc(){
    var id=String(($('rh-res-person')||{}).value||''),p=planPeople().find(function(x){return String(x.id)===id;});if(!p)return null;var end=asDate(($('rh-res-date')||{}).value)||anchorDate(),type=$('rh-res-type').value,notice=$('rh-res-notice').value,sal=Number(p.salario)||0,day=Math.min(30,end.getDate()),saldo=sal/30*day,year=end.getFullYear(),avos13=fullMonthsWith15Days(year,p.admissao,end,end.getMonth()+1),decimo=sal/12*avos13,avosFer=vacationAvo(p.admissao,end),ferBase=sal/12*avosFer,ferProp=ferBase+ferBase/3,overdue=Math.max(0,Number($('rh-res-overdue').value)||0),ferVenc=sal*4/3*overdue,years=serviceYears(p.admissao,end),noticeDays=Math.min(90,30+3*years),noticeVal=sal/30*noticeDays,noticeCredit=0,noticeDiscount=0;
    if(notice==='indenizado'){if(type==='sem_justa')noticeCredit=noticeVal;else if(type==='acordo')noticeCredit=noticeVal*.5;}else if(notice==='desconto'&&type==='pedido')noticeDiscount=sal;
    if(type==='justa'){decimo=0;ferProp=0;}var fgts=parseBR($('rh-res-fgts').value),fine=type==='sem_justa'?fgts*.40:(type==='acordo'?fgts*.20:0),credits=parseBR($('rh-res-credits').value),discounts=parseBR($('rh-res-discounts').value)+noticeDiscount,total=saldo+decimo+ferProp+ferVenc+noticeCredit+fine+credits-discounts;
    return {p:p,end:end,type:type,notice:notice,salario:sal,saldo:saldo,avos13:avos13,decimo:decimo,avosFer:avosFer,ferProp:ferProp,ferVenc:ferVenc,noticeDays:noticeDays,noticeCredit:noticeCredit,noticeDiscount:noticeDiscount,fgts:fgts,fine:fine,credits:credits,discounts:discounts,total:total};
  }
  function modeLabel(v){return {sem_justa:'Sem justa causa',justa:'Justa causa',acordo:'Acordo entre as partes',pedido:'Pedido de demissão'}[v]||v;}
  function renderTermination(){var x=terminationCalc(),box=$('rh-res-result');if(!x||!box)return;PLAN.lastTermination=x;var rows=[['Saldo de salário',x.saldo],['13º proporcional ('+x.avos13+'/12)',x.decimo],['Férias proporcionais + 1/3 ('+x.avosFer+'/12)',x.ferProp],['Férias vencidas + 1/3',x.ferVenc],['Aviso prévio indenizado',x.noticeCredit],['Multa sobre FGTS',x.fine],['Outros créditos',x.credits],['Descontos',-x.discounts]].filter(function(r){return Math.abs(r[1])>.004;});box.innerHTML='<div class="panel-head"><div><span class="panel-kicker">MEMÓRIA ESTIMADA</span><h2>'+esc(x.p.nome||'Colaborador')+'</h2><p>'+esc(modeLabel(x.type))+' · '+brDate(iso(x.end))+'</p></div><button class="button ghost" id="rh-res-print">Imprimir / PDF</button></div><div class="rh-res-meta"><span>Salário base <b>'+money(x.salario)+'</b></span><span>Aviso-base <b>'+x.noticeDays+' dias</b></span><span>FGTS informado <b>'+money(x.fgts)+'</b></span></div><div class="rh-res-lines">'+rows.map(function(r){return '<div><span>'+esc(r[0])+'</span><b class="'+(r[1]<0?'negative':'')+'">'+money(r[1])+'</b></div>';}).join('')+'<div class="total"><span>Total estimado bruto</span><strong>'+money(x.total)+'</strong></div></div><p class="detail-note">Não inclui automaticamente INSS/IRRF rescisórios, médias variáveis, estabilidade, convenção coletiva, indenizações específicas ou outras particularidades. Use como cenário gerencial e valide o cálculo oficial antes do pagamento.</p>';$('rh-res-print').onclick=printTermination;}
  function populateTerminationPeople(){var sel=$('rh-res-person');if(!sel)return;var cur=sel.value,rows=planPeople().filter(clt).sort(function(a,b){return String(a.nome||'').localeCompare(String(b.nome||''),'pt-BR');});sel.innerHTML=rows.map(function(p){return '<option value="'+esc(p.id)+'">'+esc(p.nome||'—')+'</option>';}).join('');if(cur&&rows.some(function(p){return String(p.id)===String(cur);}))sel.value=cur;if(!$('rh-res-date').value)$('rh-res-date').value=iso(anchorDate());}
  function renderPlanning(){ensurePage();render13();renderVac();renderForecast();populateTerminationPeople();if(typeof rhFitAllCardValues==='function')rhFitAllCardValues($('page-planejamento'));}
  function printTermination(){var x=PLAN.lastTermination;if(!x)return;var w=window.open('','_blank','width=900,height=700');if(!w)return;var html=$('rh-res-result').innerHTML;w.document.write('<!doctype html><html><head><meta charset="utf-8"><title>Relatório de Rescisão - '+esc(x.p.nome||'')+'</title><style>body{font-family:Arial,sans-serif;padding:32px;color:#111}button{display:none}.panel-head{display:flex;justify-content:space-between;border-bottom:2px solid #111;padding-bottom:12px}.rh-res-meta{display:flex;gap:24px;flex-wrap:wrap;margin:20px 0}.rh-res-lines>div{display:flex;justify-content:space-between;padding:9px 0;border-bottom:1px solid #ddd}.rh-res-lines .total{font-size:20px;border-top:2px solid #111;margin-top:10px}.detail-note{font-size:11px;color:#555;margin-top:24px}</style></head><body><h1>LNB · Simulação de Rescisão</h1>'+html+'</body></html>');w.document.close();setTimeout(function(){w.print();},250);}
  async function exportPlanning(){try{await loadLibrary('xlsx');var wb=XLSX.utils.book_new(),r13=calc13(),rv=calcVacations(),rf=forecastRows();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(r13.map(function(x){return {'Colaborador':x.nome,'Departamento':x.departamento,'Salário':x.salario,'Avos':x.avos,'Provisão acumulada':x.provisionado,'Já pago':x.pago,'Saldo':x.saldo,'Encargos':x.encargos,'Custo':x.total};})),'13o');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rv.map(function(x){return {'Colaborador':x.nome,'Departamento':x.departamento,'Avos':x.avos,'Férias':x.base,'1/3':x.terco,'Provisão':x.provisao,'Encargos':x.encargos,'Custo':x.total};})),'Ferias');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rf.map(function(x){return {'Colaborador':x.nome,'Departamento':x.departamento,'Proventos previstos':x.proventos,'Descontos base':x.descontos,'Líquido previsto':x.liquido,'Encargos':x.encargos,'Benefícios':x.beneficios,'Custo previsto':x.custo};})),'Proxima Folha');if(PLAN.lastTermination)XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet([PLAN.lastTermination].map(function(x){return {'Colaborador':x.p.nome,'Modalidade':modeLabel(x.type),'Data':iso(x.end),'Salário':x.salario,'Saldo salário':x.saldo,'13º proporcional':x.decimo,'Férias proporcionais':x.ferProp,'Férias vencidas':x.ferVenc,'Aviso':x.noticeCredit,'Multa FGTS':x.fine,'Total estimado':x.total};})),'Rescisao');XLSX.writeFile(wb,'LNB_Planejamento_RH_'+iso(anchorDate())+'.xlsx');toast('Planejamento exportado.');}catch(e){toast('Não foi possível exportar: '+e.message,true);}}
  function addStyles(){if($('_rh_plan_v24'))return;var st=document.createElement('style');st.id='_rh_plan_v24';st.textContent='\
.rh-plan-warning{display:flex;gap:10px;align-items:flex-start;padding:10px 14px;margin-bottom:14px;border:1px solid color-mix(in srgb,var(--gold) 45%,var(--line-soft));border-radius:12px;background:color-mix(in srgb,var(--gold) 7%,var(--surface));font-size:.72rem}.rh-plan-warning b{color:var(--gold-2);white-space:nowrap}.rh-plan-warning span{color:var(--muted)}\
.rh-plan-tabs{display:flex;gap:8px;flex-wrap:wrap;margin:0 0 16px}.rh-plan-tabs button{border:1px solid var(--line-soft);background:var(--surface-2);color:var(--muted);border-radius:10px;padding:9px 13px;font-weight:850;cursor:pointer}.rh-plan-tabs button.active{color:var(--text);border-color:var(--gold);background:color-mix(in srgb,var(--gold) 10%,var(--surface-2))}.rh-plan-pane{display:none}.rh-plan-pane.active{display:block}.rh-plan-pane table{min-width:1080px}.rh-plan-pane tfoot td{border-top:2px solid var(--gold);background:var(--surface-2)}\
.rh-plan-forecast-controls{display:flex;justify-content:flex-end;gap:10px;align-items:end;margin-bottom:12px}.rh-plan-forecast-controls label,.rh-plan-form label{display:grid;gap:5px;color:var(--muted);font-size:.68rem;font-weight:850;text-transform:uppercase}.rh-plan-forecast-controls input,.rh-plan-form input,.rh-plan-form select{height:40px;border:1px solid var(--line-soft);border-radius:9px;background:var(--surface-2);color:var(--text);padding:0 10px}.rh-plan-forecast-controls input{width:150px}\
.rh-plan-form{display:grid;grid-template-columns:1fr 1fr;gap:12px}.rh-plan-form .button{grid-column:1/-1}.rh-res-meta{display:flex;gap:10px;flex-wrap:wrap;margin:12px 0}.rh-res-meta span{padding:7px 9px;border:1px solid var(--line-soft);border-radius:8px;color:var(--muted);font-size:.7rem}.rh-res-meta b{color:var(--text)}.rh-res-lines>div{display:flex;justify-content:space-between;gap:12px;padding:9px 2px;border-bottom:1px solid var(--line-soft)}.rh-res-lines .negative{color:var(--red)}.rh-res-lines .total{margin-top:10px;padding-top:14px;border-top:2px solid var(--gold);border-bottom:0}.rh-res-lines .total strong{font-size:1.3rem;color:var(--gold-2)}\
@media(max-width:850px){.rh-plan-res-grid{grid-template-columns:1fr!important}.rh-plan-form{grid-template-columns:1fr}.rh-plan-forecast-controls{align-items:stretch;flex-direction:column}.rh-plan-forecast-controls input{width:100%}}';document.head.appendChild(st);}
  var oldSetup=setupUI;setupUI=function(){var r=oldSetup.apply(this,arguments);ensurePage();renderPlanning();return r;};
  var oldRenderAll=renderAll;renderAll=function(){var r=oldRenderAll.apply(this,arguments);if($('page-planejamento'))renderPlanning();return r;};
  window.rhRenderPlanning=renderPlanning;window.rhPlanTermination=terminationCalc;
})();
