/* RH v40 — relatórios executivos, guias gerenciais e encaixe estável de cards */
(function(){
'use strict';
var V={fitTimer:0,resize:null,ui:false};
var GOLD='#f2c94c',NAVY='#071a2c',NAVY2='#0d2b42',BLUE='#1f6f9f',EMERALD='#1f9d7a',RED='#d75858',MUTED='#6b7d90',LIGHT='#eef4f8',LINE='#d7e1e8';
function E(id){return document.getElementById(id)}
function n(v){var x=Number(v);return isFinite(x)?x:0}
function esc40(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function norm(v){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()}
function brMoney(v){return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(n(v))}
function compLabel(v){try{return formatCompetence(v)}catch(e){if(!v)return '—';var p=String(v).slice(0,7).split('-');return p[1]+'/'+p[0]}}
function compSlug(v){var x=compLabel(v).replace('/','-');return x==='—'?'sem-competencia':x}
function filename(base,ext){return base+'_'+compSlug(S.competencia&&S.competencia.competencia)+'.'+ext}
function companyName(){return String(S.competencia&&S.competencia.empresa_nome||'LIGA NACIONAL DE BASQUETE')}
function companyCode(){return String(S.competencia&&S.competencia.empresa_codigo||'2038')}
function currentPeople(){return (S.pessoas||[]).slice().sort(function(a,b){return String(a.nome||'').localeCompare(String(b.nome||''),'pt-BR')})}
function chargeObject(){return S.competencia&&S.competencia.encargos||{}}
function chargeRows(){var e=chargeObject(),c=S.competencia||{};return[
  {key:'IRRF',label:'IRRF',base:n(e.base_irrf_mensal||c.resumo&&c.resumo.base_irrf),value:n(e.valor_total_irrf||e.valor_irrf_mensal||e.valor_irrf)},
  {key:'INSS',label:'INSS',base:n(e.base_total_inss||c.resumo&&c.resumo.base_inss),value:n(e.total_inss)},
  {key:'PIS',label:'PIS sobre folha',base:n(e.base_pis||c.resumo&&c.resumo.base_inss),value:n(e.valor_pis)},
  {key:'FGTS',label:'FGTS',base:n(e.base_fgts||c.resumo&&c.resumo.base_fgts),value:n(e.valor_fgts||c.valor_fgts)}
]}
function depRows(){var map={};currentPeople().forEach(function(p){var d=String(p.departamento||p.departamento_snapshot||'Sem departamento'),name;try{name=departmentName(d)}catch(e){name=d}if(!map[name])map[name]={departamento:name,pessoas:0,proventos:0,descontos:0,liquido:0,fgts:0};var x=map[name];x.pessoas++;x.proventos+=n(p.proventos);x.descontos+=n(p.descontos);x.liquido+=n(p.liquido);x.fgts+=n(p.valor_fgts)});return Object.keys(map).map(function(k){return map[k]}).sort(function(a,b){return b.liquido-a.liquido})}
function rubricRows(){var map={};(S.lancamentos||[]).forEach(function(l){var k=String(l.rubrica_codigo||'')+'|'+String(l.rubrica_nome||l.nome||'')+'|'+String(l.tipo||'');if(!map[k])map[k]={codigo:String(l.rubrica_codigo||''),nome:String(l.rubrica_nome||l.nome||'—'),tipo:String(l.tipo||'—'),valor:0};map[k].valor+=n(l.valor)});return Object.keys(map).map(function(k){return map[k]}).sort(function(a,b){return b.valor-a.valor})}
function ccRows(){var map={};currentPeople().forEach(function(p){var cc=String(p.centro_custo||p.centro_custo_snapshot||'Sem CC');if(!map[cc])map[cc]={cc:cc,pessoas:0,proventos:0,descontos:0,liquido:0};var x=map[cc];x.pessoas++;x.proventos+=n(p.proventos);x.descontos+=n(p.descontos);x.liquido+=n(p.liquido)});return Object.keys(map).map(function(k){return map[k]}).sort(function(a,b){return b.liquido-a.liquido})}
function totals(){var c=S.competencia||{},charges=chargeRows(),totalCharges=charges.reduce(function(s,x){return s+x.value},0);return{proventos:n(c.proventos),descontos:n(c.descontos),liquido:n(c.liquido),fgts:n(c.valor_fgts||chargeObject().valor_fgts),pessoas:currentPeople().length,encargos:totalCharges}}

/* encaixe estável: sem MutationObserver e sem reflow contínuo */
var FIT_SELECTOR='.kpi strong,.rh-close-stat strong,.rh-history-metric strong,.metric-row strong,.preview-summary strong,.summary-card strong,.stat-card strong,#rh-dossier-kpis strong,#rh-insight-kpis strong,#custo-real-kpis strong,#payroll-kpis strong,#charges-kpis strong,#movement-kpis strong';
var fitCanvas=document.createElement('canvas'),fitCtx=fitCanvas.getContext('2d');
function fitTextWidth(el,size){if(!fitCtx)return 999999;var cs=getComputedStyle(el);fitCtx.font=(cs.fontWeight||700)+' '+size+'px '+(cs.fontFamily||'sans-serif');return fitCtx.measureText(String(el.textContent||'').trim()).width}
function fitAvailable(el){var box=el.closest('.kpi,.rh-close-stat,.rh-history-metric,.metric-row,.preview-summary,.summary-card,.stat-card')||el.parentElement;if(!box)return 0;var bcs=getComputedStyle(box),w=box.clientWidth-(parseFloat(bcs.paddingLeft)||0)-(parseFloat(bcs.paddingRight)||0);var ecs=getComputedStyle(el),ml=parseFloat(ecs.marginLeft)||0,mr=parseFloat(ecs.marginRight)||0;return Math.max(56,w-ml-mr-10)}
function fitOne(el){if(!el||!el.isConnected||el.closest('#page-planejamento'))return;var text=String(el.textContent||'').trim();if(!text)return;var av=fitAvailable(el);if(!av)return;var max=36,min=10;if(text.length>10)max=31;if(text.length>14)max=27;if(text.length>18)max=23;if(text.length>22)max=20;var lo=min,hi=max,best=min;for(var i=0;i<18;i++){var mid=(lo+hi)/2;if(fitTextWidth(el,mid)<=av){best=mid;lo=mid}else hi=mid}var size=Math.max(min,Math.floor(best*10)/10);el.style.setProperty('font-size',size+'px','important');el.style.setProperty('letter-spacing',size<18?'-.055em':size<23?'-.04em':'-.02em','important');el.style.setProperty('white-space','nowrap','important');el.style.setProperty('overflow','hidden','important');el.style.setProperty('text-overflow','clip','important');el.style.setProperty('max-width','100%','important');el.style.setProperty('width','100%','important')}
function fitAll(){Array.prototype.forEach.call(document.querySelectorAll(FIT_SELECTOR),fitOne)}
function scheduleFit(delay){clearTimeout(V.fitTimer);V.fitTimer=setTimeout(function(){requestAnimationFrame(fitAll)},delay==null?50:delay)}
window.rhFitAllCardValues=fitAll;
function installFit(){if(!E('_rh40_fit')){var st=document.createElement('style');st.id='_rh40_fit';st.textContent='.kpi,.rh-close-stat,.rh-history-metric,.metric-row,.preview-summary,.summary-card,.stat-card{min-width:0!important;overflow:hidden!important}.kpi strong,.rh-close-stat strong,.rh-history-metric strong,.metric-row strong,.preview-summary strong,.summary-card strong,.stat-card strong{display:block!important;min-width:0!important;max-width:100%!important;line-height:1.02!important;transition:none!important;animation:none!important}';document.head.appendChild(st)}if(window.ResizeObserver){V.resize=new ResizeObserver(function(){scheduleFit(70)});document.querySelectorAll('.kpi,.rh-close-stat,.rh-history-metric,.metric-row,.preview-summary,.summary-card,.stat-card').forEach(function(x){if(x.closest('#page-planejamento'))return;try{V.resize.observe(x)}catch(e){}})}window.addEventListener('resize',function(){scheduleFit(80)});if(document.fonts&&document.fonts.ready)document.fonts.ready.then(function(){scheduleFit(0)});scheduleFit(0)}

/* bibliotecas para relatórios */
LIBRARIES.jspdf={url:'https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js',ready:function(){return !!(window.jspdf&&window.jspdf.jsPDF)}};
LIBRARIES.autotable={url:'https://cdnjs.cloudflare.com/ajax/libs/jspdf-autotable/3.8.4/jspdf.plugin.autotable.min.js',ready:function(){return !!(window.jspdf&&window.jspdf.jsPDF&&window.jspdf.jsPDF.API&&window.jspdf.jsPDF.API.autoTable)}};
LIBRARIES.exceljs={url:'https://cdn.jsdelivr.net/npm/exceljs@4.4.0/dist/exceljs.min.js',ready:function(){return !!window.ExcelJS}};
async function ensurePdf(){await loadLibrary('jspdf');await loadLibrary('autotable')}
async function ensureExcel(){await loadLibrary('exceljs')}
function downloadBlob(blob,name){var a=document.createElement('a'),u=URL.createObjectURL(blob);a.href=u;a.download=name;document.body.appendChild(a);a.click();setTimeout(function(){URL.revokeObjectURL(u);a.remove()},1000)}
async function imageData(url){try{var r=await fetch(url);if(!r.ok)return null;var b=await r.blob();return await new Promise(function(res){var fr=new FileReader();fr.onload=function(){res(fr.result)};fr.onerror=function(){res(null)};fr.readAsDataURL(b)})}catch(e){return null}}
function hexRgb(hex){hex=String(hex).replace('#','');return [parseInt(hex.slice(0,2),16),parseInt(hex.slice(2,4),16),parseInt(hex.slice(4,6),16)]}
function setFill(doc,hex){var r=hexRgb(hex);doc.setFillColor(r[0],r[1],r[2])}
function setText(doc,hex){var r=hexRgb(hex);doc.setTextColor(r[0],r[1],r[2])}
function pdfHeader(doc,title,subtitle,logo){var w=doc.internal.pageSize.getWidth();setFill(doc,NAVY);doc.rect(0,0,w,31,'F');if(logo)try{doc.addImage(logo,'PNG',12,6,22,18);doc.__rhBrandApplied=true}catch(e){}setText(doc,'#ffffff');doc.setFont('helvetica','bold');doc.setFontSize(16);doc.text(title,40,13);doc.setFont('helvetica','normal');doc.setFontSize(8.5);doc.text(subtitle||'',40,20);setText(doc,GOLD);doc.setFont('helvetica','bold');doc.setFontSize(8);doc.text('LIGA NACIONAL DE BASQUETE',40,26)}
function pdfFooter(doc){var pages=doc.internal.getNumberOfPages();for(var i=1;i<=pages;i++){doc.setPage(i);var w=doc.internal.pageSize.getWidth(),h=doc.internal.pageSize.getHeight();setText(doc,MUTED);doc.setFont('helvetica','normal');doc.setFontSize(7.5);doc.text('Uso restrito - Diretoria | RH & Folha | '+compLabel(S.competencia&&S.competencia.competencia),12,h-7);doc.text('Página '+i+' de '+pages,w-12,h-7,{align:'right'})}}
function pdfKpis(doc,y,items){var w=doc.internal.pageSize.getWidth(),gap=4,x=12,cardW=(w-24-gap*(items.length-1))/items.length;items.forEach(function(it,idx){var xx=x+idx*(cardW+gap);setFill(doc,idx===items.length-1?NAVY2:'#eef4f8');doc.roundedRect(xx,y,cardW,24,3,3,'F');setText(doc,idx===items.length-1?'#ffffff':MUTED);doc.setFont('helvetica','bold');doc.setFontSize(7);doc.text(String(it[0]).toUpperCase(),xx+4,y+7);setText(doc,idx===items.length-1?GOLD:NAVY);doc.setFontSize(12);doc.text(String(it[1]),xx+4,y+17,{maxWidth:cardW-8})});return y+30}
function deptChart(){var a=depRows().slice(0,8),cv=document.createElement('canvas');cv.width=1000;cv.height=Math.max(260,a.length*54+70);var x=cv.getContext('2d'),max=Math.max.apply(null,a.map(function(d){return d.liquido}).concat([1]));x.fillStyle='#ffffff';x.fillRect(0,0,cv.width,cv.height);x.font='700 23px Segoe UI, Arial';x.fillStyle=NAVY;x.fillText('Líquido por departamento',28,36);a.forEach(function(d,i){var y=70+i*54,w=(cv.width-360)*(d.liquido/max);x.font='600 19px Segoe UI, Arial';x.fillStyle='#334b5f';x.fillText(d.departamento,28,y+19);x.fillStyle='#dce8ef';x.fillRect(260,y,cv.width-350,26);x.fillStyle=i===0?GOLD:BLUE;x.fillRect(260,y,w,26);x.fillStyle=NAVY;x.font='700 18px Segoe UI, Arial';x.textAlign='right';x.fillText(brMoney(d.liquido),cv.width-25,y+20);x.textAlign='left'});return cv.toDataURL('image/png')}

async function exportPayrollPdf(){if(!S.competencia)throw new Error('Selecione uma competência.');await ensurePdf();var jsPDF=window.jspdf.jsPDF,doc=new jsPDF({orientation:'landscape',unit:'mm',format:'a4',compress:true}),logo=await imageData('/rh/lnb-logo.png'),t=totals(),e=chargeObject(),subtitle='Relatório Executivo da Folha - '+compLabel(S.competencia.competencia)+' | Empresa '+companyCode();pdfHeader(doc,'Folha de Pagamento - Relatório Executivo',subtitle,logo);var y=37;y=pdfKpis(doc,y,[['Proventos',brMoney(t.proventos)],['Descontos',brMoney(t.descontos)],['Líquido',brMoney(t.liquido)],['Pessoas',String(t.pessoas)],['FGTS',brMoney(t.fgts)]]);
  var chart=deptChart();try{doc.addImage(chart,'PNG',12,y,128,46)}catch(ignore){}
  doc.autoTable({startY:y,margin:{left:148,right:12},head:[['Obrigação','Base','Valor']],body:chargeRows().map(function(r){return[r.label,brMoney(r.base),brMoney(r.value)]}),foot:[['Total','',''+brMoney(chargeRows().reduce(function(s,r){return s+r.value},0))]],theme:'grid',styles:{font:'helvetica',fontSize:8,cellPadding:2.5,textColor:hexRgb(NAVY)},headStyles:{fillColor:hexRgb(NAVY2),textColor:[255,255,255],fontStyle:'bold'},footStyles:{fillColor:hexRgb(LIGHT),textColor:hexRgb(NAVY),fontStyle:'bold'},columnStyles:{1:{halign:'right'},2:{halign:'right',fontStyle:'bold'}}});
  y=Math.max(y+51,doc.lastAutoTable.finalY+5);doc.autoTable({startY:y,head:[['Departamento','Pessoas','Proventos','Descontos','Líquido','FGTS']],body:depRows().map(function(r){return[r.departamento,r.pessoas,brMoney(r.proventos),brMoney(r.descontos),brMoney(r.liquido),brMoney(r.fgts)]}),theme:'striped',styles:{font:'helvetica',fontSize:7.7,cellPadding:2.3,textColor:hexRgb(NAVY)},headStyles:{fillColor:hexRgb(NAVY2),textColor:[255,255,255]},alternateRowStyles:{fillColor:[247,250,252]},columnStyles:{1:{halign:'center'},2:{halign:'right'},3:{halign:'right'},4:{halign:'right',fontStyle:'bold'},5:{halign:'right'}}});
  doc.addPage('a4','landscape');pdfHeader(doc,'Composição Individual da Folha','Competência '+compLabel(S.competencia.competencia)+' | '+companyName(),logo);doc.autoTable({startY:36,margin:{left:10,right:10,bottom:14},head:[['Matr.','Colaborador','Vínculo','Situação','Departamento','CC','Salário','Proventos','Descontos','Líquido','FGTS']],body:currentPeople().map(function(p){var dep;try{dep=departmentName(p.departamento||p.departamento_snapshot)}catch(e2){dep=p.departamento||p.departamento_snapshot||'—'}return[p.matricula||'—',p.nome||'—',p.vinculo||p.vinculo_snapshot||'—',p.situacao||p.situacao_snapshot||'—',dep,p.centro_custo||p.centro_custo_snapshot||'—',brMoney(p.salario),brMoney(p.proventos),brMoney(p.descontos),brMoney(p.liquido),brMoney(p.valor_fgts)]}),theme:'striped',styles:{font:'helvetica',fontSize:6.5,cellPadding:1.8,textColor:hexRgb(NAVY)},headStyles:{fillColor:hexRgb(NAVY2),textColor:[255,255,255],fontStyle:'bold'},alternateRowStyles:{fillColor:[247,250,252]},columnStyles:{6:{halign:'right'},7:{halign:'right'},8:{halign:'right'},9:{halign:'right',fontStyle:'bold'},10:{halign:'right'}}});
  doc.addPage('a4','landscape');pdfHeader(doc,'Rubricas e Bases de Encargos','Competência '+compLabel(S.competencia.competencia),logo);doc.autoTable({startY:36,margin:{left:12,right:150},head:[['Código','Rubrica','Tipo','Valor']],body:rubricRows().map(function(r){return[r.codigo||'—',r.nome,r.tipo,brMoney(r.valor)]}),theme:'striped',styles:{font:'helvetica',fontSize:7,cellPadding:2,textColor:hexRgb(NAVY)},headStyles:{fillColor:hexRgb(NAVY2),textColor:[255,255,255]},columnStyles:{3:{halign:'right',fontStyle:'bold'}}});var start=36;doc.autoTable({startY:start,margin:{left:155,right:12},head:[['Indicador','Valor']],body:[['Base INSS',brMoney(e.base_total_inss||0)],['Base FGTS',brMoney(e.base_fgts||0)],['Base PIS',brMoney(e.base_pis||0)],['Base IRRF',brMoney(e.base_irrf_mensal||0)],['INSS total',brMoney(e.total_inss||0)],['FGTS',brMoney(e.valor_fgts||0)],['PIS',brMoney(e.valor_pis||0)],['IRRF',brMoney(e.valor_total_irrf||e.valor_irrf||0)]],theme:'grid',styles:{font:'helvetica',fontSize:8,cellPadding:2.5,textColor:hexRgb(NAVY)},headStyles:{fillColor:hexRgb(NAVY2),textColor:[255,255,255]},columnStyles:{1:{halign:'right',fontStyle:'bold'}}});
  pdfFooter(doc);doc.save(filename('LNB_Folha_Executiva','pdf'))}

function guideInfo(kind){var all=chargeRows(),r=all.find(function(x){return x.key===kind});if(!r)throw new Error('Encargo não encontrado.');var note='Valor extraído da folha importada. Esta guia é uma memória gerencial e não substitui DARF, DCTFWeb, FGTS Digital ou documento oficial de arrecadação.';return{key:r.key,label:r.label,base:r.base,value:r.value,note:note}}
async function buildGuidePdf(kinds,save){await ensurePdf();var jsPDF=window.jspdf.jsPDF,doc=new jsPDF({orientation:'portrait',unit:'mm',format:'a4',compress:true}),logo=await imageData('/rh/lnb-logo.png');for(var z=0;z<kinds.length;z++){if(z)doc.addPage();var g=guideInfo(kinds[z]),w=doc.internal.pageSize.getWidth();pdfHeader(doc,'Guia Gerencial - '+g.label,'Competência '+compLabel(S.competencia.competencia)+' | Empresa '+companyCode(),logo);setFill(doc,'#f7fafc');doc.roundedRect(12,40,w-24,46,4,4,'F');setText(doc,MUTED);doc.setFont('helvetica','bold');doc.setFontSize(8);doc.text('VALOR PARA CONFERÊNCIA',18,51);setText(doc,NAVY);doc.setFontSize(24);doc.text(brMoney(g.value),18,66);setText(doc,MUTED);doc.setFontSize(8);doc.setFont('helvetica','normal');doc.text('Base informada: '+brMoney(g.base),18,78);doc.autoTable({startY:96,margin:{left:12,right:12},head:[['Campo','Informação']],body:[['Empresa',companyName()],['Código da empresa',companyCode()],['Competência',compLabel(S.competencia.competencia)],['Obrigação',g.label],['Base',brMoney(g.base)],['Valor',brMoney(g.value)],['Origem','RH & Folha - competência importada']],theme:'grid',styles:{font:'helvetica',fontSize:9,cellPadding:3,textColor:hexRgb(NAVY)},headStyles:{fillColor:hexRgb(NAVY2),textColor:[255,255,255]},columnStyles:{0:{fontStyle:'bold',cellWidth:48},1:{}}});var yy=doc.lastAutoTable.finalY+10;setFill(doc,'#fff8df');doc.roundedRect(12,yy,w-24,30,3,3,'F');setText(doc,'#7a5d00');doc.setFont('helvetica','bold');doc.setFontSize(8);doc.text('ATENÇÃO',18,yy+9);doc.setFont('helvetica','normal');doc.setFontSize(8.3);doc.text(doc.splitTextToSize(g.note,w-36),18,yy+16);setText(doc,MUTED);doc.setFontSize(7.5);doc.text('Gerado em '+new Date().toLocaleString('pt-BR')+' | Uso interno e restrito',12,280)}pdfFooter(doc);if(save!==false)doc.save(filename(kinds.length===1?'LNB_Guia_'+kinds[0]:'LNB_Pacote_Guias','pdf'));return doc}
async function exportGuide(kind){if(!S.competencia)throw new Error('Selecione uma competência.');return buildGuidePdf([kind],true)}
async function exportGuidePack(){if(!S.competencia)throw new Error('Selecione uma competência.');return buildGuidePdf(['IRRF','INSS','PIS','FGTS'],true)}

function xStyleHeader(cell){cell.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF0D2B42'}};cell.font={name:'Aptos',bold:true,color:{argb:'FFFFFFFF'},size:10};cell.alignment={vertical:'middle',horizontal:'center'};cell.border={bottom:{style:'thin',color:{argb:'FFF2C94C'}}}}
function xMoney(cell){cell.numFmt='R$ #,##0.00;[Red]-R$ #,##0.00';cell.alignment={horizontal:'right'}}
function xAutoWidth(ws,max){ws.columns.forEach(function(col){var m=10;col.eachCell({includeEmpty:true},function(c){var v=c.value;if(v&&typeof v==='object'&&v.richText)v=v.richText.map(function(x){return x.text}).join('');m=Math.max(m,String(v==null?'':v).length+2)});col.width=Math.min(max||34,Math.max(10,m))})}
function xTitle(ws,title,subtitle,lastCol){ws.mergeCells(1,1,2,lastCol);var c=ws.getCell(1,1);c.value=title;c.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF071A2C'}};c.font={name:'Aptos Display',bold:true,size:22,color:{argb:'FFF2C94C'}};c.alignment={vertical:'middle',horizontal:'left'};ws.getRow(1).height=28;ws.getRow(2).height=8;ws.mergeCells(3,1,3,lastCol);var s=ws.getCell(3,1);s.value=subtitle;s.font={name:'Aptos',size:10,color:{argb:'FF5F7486'},italic:true};ws.getRow(3).height=20}
async function exportPayrollExcel(){if(!S.competencia)throw new Error('Selecione uma competência.');await ensureExcel();var wb=new ExcelJS.Workbook();wb.creator='LNB - RH & Folha';wb.company='Liga Nacional de Basquete';wb.subject='Relatório executivo da folha';wb.created=new Date();var t=totals(),e=chargeObject();
  var ws=wb.addWorksheet('Resumo Executivo',{views:[{showGridLines:false,state:'frozen',ySplit:5}]});xTitle(ws,'LNB | FOLHA DE PAGAMENTO','Relatório Executivo - '+compLabel(S.competencia.competencia)+' | '+companyName()+' | Empresa '+companyCode(),8);var labels=[['Proventos',t.proventos],['Descontos',t.descontos],['Líquido',t.liquido],['Pessoas',t.pessoas],['FGTS',t.fgts],['Encargos',t.encargos]];labels.forEach(function(it,i){var col=i+1,lab=ws.getCell(5,col),val=ws.getCell(6,col);lab.value=it[0].toUpperCase();lab.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF0D2B42'}};lab.font={bold:true,color:{argb:'FFFFFFFF'},size:9};lab.alignment={horizontal:'center'};val.value=it[1];val.fill={type:'pattern',pattern:'solid',fgColor:{argb:i===2?'FFFFF5D6':'FFF0F5F8'}};val.font={bold:true,color:{argb:'FF071A2C'},size:13};val.alignment={horizontal:'center'};if(i!==3)xMoney(val)});ws.getRow(6).height=26;
  ws.getCell('A9').value='OBRIGAÇÕES';ws.getCell('A9').font={bold:true,color:{argb:'FFF2C94C'},size:12};ws.getCell('A10').value='Obrigação';ws.getCell('B10').value='Base';ws.getCell('C10').value='Valor';['A10','B10','C10'].forEach(function(a){xStyleHeader(ws.getCell(a))});chargeRows().forEach(function(r,i){var row=11+i;ws.getCell(row,1).value=r.label;ws.getCell(row,2).value=r.base;ws.getCell(row,3).value=r.value;xMoney(ws.getCell(row,2));xMoney(ws.getCell(row,3))});
  var ds=18;ws.getCell(ds,1).value='DISTRIBUIÇÃO POR DEPARTAMENTO';ws.getCell(ds,1).font={bold:true,color:{argb:'FFF2C94C'},size:12};var dh=['Departamento','Pessoas','Proventos','Descontos','Líquido','FGTS'];dh.forEach(function(h,i){ws.getCell(ds+1,i+1).value=h;xStyleHeader(ws.getCell(ds+1,i+1))});depRows().forEach(function(r,i){var row=ds+2+i,vals=[r.departamento,r.pessoas,r.proventos,r.descontos,r.liquido,r.fgts];vals.forEach(function(v,j){ws.getCell(row,j+1).value=v;if(j>=2)xMoney(ws.getCell(row,j+1))});if(i%2)for(var j=1;j<=6;j++)ws.getCell(row,j).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FFF7FAFC'}}});xAutoWidth(ws,28);

  var wf=wb.addWorksheet('Folha por Colaborador',{views:[{state:'frozen',ySplit:5,xSplit:2,showGridLines:false}]});xTitle(wf,'FOLHA POR COLABORADOR','Competência '+compLabel(S.competencia.competencia)+' | Valores individuais',14);var headers=['Matrícula','Colaborador','Vínculo','Situação','Cargo','Departamento','Centro de Custo','Salário','Proventos','Descontos','Líquido','Base INSS','FGTS','Base IRRF'];headers.forEach(function(h,i){wf.getCell(5,i+1).value=h;xStyleHeader(wf.getCell(5,i+1))});currentPeople().forEach(function(p,i){var row=6+i,dep;try{dep=departmentName(p.departamento||p.departamento_snapshot)}catch(er){dep=p.departamento||p.departamento_snapshot||'—'};var vals=[p.matricula||'',p.nome||'',p.vinculo||p.vinculo_snapshot||'',p.situacao||p.situacao_snapshot||'',p.cargo||p.cargo_snapshot||'',dep,p.centro_custo||p.centro_custo_snapshot||'',n(p.salario),n(p.proventos),n(p.descontos),n(p.liquido),n(p.base_inss),n(p.valor_fgts),n(p.base_irrf)];vals.forEach(function(v,j){var c=wf.getCell(row,j+1);c.value=v;if(j>=7)xMoney(c);if(i%2)c.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FFF7FAFC'}}})});var fr=6+currentPeople().length;wf.getCell(fr,1).value='TOTAL';wf.mergeCells(fr,1,fr,7);wf.getCell(fr,1).font={bold:true,color:{argb:'FFFFFFFF'}};wf.getCell(fr,1).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF0D2B42'}};[8,9,10,11,12,13,14].forEach(function(col){var c=wf.getCell(fr,col),letter=wf.getColumn(col).letter;c.value={formula:'SUM('+letter+'6:'+letter+(fr-1)+')'};xMoney(c);c.font={bold:true,color:{argb:'FFFFFFFF'}};c.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF0D2B42'}}});wf.autoFilter={from:{row:5,column:1},to:{row:5,column:14}};xAutoWidth(wf,34);

  var wr=wb.addWorksheet('Rubricas',{views:[{state:'frozen',ySplit:5,showGridLines:false}]});xTitle(wr,'RUBRICAS','Consolidação da competência '+compLabel(S.competencia.competencia),5);['Código','Rubrica','Tipo','Valor','% dos Proventos'].forEach(function(h,i){wr.getCell(5,i+1).value=h;xStyleHeader(wr.getCell(5,i+1))});rubricRows().forEach(function(r,i){var row=6+i;wr.getCell(row,1).value=r.codigo;wr.getCell(row,2).value=r.nome;wr.getCell(row,3).value=r.tipo;wr.getCell(row,4).value=r.valor;xMoney(wr.getCell(row,4));wr.getCell(row,5).value=t.proventos?r.valor/t.proventos:0;wr.getCell(row,5).numFmt='0.00%';if(i%2)for(var j=1;j<=5;j++)wr.getCell(row,j).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FFF7FAFC'}}});wr.autoFilter={from:{row:5,column:1},to:{row:5,column:5}};xAutoWidth(wr,42);

  var we=wb.addWorksheet('Encargos',{views:[{showGridLines:false}]});xTitle(we,'ENCARGOS E RECOLHIMENTOS','Bases e valores extraídos da competência '+compLabel(S.competencia.competencia),4);['Obrigação','Base','Valor','Observação'].forEach(function(h,i){we.getCell(5,i+1).value=h;xStyleHeader(we.getCell(5,i+1))});chargeRows().forEach(function(r,i){var row=6+i;we.getCell(row,1).value=r.label;we.getCell(row,2).value=r.base;we.getCell(row,3).value=r.value;we.getCell(row,4).value='Conferir com documento oficial de arrecadação';xMoney(we.getCell(row,2));xMoney(we.getCell(row,3))});var extras=[['RAT',n(e.rat)],['Terceiros',n(e.terceiros)],['Segurados INSS',n(e.segurados)],['Base total INSS',n(e.base_total_inss)]];extras.forEach(function(r,i){var row=12+i;we.getCell(row,1).value=r[0];we.getCell(row,3).value=r[1];xMoney(we.getCell(row,3))});xAutoWidth(we,42);

  var wc=wb.addWorksheet('Rateio',{views:[{state:'frozen',ySplit:5,showGridLines:false}]});xTitle(wc,'RATEIO DA FOLHA','Departamento e centro de custo - '+compLabel(S.competencia.competencia),6);['Centro de Custo','Pessoas','Proventos','Descontos','Líquido','% do Líquido'].forEach(function(h,i){wc.getCell(5,i+1).value=h;xStyleHeader(wc.getCell(5,i+1))});ccRows().forEach(function(r,i){var row=6+i;wc.getCell(row,1).value=r.cc;wc.getCell(row,2).value=r.pessoas;wc.getCell(row,3).value=r.proventos;wc.getCell(row,4).value=r.descontos;wc.getCell(row,5).value=r.liquido;wc.getCell(row,6).value=t.liquido?r.liquido/t.liquido:0;[3,4,5].forEach(function(col){xMoney(wc.getCell(row,col))});wc.getCell(row,6).numFmt='0.00%';if(i%2)for(var j=1;j<=6;j++)wc.getCell(row,j).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FFF7FAFC'}}});xAutoWidth(wc,30);

  var wq=wb.addWorksheet('Conferência',{views:[{showGridLines:false}]});xTitle(wq,'CONFERÊNCIA','Reconciliação automática dos valores - '+compLabel(S.competencia.competencia),5);['Indicador','Total oficial','Soma individual','Diferença','Status'].forEach(function(h,i){wq.getCell(5,i+1).value=h;xStyleHeader(wq.getCell(5,i+1))});var ps=currentPeople(),checks=[['Proventos',t.proventos,ps.reduce(function(s,p){return s+n(p.proventos)},0)],['Descontos',t.descontos,ps.reduce(function(s,p){return s+n(p.descontos)},0)],['Líquido',t.liquido,ps.reduce(function(s,p){return s+n(p.liquido)},0)],['FGTS',t.fgts,ps.reduce(function(s,p){return s+n(p.valor_fgts)},0)]];checks.forEach(function(q,i){var row=6+i,d=q[1]-q[2];wq.getCell(row,1).value=q[0];wq.getCell(row,2).value=q[1];wq.getCell(row,3).value=q[2];wq.getCell(row,4).value=d;wq.getCell(row,5).value=Math.abs(d)<0.02?'OK':'REVISAR';[2,3,4].forEach(function(col){xMoney(wq.getCell(row,col))});wq.getCell(row,5).font={bold:true,color:{argb:Math.abs(d)<0.02?'FF1F7A5B':'FFC34242'}}});xAutoWidth(wq,28);

  var buf=await wb.xlsx.writeBuffer();downloadBlob(new Blob([buf],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),filename('LNB_Folha_Executiva','xlsx'))}

function guideCardsHtml(){return chargeRows().map(function(r){return '<div class="rh40-guide-card"><span>'+esc40(r.label)+'</span><strong>'+esc40(brMoney(r.value))+'</strong><small>Base '+esc40(brMoney(r.base))+'</small><button type="button" class="button ghost export-only" data-rh40-guide="'+r.key+'">Gerar PDF</button></div>'}).join('')}
function installUi(){if(V.ui)return;V.ui=true;var folha=E('page-folha'),enc=E('page-encargos');if(folha){var head=folha.querySelector('.page-head');if(head&&!E('rh40-report-actions')){var a=document.createElement('div');a.className='head-actions rh40-actions';a.id='rh40-report-actions';a.innerHTML='<label>Competência<select id="rh40-comp-select"></select></label><button class="button primary export-only" id="rh40-pdf" type="button">PDF Executivo</button><button class="button secondary export-only" id="rh40-xlsx" type="button">Excel Executivo</button><button class="button ghost export-only" id="rh40-guides" type="button">Pacote de Guias</button>';head.appendChild(a)}}if(enc&&!E('rh40-guides-panel')){var panel=document.createElement('article');panel.className='panel rh40-guide-panel';panel.id='rh40-guides-panel';panel.innerHTML='<div class="panel-head"><div><span class="panel-kicker">RELATÓRIOS PARA PAGAMENTO</span><h2>Guias gerenciais da competência</h2><p class="detail-note">IRRF, INSS, PIS e FGTS com bases e valores extraídos da folha. Para pagamento, confronte com o documento oficial do respectivo portal.</p></div><button type="button" class="button primary export-only" id="rh40-guides-pack">Gerar pacote PDF</button></div><div class="rh40-guide-grid" id="rh40-guide-grid"></div>';var k=enc.querySelector('#charges-kpis');if(k)k.insertAdjacentElement('afterend',panel);else enc.appendChild(panel)}
  var st=document.createElement('style');st.id='_rh40_reports';st.textContent='.rh40-actions{display:flex!important;gap:8px!important;align-items:flex-end!important;flex-wrap:wrap!important}.rh40-actions label{min-width:135px}.rh40-guide-panel{margin:16px 0 18px}.rh40-guide-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.rh40-guide-card{border:1px solid var(--line-soft);border-radius:14px;background:var(--surface-2);padding:16px;min-width:0;overflow:hidden}.rh40-guide-card span{display:block;color:var(--muted);font-size:.72rem;font-weight:900;letter-spacing:.06em;text-transform:uppercase}.rh40-guide-card strong{display:block;margin:7px 0 3px;font-size:1.35rem;color:var(--text);white-space:nowrap}.rh40-guide-card small{display:block;color:var(--muted);margin-bottom:12px}.rh40-guide-card .button{width:100%}@media(max-width:1100px){.rh40-guide-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:650px){.rh40-guide-grid{grid-template-columns:1fr}.rh40-actions{width:100%}.rh40-actions>*{flex:1 1 160px}}';document.head.appendChild(st);
  bindUi();syncUi()}
function syncUi(){var sel=E('rh40-comp-select');if(sel){var cur=S.competencia&&S.competencia.id||'';sel.innerHTML=(S.competencias||[]).map(function(c){return '<option value="'+esc40(c.id)+'">'+esc40(compLabel(c.competencia))+'</option>'}).join('');if(cur)sel.value=cur}var grid=E('rh40-guide-grid');if(grid)grid.innerHTML=guideCardsHtml();scheduleFit(20);if(typeof setupPermissions==='function')try{setupPermissions()}catch(e){}}
function busy(btn,label,fn){if(!btn)return;var old=btn.textContent;btn.disabled=true;btn.textContent=label;Promise.resolve().then(fn).catch(function(err){try{toast(err.message||String(err),true)}catch(e){alert(err.message||String(err))}}).finally(function(){btn.disabled=false;btn.textContent=old})}
function bindUi(){var sel=E('rh40-comp-select');if(sel)sel.onchange=function(){var id=this.value;busy(this,'Carregando...',async function(){await selectCompetence(id);syncUi()})};var p=E('rh40-pdf');if(p)p.onclick=function(){busy(p,'Gerando PDF...',exportPayrollPdf)};var x=E('rh40-xlsx');if(x)x.onclick=function(){busy(x,'Gerando Excel...',exportPayrollExcel)};var g=E('rh40-guides');if(g)g.onclick=function(){busy(g,'Gerando guias...',exportGuidePack)};var gp=E('rh40-guides-pack');if(gp)gp.onclick=function(){busy(gp,'Gerando pacote...',exportGuidePack)};document.addEventListener('click',function(ev){var b=ev.target&&ev.target.closest&&ev.target.closest('[data-rh40-guide]');if(!b)return;ev.preventDefault();var k=b.dataset.rh40Guide;busy(b,'Gerando...',function(){return exportGuide(k)})})}

function init(){installFit();installUi();var baseSel=E('competencia-select');if(baseSel)baseSel.addEventListener('change',function(){setTimeout(syncUi,100)});var nav=E('nav');if(nav)nav.addEventListener('click',function(){setTimeout(function(){syncUi();scheduleFit(10)},80)});setTimeout(syncUi,600);setTimeout(function(){scheduleFit(0)},900)}
window.rhV40ExportPayrollPdf=exportPayrollPdf;window.rhV40ExportPayrollExcel=exportPayrollExcel;window.rhV40ExportGuide=exportGuide;window.rhV40ExportGuidePack=exportGuidePack;window.RH_EXECUTIVE_REPORTS_V40=true;
init();
})();
