/* RH v26 — provisões e rescisões conforme modelos contábeis anexados */
(function(){
'use strict';
var V={term:null};
function E(id){return document.getElementById(id)}
function h(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function m(v){try{return fmt(Number(v)||0)}catch(e){return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v)||0)}}
function d(v){if(!v)return null;var x=new Date(String(v).slice(0,10)+'T12:00:00');return isNaN(x)?null:x}
function db(v){var x=v instanceof Date?v:d(v);return x?String(x.getDate()).padStart(2,'0')+'/'+String(x.getMonth()+1).padStart(2,'0')+'/'+x.getFullYear():'—'}
function anchor(){var a=(window.RH_PERIOD&&RH_PERIOD.active&&RH_PERIOD.active.length?RH_PERIOD.active:(S.competencia?[S.competencia]:[])).slice().sort(function(a,b){return String(a.competencia||'').localeCompare(String(b.competencia||''))}),c=a[a.length-1],x=d(c&&c.competencia);return x?new Date(x.getFullYear(),x.getMonth()+1,0,12):new Date()}
function key(p){return String(p&&p.colaborador_id||p&&p.id||'')}
function clt(p){try{return rhVinculoCategory(p)==='clt'}catch(e){return /clt|celet/i.test(String(p&&p.vinculo||''))}}
function cc(p){return String(p&&p.centro_custo||p&&p.cc||p&&p.centro_de_custo||'Sem CC')}
function dept(p){try{return departmentName(p.departamento)}catch(e){return String(p.departamento||'—')}}
function people(){var z={},meta={};(S.colaboradores||[]).forEach(function(x){meta[String(x.id)]=x});(S.pessoas||[]).forEach(function(p){var k=key(p);if(k)z[k]=Object.assign({},meta[k]||{},p,{id:k,colaborador_id:k})});return Object.keys(z).map(function(k){return z[k]})}
function rates(){var e=(S.competencia&&S.competencia.encargos)||{},b=Number(e.base_total_inss)||0;return{inss:b&&Number(e.inss_empresa)>0?Number(e.inss_empresa)/b:.20,rat:b&&Number(e.rat)>0?Number(e.rat)/b:.01,terc:b&&Number(e.terceiros)>0?Number(e.terceiros)/b:.058,fgts:.08,pis:b&&Number(e.valor_pis)>0?Number(e.valor_pis)/b:.01}}
function charges(base,r){return{inss:base*r.inss,rat:base*r.rat,terc:base*r.terc,fgts:base*r.fgts,pis:base*r.pis}}
function ct(e){return e.inss+e.rat+e.terc+e.fgts+e.pis}
function avos13(y,adm,dem,through){adm=d(adm);dem=d(dem);var n=0;for(var i=0;i<Math.min(12,through);i++){var s=new Date(y,i,1,12),e=new Date(y,i+1,0,12),a=s,b=e;if(adm&&adm>a)a=adm;if(dem&&dem<b)b=dem;if(b>=a&&Math.floor((b-a)/86400000)+1>=15)n++}return n}
function avosFerias(adm,end){adm=d(adm);if(!adm||end<adm)return 0;var a=new Date(end.getFullYear(),adm.getMonth(),adm.getDate(),12);if(a>end)a.setFullYear(a.getFullYear()-1);if(a<adm)a=adm;var n=0,c=new Date(a);while(c<=end&&n<12){var nx=new Date(c.getFullYear(),c.getMonth()+1,c.getDate(),12),pe=new Date(nx-86400000);if(pe>end)pe=end;if(Math.floor((pe-c)/86400000)+1>=15)n++;c=nx}return Math.min(12,n)}
function years(adm,end){adm=d(adm);if(!adm)return 0;var y=end.getFullYear()-adm.getFullYear(),a=new Date(end.getFullYear(),adm.getMonth(),adm.getDate(),12);if(end<a)y--;return Math.max(0,y)}
function due(adm,end){adm=d(adm);if(!adm)return null;var x=new Date(end.getFullYear(),adm.getMonth(),adm.getDate()-1,12);if(x<end)x.setFullYear(x.getFullYear()+1);return x}
function lname(l){return String((l.rubrica_codigo||l.codigo||'')+' '+(l.rubrica_nome||l.nome||'')).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()}
function lsum(p,re,discount){var s=0;(p.lancamentos||[]).forEach(function(l){if(!re.test(lname(l)))return;var t=String(l.tipo||'').toLowerCase(),isD=t==='d'||/desconto/.test(t);if(discount===true&&!isD)return;if(discount===false&&isD)return;s+=Number(l.valor)||0});return s}
function rows13(){var a=anchor(),y=a.getFullYear(),mo=a.getMonth()+1,r=rates();return people().filter(clt).map(function(p){var sal=Number(p.salario)||0,av=avos13(y,p.admissao,p.demissao||p.desligamento,mo),prev=Math.max(0,av-1)*sal/12,pm=av?sal/12:0,at=av*sal/12,pago=lsum(p,/13.*sal|decimo.*terceiro/i,false),adi=lsum(p,/adiant.*13|13.*adiant/i,false),est=lsum(p,/estorn.*13|13.*estorn/i,false),saldo=Math.max(0,at-pago-adi-est),e=charges(saldo,r);return{id:key(p),nome:p.nome||'—',dep:dept(p),cc:cc(p),adm:p.admissao,sal:sal,av:av,prev:prev,pm:pm,aj:at-prev-pm,at:at,pago:pago,adi:adi,est:est,saldo:saldo,e:e,total:saldo+ct(e)}}).sort(function(a,b){return a.cc.localeCompare(b.cc)||a.nome.localeCompare(b.nome)})}
function rowsFerias(){var a=anchor(),r=rates();return people().filter(clt).map(function(p){var sal=Number(p.salario)||0,av=avosFerias(p.admissao,a),fer=sal/12*av,ter=fer/3,prev=Math.max(0,av-1)*sal/12*4/3,pm=sal/12*4/3,goz=lsum(p,/ferias.*goz|gozo.*ferias/i,false),ind=lsum(p,/ferias.*inden|inden.*ferias/i,false),est=lsum(p,/estorn.*ferias|ferias.*estorn/i,false),saldo=Math.max(0,fer+ter-goz-ind-est),e=charges(saldo,r);return{id:key(p),nome:p.nome||'—',dep:dept(p),cc:cc(p),adm:p.admissao,venc:due(p.admissao,a),vencidas:Math.max(0,years(p.admissao,a)-1),sal:sal,av:av,prev:prev,pm:pm,aj:fer+ter-prev-pm,fer:fer,ter:ter,goz:goz,ind:ind,est:est,saldo:saldo,e:e,total:saldo+ct(e)}}).sort(function(a,b){return a.cc.localeCompare(b.cc)||a.nome.localeCompare(b.nome)})}
function sum(a,k){return a.reduce(function(s,x){var v=x;k.split('.').forEach(function(q){v=v&&v[q]});return s+(Number(v)||0)},0)}
function cards(a){return '<div class="kpi-grid slim rh26-kpis">'+a.map(function(x){return '<div class="kpi '+(x[3]||'')+'"><span>'+h(x[0])+'</span><strong>'+h(x[1])+'</strong><small>'+h(x[2]||'')+'</small></div>'}).join('')+'</div>'}
function ccTable(rows,title){var g={};rows.forEach(function(x){if(!g[x.cc])g[x.cc]={cc:x.cc,n:0,s:0,e:0,t:0};g[x.cc].n++;g[x.cc].s+=x.saldo;g[x.cc].e+=ct(x.e);g[x.cc].t+=x.total});var a=Object.keys(g).map(function(k){return g[k]}).sort(function(x,y){return y.t-x.t});return '<article class="panel table-panel"><div class="panel-head"><div><span class="panel-kicker">RESUMO EXECUTIVO</span><h2>'+h(title)+' por centro de custo</h2></div></div><div class="table-wrap"><table><thead><tr><th>Centro de custo</th><th class="money">Pessoas</th><th class="money">Saldo</th><th class="money">Encargos</th><th class="money">Total</th></tr></thead><tbody>'+a.map(function(x){return '<tr><td><b>'+h(x.cc)+'</b></td><td class="money">'+x.n+'</td><td class="money">'+m(x.s)+'</td><td class="money">'+m(x.e)+'</td><td class="money"><b>'+m(x.t)+'</b></td></tr>'}).join('')+'</tbody><tfoot><tr><td><b>TOTAL</b></td><td class="money">'+rows.length+'</td><td class="money"><b>'+m(sum(rows,'saldo'))+'</b></td><td class="money"><b>'+m(a.reduce(function(s,x){return s+x.e},0))+'</b></td><td class="money"><b>'+m(sum(rows,'total'))+'</b></td></tr></tfoot></table></div></article>'}
function table13(rows){return '<article class="panel table-panel"><div class="panel-head"><div><span class="panel-kicker">COMPOSIÇÃO POR COLABORADOR</span><h2>Detalhamento da provisão de 13º</h2><p class="detail-note">Clique na linha para abrir a memória de cálculo.</p></div></div><div class="table-wrap"><table class="rh26-wide"><thead><tr><th>Colaborador</th><th>CC</th><th class="money">Salário</th><th class="money">Avos</th><th class="money">Saldo anterior</th><th class="money">Provisão mês</th><th class="money">Ajuste</th><th class="money">Pago</th><th class="money">Adiant.</th><th class="money">Saldo atual</th><th class="money">INSS Emp.</th><th class="money">RAT</th><th class="money">Terceiros</th><th class="money">FGTS</th><th class="money">PIS</th><th class="money">Total</th></tr></thead><tbody>'+rows.map(function(x){return '<tr class="rh26-row" data-k="13" data-id="'+h(x.id)+'"><td><b>'+h(x.nome)+'</b><small>'+h(x.dep)+'</small></td><td>'+h(x.cc)+'</td><td class="money">'+m(x.sal)+'</td><td class="money">'+x.av+'/12</td><td class="money">'+m(x.prev)+'</td><td class="money">'+m(x.pm)+'</td><td class="money">'+m(x.aj)+'</td><td class="money">'+m(x.pago)+'</td><td class="money">'+m(x.adi)+'</td><td class="money"><b>'+m(x.saldo)+'</b></td><td class="money">'+m(x.e.inss)+'</td><td class="money">'+m(x.e.rat)+'</td><td class="money">'+m(x.e.terc)+'</td><td class="money">'+m(x.e.fgts)+'</td><td class="money">'+m(x.e.pis)+'</td><td class="money"><b>'+m(x.total)+'</b></td></tr>'}).join('')+'</tbody><tfoot><tr><td><b>TOTAL</b></td><td></td><td></td><td></td><td class="money">'+m(sum(rows,'prev'))+'</td><td class="money">'+m(sum(rows,'pm'))+'</td><td class="money">'+m(sum(rows,'aj'))+'</td><td class="money">'+m(sum(rows,'pago'))+'</td><td class="money">'+m(sum(rows,'adi'))+'</td><td class="money"><b>'+m(sum(rows,'saldo'))+'</b></td><td class="money">'+m(sum(rows,'e.inss'))+'</td><td class="money">'+m(sum(rows,'e.rat'))+'</td><td class="money">'+m(sum(rows,'e.terc'))+'</td><td class="money">'+m(sum(rows,'e.fgts'))+'</td><td class="money">'+m(sum(rows,'e.pis'))+'</td><td class="money"><b>'+m(sum(rows,'total'))+'</b></td></tr></tfoot></table></div></article>'}
function tableFerias(rows){return '<article class="panel table-panel"><div class="panel-head"><div><span class="panel-kicker">COMPOSIÇÃO POR COLABORADOR</span><h2>Detalhamento da provisão de férias</h2><p class="detail-note">Férias vencidas são estimadas quando não houver histórico estruturado de gozo. Clique na linha para a memória.</p></div></div><div class="table-wrap"><table class="rh26-wide"><thead><tr><th>Colaborador</th><th>CC</th><th>Vencimento</th><th class="money">Vencidas*</th><th class="money">Avos</th><th class="money">Saldo anterior</th><th class="money">Provisão mês</th><th class="money">Ajuste</th><th class="money">Férias atual</th><th class="money">1/3 atual</th><th class="money">Gozadas</th><th class="money">Indenizadas</th><th class="money">Saldo atual</th><th class="money">INSS Emp.</th><th class="money">RAT</th><th class="money">Terceiros</th><th class="money">FGTS</th><th class="money">PIS</th><th class="money">Total</th></tr></thead><tbody>'+rows.map(function(x){return '<tr class="rh26-row" data-k="ferias" data-id="'+h(x.id)+'"><td><b>'+h(x.nome)+'</b><small>'+h(x.dep)+'</small></td><td>'+h(x.cc)+'</td><td>'+db(x.venc)+'</td><td class="money">'+x.vencidas+'</td><td class="money">'+x.av+'/12</td><td class="money">'+m(x.prev)+'</td><td class="money">'+m(x.pm)+'</td><td class="money">'+m(x.aj)+'</td><td class="money">'+m(x.fer)+'</td><td class="money">'+m(x.ter)+'</td><td class="money">'+m(x.goz)+'</td><td class="money">'+m(x.ind)+'</td><td class="money"><b>'+m(x.saldo)+'</b></td><td class="money">'+m(x.e.inss)+'</td><td class="money">'+m(x.e.rat)+'</td><td class="money">'+m(x.e.terc)+'</td><td class="money">'+m(x.e.fgts)+'</td><td class="money">'+m(x.e.pis)+'</td><td class="money"><b>'+m(x.total)+'</b></td></tr>'}).join('')+'</tbody><tfoot><tr><td><b>TOTAL</b></td><td></td><td></td><td></td><td></td><td class="money">'+m(sum(rows,'prev'))+'</td><td class="money">'+m(sum(rows,'pm'))+'</td><td class="money">'+m(sum(rows,'aj'))+'</td><td class="money">'+m(sum(rows,'fer'))+'</td><td class="money">'+m(sum(rows,'ter'))+'</td><td class="money">'+m(sum(rows,'goz'))+'</td><td class="money">'+m(sum(rows,'ind'))+'</td><td class="money"><b>'+m(sum(rows,'saldo'))+'</b></td><td class="money">'+m(sum(rows,'e.inss'))+'</td><td class="money">'+m(sum(rows,'e.rat'))+'</td><td class="money">'+m(sum(rows,'e.terc'))+'</td><td class="money">'+m(sum(rows,'e.fgts'))+'</td><td class="money">'+m(sum(rows,'e.pis'))+'</td><td class="money"><b>'+m(sum(rows,'total'))+'</b></td></tr></tfoot></table></div></article>'}
function memory(k,id){var x=(k==='13'?rows13():rowsFerias()).find(function(q){return q.id===id});if(!x)return;var a=k==='13'?[['Admissão',db(x.adm)],['Salário atual',m(x.sal)],['Avos',x.av+'/12'],['Saldo prov. anterior',m(x.prev)],['Provisão do mês',m(x.pm)],['Ajuste no mês',m(x.aj)],['Valor 13º atual',m(x.at)],['13º pago identificado',m(x.pago)],['Adiantamento identificado',m(x.adi)],['Estorno identificado',m(x.est)],['Saldo atual',m(x.saldo)]]:[['Admissão',db(x.adm)],['Vencimento estimado',db(x.venc)],['Férias vencidas (estim.)',x.vencidas],['Férias proporcionais',x.av+'/12'],['Saldo prov. anterior',m(x.prev)],['Provisão do mês',m(x.pm)],['Ajuste no mês',m(x.aj)],['Valor férias atual',m(x.fer)],['1/3 férias atual',m(x.ter)],['Gozadas identificadas',m(x.goz)],['Indenizadas identificadas',m(x.ind)],['Saldo atual',m(x.saldo)]];document.body.insertAdjacentHTML('beforeend','<div class="rh26-modal" id="rh26-modal"><div class="rh26-card"><button id="rh26-close">×</button><span class="eyebrow">MEMÓRIA DE CÁLCULO</span><h2>'+h(x.nome)+'</h2><p>'+h(x.cc)+' · '+h(x.dep)+'</p><div class="rh26-memory">'+a.map(function(q){return '<div><span>'+h(q[0])+'</span><b>'+h(q[1])+'</b></div>'}).join('')+'</div><h3>Encargos</h3><div class="rh26-memory"><div><span>INSS Empresa</span><b>'+m(x.e.inss)+'</b></div><div><span>RAT</span><b>'+m(x.e.rat)+'</b></div><div><span>Terceiros</span><b>'+m(x.e.terc)+'</b></div><div><span>FGTS</span><b>'+m(x.e.fgts)+'</b></div><div><span>PIS</span><b>'+m(x.e.pis)+'</b></div><div class="total"><span>Custo provisionado</span><b>'+m(x.total)+'</b></div></div><p class="detail-note">Estimativa gerencial. Faltas, afastamentos, médias e movimentos não estruturados devem ser conferidos com a folha oficial.</p></div></div>');E('rh26-close').onclick=function(){E('rh26-modal').remove()}}
function bind(p){p.querySelectorAll('.rh26-row').forEach(function(tr){tr.onclick=function(){memory(tr.dataset.k,tr.dataset.id)}})}
function render13(){var p=document.querySelector('[data-plan-pane="13"]');if(!p)return;var r=rows13(),a=anchor();p.innerHTML=cards([['Saldo provisionado',m(sum(r,'saldo')),r.length+' CLT'],['Provisão do mês',m(sum(r,'pm')),String(a.getMonth()+1).padStart(2,'0')+'/'+a.getFullYear()],['Encargos sobre saldo',m(r.reduce(function(s,x){return s+ct(x.e)},0)),'INSS Emp. + RAT + Terceiros + FGTS + PIS'],['Custo provisionado',m(sum(r,'total')),'saldo + encargos','featured']])+ccTable(r,'13º salário')+table13(r);bind(p)}
function renderFerias(){var p=document.querySelector('[data-plan-pane="ferias"]');if(!p)return;var r=rowsFerias();p.innerHTML=cards([['Saldo provisionado',m(sum(r,'saldo')),r.length+' CLT'],['Provisão do mês',m(sum(r,'pm')),'férias + 1/3'],['Encargos sobre saldo',m(r.reduce(function(s,x){return s+ct(x.e)},0)),'INSS Emp. + RAT + Terceiros + FGTS + PIS'],['Custo provisionado',m(sum(r,'total')),'saldo + encargos','featured']])+ccTable(r,'Férias')+tableFerias(r);bind(p)}
function pbr(v){return Number(String(v||'').replace(/R\$|\s/g,'').replace(/\./g,'').replace(',','.'))||0}
function calcTerm(){var p=people().filter(clt).find(function(x){return key(x)===String(E('rh26-person').value)});if(!p)return null;var x=d(E('rh26-date').value)||new Date(),t=E('rh26-type').value,n=E('rh26-notice').value,s=Number(p.salario)||0,ds=Math.min(30,x.getDate()),saldo=s/30*ds,a13=avos13(x.getFullYear(),p.admissao,x,x.getMonth()+1),v13=s/12*a13,avf=avosFerias(p.admissao,x),vf=s/12*avf,ven=Math.max(0,Number(E('rh26-over').value)||0)*s,ter=(vf+ven)/3,yd=years(p.admissao,x),nd=Math.min(90,30+yd*3),aviso=t==='empregador'&&n==='indenizado'?s/30*nd:0,av13=aviso?s/12:0,avfut=aviso?s/12:0,cct=pbr(E('rh26-cct').value),cred=pbr(E('rh26-cred').value),od=pbr(E('rh26-disc').value),fg=pbr(E('rh26-fgts').value),inssRate=Number(p.valor_inss||0)&&Number(p.base_inss||0)?Math.min(.14,Number(p.valor_inss)/Number(p.base_inss)):0,irrfRate=Number(p.valor_irrf||0)&&Number(p.base_irrf||0)?Math.min(.275,Number(p.valor_irrf)/Number(p.base_irrf)):0,inss=saldo*inssRate,inss13=v13*inssRate,irrf=Math.max(0,(saldo-inss)*irrfRate),irrf13=Math.max(0,(v13-inss13)*irrfRate),avDisc=t==='pedido'&&n==='desconto'?s:0,bruto=saldo+v13+vf+ven+ter+aviso+av13+avfut+cct+cred,ded=inss+inss13+irrf+irrf13+avDisc+od,multa=t==='empregador'?fg*.4:0;return{p:p,date:x,type:t,s:s,ds:ds,saldo:saldo,a13:a13,v13:v13,avf:avf,vf:vf,ven:ven,ter:ter,nd:nd,aviso:aviso,av13:av13,avfut:avfut,cct:cct,cred:cred,inss:inss,inss13:inss13,irrf:irrf,irrf13:irrf13,avDisc:avDisc,od:od,bruto:bruto,ded:ded,liq:bruto-ded,fg:fg,fgm:saldo*.08,fg13:(v13+av13)*.08,fgav:aviso*.08,multa:multa,custo:bruto+saldo*.08+(v13+av13)*.08+aviso*.08+multa}}
function lines(a){return '<div class="rh-res-lines">'+a.filter(function(x){return Math.abs(x[1])>.004}).map(function(x){return '<div><span>'+h(x[0])+'</span><b>'+m(x[1])+'</b></div>'}).join('')+'</div>'}
function renderTerm(){var x=calcTerm();if(!x)return;V.term=x;E('rh26-result').innerHTML='<div class="panel-head"><div><span class="panel-kicker">RELATÓRIO ANALÍTICO</span><h2>'+h(x.p.nome)+'</h2><p>'+(x.type==='empregador'?'Despedida sem justa causa pelo empregador':'Pedido de demissão sem justa causa')+' · '+db(x.date)+'</p></div></div>'+cards([['Total bruto',m(x.bruto),'verbas rescisórias'],['Deduções estimadas',m(x.ded),'INSS/IRRF + outros'],['Líquido estimado',m(x.liq),'a pagar','featured'],['Custo empregador',m(x.custo),'bruto + FGTS/multa']])+'<div class="rh26-term"><div><h3>Verbas rescisórias</h3>'+lines([['Saldo de salário',x.saldo],['13º proporcional '+x.a13+'/12',x.v13],['Férias proporcionais '+x.avf+'/12',x.vf],['Férias vencidas',x.ven],['1/3 constitucional',x.ter],['Aviso-prévio indenizado '+x.nd+' dias',x.aviso],['13º sobre aviso',x.av13],['Férias sobre aviso',x.avfut],['Indenização CCT',x.cct],['Outros créditos',x.cred]])+'</div><div><h3>Deduções</h3>'+lines([['INSS sobre rescisão (estim.)',x.inss],['INSS 13º (estim.)',x.inss13],['IRRF mensal (estim.)',x.irrf],['IRRF 13º (estim.)',x.irrf13],['Aviso descontado',x.avDisc],['Outros descontos',x.od]])+'</div></div><article class="panel rh26-base"><h3>Base de cálculo e FGTS</h3><div class="rh26-memory"><div><span>Saldo FGTS informado</span><b>'+m(x.fg)+'</b></div><div><span>FGTS mensal</span><b>'+m(x.fgm)+'</b></div><div><span>FGTS 13º</span><b>'+m(x.fg13)+'</b></div><div><span>FGTS aviso</span><b>'+m(x.fgav)+'</b></div><div><span>Multa FGTS</span><b>'+m(x.multa)+'</b></div><div><span>Base INSS mensal</span><b>'+m(x.saldo)+'</b></div><div><span>Base INSS 13º</span><b>'+m(x.v13)+'</b></div></div></article><div class="rh-plan-warning"><b>Estimativa gerencial</b><span>Estrutura baseada nos modelos anexados. Validar incidências, médias, CCT, estabilidade e cálculo oficial antes do pagamento.</span></div>'}
function buildTerm(){var p=document.querySelector('[data-plan-pane="rescisao"]');if(!p)return;var ps=people().filter(clt).sort(function(a,b){return String(a.nome).localeCompare(String(b.nome))}),a=anchor();p.innerHTML='<div class="grid two rh-plan-res-grid"><article class="panel"><div class="panel-head"><div><span class="panel-kicker">SIMULADOR BASEADO NOS MODELOS</span><h2>Rescisão individual</h2></div></div><div class="rh-plan-form"><label>Colaborador<select id="rh26-person">'+ps.map(function(x){return '<option value="'+h(key(x))+'">'+h(x.nome)+'</option>'}).join('')+'</select></label><label>Data de desligamento<input id="rh26-date" type="date" value="'+a.toISOString().slice(0,10)+'"></label><label>Modalidade<select id="rh26-type"><option value="pedido">Pedido do empregado — sem justa causa</option><option value="empregador">Sem justa causa — empregador</option></select></label><label>Aviso prévio<select id="rh26-notice"><option value="indenizado">Indenizado</option><option value="trabalhado">Trabalhado</option><option value="desconto">Desconto do empregado</option><option value="na">Não aplicável</option></select></label><label>Períodos de férias vencidas<input id="rh26-over" type="number" min="0" value="0"></label><label>Saldo FGTS conhecido<input id="rh26-fgts" inputmode="decimal" placeholder="0,00"></label><label>Indenização CCT / outra verba<input id="rh26-cct" inputmode="decimal" placeholder="0,00"></label><label>Outros créditos<input id="rh26-cred" inputmode="decimal" placeholder="0,00"></label><label>Outros descontos<input id="rh26-disc" inputmode="decimal" placeholder="0,00"></label><button class="button primary" id="rh26-calc">Gerar relatório analítico</button></div></article><article class="panel" id="rh26-result"><div class="empty-state"><h2>Selecione um cenário</h2><p>O relatório mostrará verbas, deduções, líquido e bases de FGTS/INSS/IRRF.</p></div></article></div>';E('rh26-calc').onclick=renderTerm}
function enhance(){var p=E('page-planejamento');if(!p)return false;if(p.dataset.v26==='1')return true;p.dataset.v26='1';render13();renderFerias();buildTerm();p.querySelectorAll('[data-plan-tab]').forEach(function(b){var old=b.onclick;b.onclick=function(e){if(old)old.call(this,e);setTimeout(function(){if(b.dataset.planTab==='13')render13();if(b.dataset.planTab==='ferias')renderFerias();if(b.dataset.planTab==='rescisao')buildTerm()},0)}});return true}
function style(){if(E('_rh26'))return;var s=document.createElement('style');s.id='_rh26';s.textContent='.rh26-wide{min-width:1800px!important}.rh26-wide td small{display:block;color:var(--muted);margin-top:3px}.rh26-row{cursor:pointer}.rh26-kpis{margin-bottom:14px}.rh26-modal{position:fixed;inset:0;z-index:9999;background:rgba(0,0,0,.68);display:grid;place-items:center;padding:24px}.rh26-card{width:min(820px,96vw);max-height:90vh;overflow:auto;background:var(--surface);border:1px solid var(--line-soft);border-radius:18px;padding:24px;position:relative}.rh26-card>button{position:absolute;right:16px;top:16px;width:42px;height:42px;border:1px solid var(--line-soft);border-radius:12px;background:var(--surface-2);color:var(--text);font-size:24px}.rh26-memory{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;margin:14px 0}.rh26-memory>div{display:flex;justify-content:space-between;gap:10px;padding:10px;border:1px solid var(--line-soft);border-radius:10px;background:var(--surface-2)}.rh26-memory span{color:var(--muted)}.rh26-memory .total{grid-column:1/-1;border-color:var(--gold)}.rh26-term{display:grid;grid-template-columns:1fr 1fr;gap:18px;margin-top:16px}.rh26-term>div{padding:14px;border:1px solid var(--line-soft);border-radius:12px;background:var(--surface-2)}.rh26-base{margin-top:16px}@media(max-width:900px){.rh26-memory,.rh26-term{grid-template-columns:1fr}}';document.head.appendChild(s)}
var su=setupUI;setupUI=function(){var r=su.apply(this,arguments);style();setTimeout(enhance,0);return r};
var ra=renderAll;renderAll=function(){var r=ra.apply(this,arguments);if(E('page-planejamento')){if(E('page-planejamento').dataset.v26==='1'){render13();renderFerias()}else enhance()}return r};
window.rhV26EnhancePlanning=enhance;window.rhV26RenderTermination=renderTerm;
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){style();setTimeout(enhance,350)});else{style();setTimeout(enhance,350)}
})();
