/* RH & Folha — Release Candidate: indicadores executivos, variações e histórico individual */
S.rhHistoryFolhas=S.rhHistoryFolhas||[];
S.rhHistoryFolhasLoaded=false;
S.rhPersonBenefitsHistory={};

function rhInsightCost(p){var c=custoEmpresa(p),benef=0,charges=0;c.itens.forEach(function(it){if(it[2]==='benefício')benef+=Number(it[1])||0;else if(cleanSearch(it[0])!=='proventos brutos')charges+=Number(it[1])||0;});return {total:c.total,beneficios:benef,encargos:charges,proventos:Number(p.proventos)||0};}
function rhInsightRows(){return typeof rhScopePeople==='function'?rhScopePeople():S.pessoas;}
function rhInsightAggregate(rows){var t={pessoas:rows.length,proventos:0,encargos:0,beneficios:0,total:0,clt:{n:0,total:0},estagiario:{n:0,total:0},outros:{n:0,total:0}};rows.forEach(function(p){var c=rhInsightCost(p),k=rhVinculoCategory(p);t.proventos+=c.proventos;t.encargos+=c.encargos;t.beneficios+=c.beneficios;t.total+=c.total;t[k].n++;t[k].total+=c.total;});return t;}
function rhPct(n,d){return d?((Number(n)||0)/(Number(d)||0)*100):0;}
function rhAvg(total,n){return n?(Number(total)||0)/n:0;}
function rhVarLabel(key){return {proventos:'Proventos',descontos:'Descontos',liquido:'Líquido',fgts:'FGTS',patronais:'Encargos patronais',pis:'PIS',irrf:'IRRF',pessoas:'Headcount',custoFolha:'Custo folha + encargos'}[key]||key;}
function rhVarianceSummary(){var rows=typeof rhHistoryAllRows==='function'?rhHistoryAllRows():[];if(rows.length<2)return[];var cur=rows[rows.length-1],prev=rows[rows.length-2],keys=['proventos','descontos','liquido','fgts','patronais','pis','irrf','pessoas','custoFolha'];return keys.map(function(k){var a=Number(cur[k])||0,b=Number(prev[k])||0,d=a-b,p=b?d/Math.abs(b)*100:null;return {key:k,label:rhVarLabel(k),atual:a,anterior:b,diff:d,pct:p};}).sort(function(a,b){var aa=a.pct==null?Math.abs(a.diff):Math.abs(a.pct),bb=b.pct==null?Math.abs(b.diff):Math.abs(b.pct);return bb-aa;});}

async function rhLoadHistoryFolhas(){
  if(S.rhHistoryFolhasLoaded)return S.rhHistoryFolhas;
  if(!(can('ver_valores_individuais')||canAdmin()))return[];
  try{S.rhHistoryFolhas=await api('rh_folha_colaboradores?select=*');S.rhHistoryFolhasLoaded=true;}catch(e){S.rhHistoryFolhas=[];}
  return S.rhHistoryFolhas;
}
function rhFolhasByComp(){var m={};(S.rhHistoryFolhas||[]).forEach(function(f){(m[String(f.competencia_id)]||(m[String(f.competencia_id)]=[])).push(f);});return m;}
function rhDepartmentVariance(){var hist=typeof rhHistoryAllRows==='function'?rhHistoryAllRows():[],by=rhFolhasByComp();if(hist.length<2||!S.rhHistoryFolhasLoaded)return null;var cur=hist[hist.length-1],prev=hist[hist.length-2];function agg(id){var m={};(by[String(id)]||[]).forEach(function(f){var dep=departmentName(rhFolhaSnap(f,'departamento','—'));m[dep]=(m[dep]||0)+(Number(f.proventos)||0);});return m;}var a=agg(cur.id),b=agg(prev.id),names={};Object.keys(a).concat(Object.keys(b)).forEach(function(n){names[n]=1;});var list=Object.keys(names).map(function(n){var av=a[n]||0,bv=b[n]||0;return {nome:n,diff:av-bv,atual:av,anterior:bv};}).sort(function(x,y){return Math.abs(y.diff)-Math.abs(x.diff);});return list[0]||null;}

function rhEnsureInsightsUI(){
  var nav=$('nav');if(nav&&!document.querySelector('[data-view="indicadores"]')){var b=document.createElement('button');b.className='nav-item';b.dataset.view='indicadores';b.innerHTML='<span>◆</span>Indicadores';var anchor=document.querySelector('[data-view="historico"]');if(anchor&&anchor.nextSibling)nav.insertBefore(b,anchor.nextSibling);else nav.appendChild(b);b.onclick=function(){go('indicadores');renderInsights();};}
  if(!$('page-indicadores')){var page=document.createElement('section');page.className='page';page.id='page-indicadores';page.innerHTML='<div class="page-head"><div><span class="eyebrow">GESTÃO DE PESSOAS</span><h1>Indicadores executivos</h1><p>Custo médio, encargos, benefícios, vínculos e variações relevantes.</p></div></div><div class="kpi-grid" id="rh-insight-kpis"></div><div class="grid two"><article class="panel"><div class="panel-head"><div><span class="panel-kicker">DEPARTAMENTOS</span><h2>Custo Real por departamento</h2></div></div><div class="chart-wrap tall"><canvas id="chart-insight-dept"></canvas></div></article><article class="panel"><div class="panel-head"><div><span class="panel-kicker">VÍNCULOS</span><h2>Custo médio por vínculo</h2></div></div><div class="chart-wrap tall"><canvas id="chart-insight-vinc"></canvas></div></article></div><article class="panel"><div class="panel-head"><div><span class="panel-kicker">VARIAÇÕES</span><h2>Principais mudanças contra a competência anterior</h2></div><span class="source-badge" id="rh-variance-period">—</span></div><div id="rh-variance-list" class="reconciliation-list"></div></article></section>';var content=document.querySelector('#app .content')||document.querySelector('#app main')||$('app');content.appendChild(page);if(typeof rhCreateScreenFilters==='function'){rhCreateScreenFilters('page-indicadores');rhPopulateScopeControls();rhEnsureScopeFilters();}}
  if(!$('_rh_insights_style')){var st=document.createElement('style');st.id='_rh_insights_style';st.textContent='#rh-insight-kpis{grid-template-columns:repeat(6,minmax(0,1fr))}.rh-variance-value{font-weight:900;white-space:nowrap}.rh-variance-up{color:var(--gold)}.rh-variance-down{color:var(--blue)}@media(max-width:1250px){#rh-insight-kpis{grid-template-columns:repeat(3,minmax(0,1fr))}}@media(max-width:680px){#rh-insight-kpis{grid-template-columns:repeat(2,minmax(0,1fr))}}';document.head.appendChild(st);}
}
function renderInsights(){
  rhEnsureInsightsUI();if(!S.competencia)return;var rows=rhInsightRows(),t=rhInsightAggregate(rows),k=$('rh-insight-kpis');if(!k)return;
  var chargesPct=rhPct(t.encargos,t.proventos),benefPct=rhPct(t.beneficios,t.total);
  k.innerHTML=[['Custo médio / pessoa',fmt(rhAvg(t.total,t.pessoas)),t.pessoas+' pessoas'],['Encargos / proventos',chargesPct.toFixed(1).replace('.',',')+'%','FGTS + patronais + PIS'],['Benefícios / custo',benefPct.toFixed(1).replace('.',',')+'%',S.rhBenefitSnapshotActive?'snapshot mensal':'base integrada atual'],['Média CLT',fmt(rhAvg(t.clt.total,t.clt.n)),t.clt.n+' pessoas'],['Média Estagiário',fmt(rhAvg(t.estagiario.total,t.estagiario.n)),t.estagiario.n+' pessoas'],['Custo total filtrado',fmt(t.total),'competência '+formatCompetence(S.competencia.competencia)]].map(function(x){return '<div class="kpi"><span>'+esc(x[0])+'</span><strong>'+esc(x[1])+'</strong><small>'+esc(x[2])+'</small></div>';}).join('');
  var dm={},vm={clt:{label:'CLT',n:0,total:0},estagiario:{label:'Estagiários',n:0,total:0},outros:{label:'Outros',n:0,total:0}};rows.forEach(function(p){var dep=departmentName(p.departamento),c=rhInsightCost(p),v=rhVinculoCategory(p);if(!dm[dep])dm[dep]={nome:dep,total:0};dm[dep].total+=c.total;vm[v].n++;vm[v].total+=c.total;});var deps=Object.keys(dm).map(function(x){return dm[x];}).sort(function(a,b){return b.total-a.total;});
  if(window.Chart){var c=chartColors();chart('chart-insight-dept','bar',{labels:deps.map(function(x){return x.nome;}),datasets:[{label:'Custo Real',data:deps.map(function(x){return x.total;}),backgroundColor:c.emerald,borderRadius:7}]},{indexAxis:'y',plugins:{legend:{display:false}}},function(e,els){if(els.length&&deps[els[0].index])openDepartmentBreakdown(deps[els[0].index].nome);});var vv=[vm.clt,vm.estagiario,vm.outros];chart('chart-insight-vinc','bar',{labels:vv.map(function(x){return x.label;}),datasets:[{label:'Custo médio',data:vv.map(function(x){return rhAvg(x.total,x.n);}),backgroundColor:[c.blue,c.gold,c.purple],borderRadius:7}]},{plugins:{legend:{display:false}}},function(e,els){if(els.length)openVinculoBreakdown(['CLT','Estagiários','Outros'][els[0].index]);});}
  var vars=rhVarianceSummary(),list=$('rh-variance-list'),period=$('rh-variance-period'),hist=typeof rhHistoryAllRows==='function'?rhHistoryAllRows():[];
  if(hist.length<2){period.textContent='A partir da 2ª competência';list.innerHTML='<div class="reconciliation-item"><span class="check">i</span><span><b>Junho é a competência-base</b><small>As variações aparecem automaticamente após a próxima importação.</small></span><span class="status">Base inicial</span></div>';}
  else{period.textContent=formatCompetence(hist[hist.length-2].competencia)+' → '+formatCompetence(hist[hist.length-1].competencia);var dv=rhDepartmentVariance(),show=vars.slice(0,5);if(dv)show.push({label:'Departamento com maior variação',diff:dv.diff,pct:dv.anterior?dv.diff/Math.abs(dv.anterior)*100:null,detail:dv.nome});list.innerHTML=show.map(function(v){var up=v.diff>0,down=v.diff<0,cls=up?'rh-variance-up':(down?'rh-variance-down':''),pct=v.pct==null?'':(' · '+Math.abs(v.pct).toFixed(1).replace('.',',')+'%');return '<div class="reconciliation-item"><span class="check">'+(up?'↑':(down?'↓':'→'))+'</span><span><b>'+esc(v.label)+'</b><small>'+esc(v.detail||'Comparação contra a competência anterior')+'</small></span><span class="rh-variance-value '+cls+'">'+(v.key==='pessoas'?nfmt(Math.abs(v.diff)):fmt(Math.abs(v.diff)))+pct+'</span></div>';}).join('');}
}

function rhEnsurePersonHistoryUI(){
  if(typeof rhEnsureHistoryUI==='function')rhEnsureHistoryUI();var page=$('page-historico');if(!page||$('rh-person-history-panel'))return;var panel=document.createElement('article');panel.id='rh-person-history-panel';panel.className='panel';panel.innerHTML='<div class="panel-head"><div><span class="panel-kicker">HISTÓRICO INDIVIDUAL</span><h2>Evolução por colaborador</h2></div><label class="rh-scope-label">Colaborador<select id="rh-person-history-select"><option value="">Selecione</option></select></label></div><div id="rh-person-history-empty" class="detail-empty">Selecione um colaborador para acompanhar salário, líquido, encargos, benefícios, custo e movimentações mês a mês.</div><div id="rh-person-history-content" hidden><div class="kpi-grid slim" id="rh-person-history-kpis"></div><div class="chart-wrap tall"><canvas id="chart-person-history"></canvas></div><div id="rh-person-history-months" class="rh-history-months"></div></div>';var note=$('rh-history-benefit-note');if(note&&note.parentNode)note.parentNode.insertBefore(panel,note);else page.appendChild(panel);var s=$('rh-person-history-select');s.onchange=function(){renderPersonHistory(s.value);};
}
function rhPopulatePersonHistory(){rhEnsurePersonHistoryUI();var s=$('rh-person-history-select');if(!s)return;var cur=s.value,people=(S.colaboradores||[]).slice().sort(function(a,b){return String(a.nome||'').localeCompare(String(b.nome||''),'pt-BR',{sensitivity:'base'});});s.innerHTML='<option value="">Selecione</option>'+people.map(function(p){return '<option value="'+esc(p.id)+'">'+esc(p.nome)+'</option>';}).join('');if(cur&&people.some(function(p){return String(p.id)===String(cur);}))s.value=cur;}
async function rhPersonBenefitHistory(id){if(S.rhPersonBenefitsHistory[id])return S.rhPersonBenefitsHistory[id];try{var rows=await api('rh_beneficios_snapshots?colaborador_id=eq.'+encodeURIComponent(id)+'&select=*');S.rhPersonBenefitsHistory[id]=rows||[];}catch(e){S.rhPersonBenefitsHistory[id]=[];}return S.rhPersonBenefitsHistory[id];}
async function renderPersonHistory(id){
  var empty=$('rh-person-history-empty'),content=$('rh-person-history-content');if(!id){empty.hidden=false;content.hidden=true;return;}empty.hidden=true;content.hidden=false;await rhLoadHistoryFolhas();var ben=await rhPersonBenefitHistory(id),bmap={};ben.forEach(function(x){bmap[String(x.competencia_id)]=x;});var compMap={};(S.competencias||[]).forEach(function(c){compMap[String(c.id)]=c;});var byComp=rhFolhasByComp(),rows=(S.rhHistoryFolhas||[]).filter(function(f){return String(f.colaborador_id)===String(id);}).map(function(f){var c=compMap[String(f.competencia_id)]||{},all=byComp[String(f.competencia_id)]||[],baseAll=all.reduce(function(a,x){return a+(Number(x.base_inss)||0);},0),fgAll=all.reduce(function(a,x){return a+(Number(x.base_fgts)||0);},0),e=c.encargos||{},baseTotal=Number(e.base_total_inss)||0,patTotal=baseTotal*.20+(Number(e.rat)||(baseTotal*.01))+(Number(e.terceiros)||(baseTotal*.058)),pat=baseAll?patTotal*(Number(f.base_inss)||0)/baseAll:0,pisTotal=Number(e.valor_pis)||0,pis=fgAll?pisTotal*(Number(f.base_fgts)||0)/fgAll:0,b=bmap[String(f.competencia_id)],benef=b?Number(b.total)||0:0,total=(Number(f.proventos)||0)+(Number(f.valor_fgts)||0)+pat+pis+benef;return {f:f,c:c,benef:b?benef:null,total:total,encargos:(Number(f.valor_fgts)||0)+pat+pis};}).sort(function(a,b){return String(a.c.competencia||'').localeCompare(String(b.c.competencia||''));});
  if(!rows.length){empty.hidden=false;empty.textContent='Sem histórico individual disponível para este colaborador.';content.hidden=true;return;}var last=rows[rows.length-1];$('rh-person-history-kpis').innerHTML=[['Competências',rows.length],['Último provento',fmt(last.f.proventos)],['Último líquido',fmt(last.f.liquido)],['Último custo',fmt(last.total)]].map(function(x){return '<div class="kpi"><span>'+esc(x[0])+'</span><strong>'+esc(x[1])+'</strong></div>';}).join('');
  if(window.Chart){var cc=chartColors();chart('chart-person-history','line',{labels:rows.map(function(x){return formatCompetence(x.c.competencia);}),datasets:[{label:'Proventos',data:rows.map(function(x){return Number(x.f.proventos)||0;}),borderColor:cc.gold,backgroundColor:cc.gold,tension:.25},{label:'Líquido',data:rows.map(function(x){return Number(x.f.liquido)||0;}),borderColor:cc.emerald,backgroundColor:cc.emerald,tension:.25},{label:'Custo',data:rows.map(function(x){return x.total;}),borderColor:cc.red,backgroundColor:cc.red,tension:.25}]},{plugins:{legend:{display:true,position:'top'}}},function(e,els){if(els.length){var r=rows[els[0].index];if(r){selectCompetence(r.c.id).then(function(){go('custoreal');});}}});}
  $('rh-person-history-months').innerHTML=rows.slice().reverse().map(function(x){return '<div class="rh-history-month"><div class="rh-history-month-head"><div><span>Competência</span><strong>'+esc(formatCompetence(x.c.competencia))+'</strong></div><span class="status">'+esc(rhAuditStatusLabel(x.c.status))+'</span></div><div class="rh-history-month-metrics">'+[['Departamento',departmentName(rhFolhaSnap(x.f,'departamento','—'))],['Vínculo',rhFolhaSnap(x.f,'vinculo','—')],['Proventos',fmt(x.f.proventos)],['Líquido',fmt(x.f.liquido)],['Encargos',fmt(x.encargos)],['Benefícios',x.benef==null?'Não versionado':fmt(x.benef)],['Custo total',fmt(x.total)]].map(function(m){return '<div class="rh-history-metric"><span>'+esc(m[0])+'</span><strong>'+esc(m[1])+'</strong></div>';}).join('')+'</div></div>';}).join('');
}

var _rhInsightEnsureHistory=rhEnsureHistoryUI;
rhEnsureHistoryUI=function(){_rhInsightEnsureHistory();rhEnsurePersonHistoryUI();rhPopulatePersonHistory();};
var _rhInsightRenderHistory=renderHistory;
renderHistory=function(){_rhInsightRenderHistory();rhPopulatePersonHistory();rhLoadHistoryFolhas().then(function(){if(S.view==='indicadores')renderInsights();});};
var _rhInsightRefreshScope=rhRefreshScope;
rhRefreshScope=function(){_rhInsightRefreshScope();if(S.view==='indicadores')renderInsights();};
var _rhInsightRenderAll=renderAll;
renderAll=function(){_rhInsightRenderAll();rhEnsureInsightsUI();if(S.view==='indicadores')renderInsights();rhPopulatePersonHistory();};
var _rhInsightSetup=setupUI;
setupUI=function(){_rhInsightSetup();rhEnsureInsightsUI();rhEnsurePersonHistoryUI();rhLoadHistoryFolhas();};
