/* RH v31 — rescisão calibrada com histórico importado e deduções reais quando disponíveis */
(function(){
'use strict';
function E(id){return document.getElementById(id)}
function n(v){var x=Number(v);return isFinite(x)?x:0}
function r2(v){return Math.round((n(v)+Number.EPSILON)*100)/100}
function floor2(v){return Math.floor((n(v)+1e-9)*100)/100}
function esc2(v){try{return esc(String(v==null?'':v))}catch(e){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}}
function money(v){try{return fmt(n(v))}catch(e){return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(n(v))}}
function date(v){if(!v)return null;var x=new Date(String(v).slice(0,10)+'T12:00:00');return isNaN(x)?null:x}
function brdate(v){var x=v instanceof Date?v:date(v);return x?String(x.getDate()).padStart(2,'0')+'/'+String(x.getMonth()+1).padStart(2,'0')+'/'+x.getFullYear():'—'}
function parseBR(v){return Number(String(v||'').replace(/R\$|\s/g,'').replace(/\./g,'').replace(',','.'))||0}
function pid(p){return String(p&&p.colaborador_id||p&&p.id||'')}
function person(id){var p=(S.pessoas||[]).find(function(x){return pid(x)===String(id)});if(p)return p;var c=(S.colaboradores||[]).find(function(x){return String(x.id)===String(id)});return c||null}
function avos13(y,adm,dem,through){adm=date(adm);dem=date(dem);var q=0;for(var i=0;i<Math.min(12,through);i++){var s=new Date(y,i,1,12),e=new Date(y,i+1,0,12),a=s,b=e;if(adm&&adm>a)a=adm;if(dem&&dem<b)b=dem;if(b>=a&&Math.floor((b-a)/86400000)+1>=15)q++}return q}
function avosFerias(adm,end){adm=date(adm);if(!adm||end<adm)return 0;var a=new Date(end.getFullYear(),adm.getMonth(),adm.getDate(),12);if(a>end)a.setFullYear(a.getFullYear()-1);if(a<adm)a=adm;var q=0,c=new Date(a);while(c<=end&&q<12){var nx=new Date(c.getFullYear(),c.getMonth()+1,c.getDate(),12),pe=new Date(nx-86400000);if(pe>end)pe=end;if(Math.floor((pe-c)/86400000)+1>=15)q++;c=nx}return Math.min(12,q)}
function years(adm,end){adm=date(adm);if(!adm)return 0;var y=end.getFullYear()-adm.getFullYear(),a=new Date(end.getFullYear(),adm.getMonth(),adm.getDate(),12);if(end<a)y--;return Math.max(0,y)}
function inssBands(dt){var y=dt.getFullYear();if(y>=2026)return [[1621,.075],[2902.84,.09],[4354.27,.12],[8475.55,.14]];if(y===2025)return [[1518,.075],[2793.88,.09],[4190.83,.12],[8157.41,.14]];if(y===2024)return [[1412,.075],[2666.68,.09],[4000.03,.12],[7786.02,.14]];if(y===2023)return [[1320,.075],[2571.29,.09],[3856.94,.12],[7507.49,.14]];return [[1412,.075],[2666.68,.09],[4000.03,.12],[7786.02,.14]]}
function inss(base,dt){base=Math.max(0,n(base));var b=inssBands(dt),prev=0,total=0;for(var i=0;i<b.length&&base>prev;i++){var top=b[i][0],rate=b[i][1],slice=Math.min(base,top)-prev;if(slice>0)total+=slice*rate;prev=top}return floor2(total)}
function irrfCfg(dt){var y=dt.getFullYear(),m=dt.getMonth()+1;if(y>=2026||y===2025&&m>=5)return [[2428.80,0,0],[2826.65,.075,182.16],[3751.05,.15,394.16],[4664.68,.225,675.49],[Infinity,.275,908.73]];if(y===2025||y===2024)return [[2259.20,0,0],[2826.65,.075,169.44],[3751.05,.15,381.44],[4664.68,.225,662.77],[Infinity,.275,896.00]];if(y===2023&&m>=5)return [[2112,0,0],[2826.65,.075,158.40],[3751.05,.15,370.40],[4664.68,.225,651.73],[Infinity,.275,884.96]];return [[1903.98,0,0],[2826.65,.075,142.80],[3751.05,.15,354.80],[4664.68,.225,636.13],[Infinity,.275,869.36]]}
function irrf(gross,inssVal,dt){var base=Math.max(0,n(gross)-n(inssVal)),cfg=irrfCfg(dt),tax=0;for(var i=0;i<cfg.length;i++){if(base<=cfg[i][0]){tax=Math.max(0,base*cfg[i][1]-cfg[i][2]);break}}if(dt.getFullYear()>=2026){var rend=n(gross),red=0;if(rend<=5000)red=tax;else if(rend<=7350)red=Math.max(0,978.62-(.133145*rend));tax=Math.max(0,tax-red)}return floor2(tax)}
function isNetMarker(l){var c=String(l&&l.rubrica_codigo||l&&l.codigo||'').trim(),nm=String(l&&l.rubrica_nome||l&&l.nome||'').toUpperCase();return c==='51'||c==='8517'||nm.indexOf('LIQUIDO RESCISAO')>=0}
function termSpecific(l){var c=String(l&&l.rubrica_codigo||l&&l.codigo||'').trim(),nm=String(l&&l.rubrica_nome||l&&l.nome||'').toUpperCase();return ['9180','8550','29','8169','9591','9592','826','989','828','51','379'].indexOf(c)>=0||/RESCISAO|AVISO PREVIO|FERIAS PROPORCIONAIS/.test(nm)}
async function history(personId,dt){
  try{
    var comp=String(dt.getFullYear())+'-'+String(dt.getMonth()+1).padStart(2,'0')+'-01';
    var cs=await api('rh_competencias?competencia=eq.'+comp+'&select=id,competencia');if(!cs||!cs.length)return null;
    var fs=await api('rh_folha_colaboradores?competencia_id=eq.'+cs[0].id+'&colaborador_id=eq.'+encodeURIComponent(personId)+'&select=*');if(!fs||!fs.length)return null;
    var f=fs[0],ls=await api('rh_lancamentos?folha_colaborador_id=eq.'+f.id+'&select=*&order=valor.desc');ls=ls||[];if(!ls.some(termSpecific))return null;
    var out={folha:f,lancamentos:ls,gross:0,discounts:0,net:0,inss:0,inss13:0,irrf:0,irrf13:0,other:0,fgts:n(f.valor_fgts)};
    var marker=0;
    ls.forEach(function(l){var type=String(l.tipo||'').toLowerCase(),v=n(l.valor),c=String(l.rubrica_codigo||'').trim(),nm=String(l.rubrica_nome||'').toUpperCase();if(type==='provento')out.gross+=v;if(type==='desconto'){if(isNetMarker(l)){marker+=v;return}out.discounts+=v;if(c==='826'||/INSS SOBRE RESCISAO/.test(nm))out.inss+=v;else if(c==='989'||/INSS 13/.test(nm))out.inss13+=v;else if(c==='828'||/IRRF SOBRE RESCISAO/.test(nm))out.irrf+=v;else if(/IRRF.*13/.test(nm))out.irrf13+=v;else out.other+=v;}});
    out.gross=r2(out.gross);out.discounts=r2(out.discounts);out.net=r2(marker||out.gross-out.discounts);out.inss=r2(out.inss);out.inss13=r2(out.inss13);out.irrf=r2(out.irrf);out.irrf13=r2(out.irrf13);out.other=r2(out.other);return out;
  }catch(e){return null}
}
function lines(a){return '<div class="rh-res-lines">'+a.filter(function(x){return Math.abs(n(x[1]))>.004}).map(function(x){return '<div><span>'+esc2(x[0])+'</span><b>'+money(x[1])+'</b></div>'}).join('')+'</div>'}
function cards(a){return '<div class="kpi-grid slim rh26-kpis">'+a.map(function(x){return '<div class="kpi '+(x[3]||'')+'"><span>'+esc2(x[0])+'</span><strong>'+esc2(x[1])+'</strong><small>'+esc2(x[2]||'')+'</small></div>'}).join('')+'</div>'}
function compareRows(sim,hist){if(!hist)return '';var rows=[['Total bruto',sim.bruto,hist.gross],['Deduções',sim.ded,hist.discounts],['Líquido',sim.liq,hist.net],['FGTS da rescisão',sim.fgTotal,hist.fgts]];return '<article class="panel rh31-compare"><div class="panel-head"><div><span class="panel-kicker">CONFERÊNCIA COM HISTÓRICO IMPORTADO</span><h3>Simulado x Rescisão real</h3><p>Valores importados da competência do desligamento, sem tratar “Líquido Rescisão” como desconto.</p></div></div><div class="table-wrap"><table><thead><tr><th>Item</th><th class="money">Simulado</th><th class="money">Real importado</th><th class="money">Diferença</th></tr></thead><tbody>'+rows.map(function(x){var d=r2(x[1]-x[2]),ok=Math.abs(d)<=.02;return '<tr><td>'+esc2(x[0])+'</td><td class="money">'+money(x[1])+'</td><td class="money">'+money(x[2])+'</td><td class="money '+(ok?'rh31-ok':'rh31-warn')+'"><b>'+money(d)+'</b></td></tr>'}).join('')+'</tbody></table></div></article>'}
async function calc(){
  var p=person(E('rh26-person')&&E('rh26-person').value);if(!p)return null;var dt=date(E('rh26-date')&&E('rh26-date').value)||new Date(),type=E('rh26-type')?E('rh26-type').value:'pedido',notice=E('rh26-notice')?E('rh26-notice').value:'na',hist=await history(pid(p),dt),salary=n(hist&&hist.folha&&hist.folha.salario)||n(p.salario),days=Math.min(30,dt.getDate()),saldo=salary/30*days,a13=avos13(dt.getFullYear(),p.admissao,dt,dt.getMonth()+1),v13=salary/12*a13,avf=avosFerias(p.admissao,dt),vf=salary/12*avf,ven=Math.max(0,n(E('rh26-over')&&E('rh26-over').value))*salary,ter=(vf+ven)/3,yd=years(p.admissao,dt),noticeDays=Math.min(90,30+yd*3),aviso=type==='empregador'&&notice==='indenizado'?salary/30*noticeDays:0,av13=aviso?salary/12:0,avfut=aviso?salary/12:0,cct=parseBR(E('rh26-cct')&&E('rh26-cct').value),cred=parseBR(E('rh26-cred')&&E('rh26-cred').value),manualDisc=parseBR(E('rh26-disc')&&E('rh26-disc').value),fg=parseBR(E('rh26-fgts')&&E('rh26-fgts').value),inssM=hist?hist.inss:inss(saldo,dt),inss13=hist?hist.inss13:inss(v13,dt),irrfM=hist?hist.irrf:irrf(saldo,inssM,dt),irrf13=hist?hist.irrf13:irrf(v13,inss13,dt),operational=manualDisc>0?manualDisc:(hist?hist.other:0),noticeDisc=type==='pedido'&&notice==='desconto'?salary:0,bruto=saldo+v13+vf+ven+ter+aviso+av13+avfut+cct+cred,ded=inssM+inss13+irrfM+irrf13+operational+noticeDisc,fgm=saldo*.08,fg13=(v13+av13)*.08,fgav=aviso*.08,multa=type==='empregador'?fg*.4:0,fgTotal=fgm+fg13+fgav;
  return{p:p,date:dt,type:type,notice:notice,hist:hist,salary:salary,days:days,saldo:r2(saldo),a13:a13,v13:r2(v13),avf:avf,vf:r2(vf),ven:r2(ven),ter:r2(ter),noticeDays:noticeDays,aviso:r2(aviso),av13:r2(av13),avfut:r2(avfut),cct:r2(cct),cred:r2(cred),inss:r2(inssM),inss13:r2(inss13),irrf:r2(irrfM),irrf13:r2(irrf13),operational:r2(operational),noticeDisc:r2(noticeDisc),bruto:r2(bruto),ded:r2(ded),liq:r2(bruto-ded),fg:r2(fg),fgm:r2(fgm),fg13:r2(fg13),fgav:r2(fgav),fgTotal:r2(fgTotal),multa:r2(multa),custo:r2(bruto+fgTotal+multa)}
}
async function render(){
  var box=E('rh26-result');if(!box)return;box.innerHTML='<div class="empty-state"><h2>Calculando...</h2><p>Conferindo histórico e bases da rescisão.</p></div>';
  var x=await calc();if(!x)return;window.rhV31TerminationResult=x;var hist=x.hist,mode=hist?'Conferência histórica':'Estimativa gerencial',taxLabel=hist?'histórico importado':'estimado pelas tabelas da competência';
  box.innerHTML='<div class="panel-head"><div><span class="panel-kicker">RELATÓRIO ANALÍTICO · '+esc2(mode.toUpperCase())+'</span><h2>'+esc2(x.p.nome||'Colaborador')+'</h2><p>'+(x.type==='empregador'?'Despedida sem justa causa pelo empregador':'Pedido de demissão')+' · '+brdate(x.date)+' · salário-base '+money(x.salary)+'</p></div></div>'+cards([['Total bruto',money(x.bruto),'verbas rescisórias'],['Deduções',money(x.ded),hist?'impostos + descontos reais identificados':'impostos estimados + descontos informados'],['Líquido',money(x.liq),'a pagar','featured'],['Custo empregador',money(x.custo),'bruto + FGTS/multa']])+'<div class="rh26-term"><div><h3>Verbas rescisórias</h3>'+lines([['Saldo de salário',x.saldo],['13º proporcional '+x.a13+'/12',x.v13],['Férias proporcionais '+x.avf+'/12',x.vf],['Férias vencidas',x.ven],['1/3 constitucional',x.ter],['Aviso-prévio indenizado '+x.noticeDays+' dias',x.aviso],['13º sobre aviso',x.av13],['Férias sobre aviso',x.avfut],['Indenização CCT',x.cct],['Outros créditos',x.cred]])+'</div><div><h3>Deduções</h3>'+lines([['INSS sobre rescisão ('+taxLabel+')',x.inss],['INSS 13º ('+taxLabel+')',x.inss13],['IRRF sobre rescisão ('+taxLabel+')',x.irrf],['IRRF 13º ('+taxLabel+')',x.irrf13],['Descontos operacionais / benefícios',x.operational],['Aviso descontado',x.noticeDisc]])+'</div></div><article class="panel rh26-base"><h3>Base de cálculo e FGTS</h3><div class="rh26-memory"><div><span>Saldo FGTS informado</span><b>'+money(x.fg)+'</b></div><div><span>FGTS mensal</span><b>'+money(x.fgm)+'</b></div><div><span>FGTS 13º</span><b>'+money(x.fg13)+'</b></div><div><span>FGTS aviso</span><b>'+money(x.fgav)+'</b></div><div><span>Multa FGTS</span><b>'+money(x.multa)+'</b></div><div><span>Base INSS mensal</span><b>'+money(x.saldo)+'</b></div><div><span>Base INSS 13º</span><b>'+money(x.v13)+'</b></div></div></article>'+compareRows(x,hist)+'<div class="rh-plan-warning"><b>'+esc2(mode)+'</b><span>'+(hist?'Foi encontrada uma rescisão importada na mesma competência. Impostos e descontos operacionais do histórico foram usados para calibrar a conferência.':'Sem rescisão histórica na competência: INSS/IRRF são estimados e benefícios/VR, médias, CCT, estabilidade e outros descontos devem ser informados ou integrados antes do cálculo oficial.')+'</span></div>';
}
function bind(){
  var btn=E('rh26-calc');if(!btn||btn.dataset.v31==='1')return false;btn.dataset.v31='1';btn.onclick=function(e){if(e)e.preventDefault();render().catch(function(err){try{toast('Não foi possível calcular a rescisão: '+err.message,true)}catch(ignore){}})};
  var type=E('rh26-type'),notice=E('rh26-notice');if(type&&notice){var sync=function(){if(type.value==='pedido'&&notice.value==='indenizado')notice.value='na'};type.addEventListener('change',sync);sync()}
  var form=btn.closest('.rh-plan-form');if(form&&!E('rh31-calibration-note')){var note=document.createElement('div');note.id='rh31-calibration-note';note.className='rh31-calibration-note';note.innerHTML='<b>Conferência automática</b><span>Se já existir rescisão importada para o colaborador na competência escolhida, o sistema compara a simulação com o histórico real e separa “Líquido Rescisão” dos descontos.</span>';form.insertBefore(note,btn)}
  return true;
}
function style(){if(E('_rh31'))return;var s=document.createElement('style');s.id='_rh31';s.textContent='.rh31-calibration-note{grid-column:1/-1;display:flex;gap:8px;align-items:flex-start;padding:10px 12px;border:1px solid var(--line-soft);border-radius:10px;background:var(--surface-2);font-size:.75rem}.rh31-calibration-note b{color:var(--gold);white-space:nowrap}.rh31-calibration-note span{color:var(--muted)}.rh31-compare{margin-top:16px}.rh31-compare table{min-width:620px!important}.rh31-ok{color:var(--emerald,#41d6a3)!important}.rh31-warn{color:var(--red,#ff7676)!important}';document.head.appendChild(s)}
var oldRenderAll=renderAll;renderAll=function(){var out=oldRenderAll.apply(this,arguments);style();setTimeout(bind,0);return out};
var obs=new MutationObserver(function(){style();bind()});
function init(){style();bind();obs.observe(document.body,{childList:true,subtree:true})}
window.rhV31RenderTermination=render;window.rhV31HistoricalTermination=history;window.rhV31CalcTermination=calc;
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
