/* RH v54 — provisões seguras e idempotentes: 13º e férias sem re-render desnecessário */
(function(){
'use strict';
var originalRosterLoad=window.rhRosterLoad;
var originalActiveIds=window.rhRosterActiveIds;
var originalNameActive=window.rhRosterNameIsActive;
var ctxCache=new Map(),inflight=null;
function E(id){return document.getElementById(id)}
function norm(v){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\s+/g,' ').trim().toLowerCase()}
function num(v){var x=Number(v);return isFinite(x)?x:0}
function r2(v){return Math.round((num(v)+Number.EPSILON)*100)/100}
function parseMoney(v){return Number(String(v||'').replace(/R\$|\s/g,'').replace(/\./g,'').replace(',','.'))||0}
function money(v){try{return fmt(r2(v))}catch(e){return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',minimumFractionDigits:2,maximumFractionDigits:2}).format(r2(v))}}
function personKey(p){return String(p&&p.colaborador_id||p&&p.id||'')}
function canonical(){var s=null;try{s=typeof originalActiveIds==='function'?originalActiveIds():null}catch(e){}return s&&typeof s.has==='function'?s:new Set()}
function activeNameMap(){var ids=canonical(),m=new Map();(S.colaboradores||[]).forEach(function(p){var id=String(p.id||'');if(id&&ids.has(id)&&p.nome)m.set(norm(p.nome),id)});(S.pessoas||[]).forEach(function(p){var id=personKey(p);if(id&&ids.has(id)&&p.nome)m.set(norm(p.nome),id)});return m}
function rowName(tr){var first=tr&&tr.cells&&tr.cells[0],b=first&&first.querySelector&&first.querySelector('b');return String(b&&b.textContent||first&&first.textContent||'').trim()}
function resolveRowId(tr){var ids=canonical(),raw=String(tr&&tr.dataset&&(tr.dataset.id||tr.dataset.colaboradorId)||'');if(raw&&ids.has(raw))return raw;var byName=activeNameMap(),nm=norm(rowName(tr));if(nm&&byName.has(nm))return byName.get(nm);var hit=(S.pessoas||[]).find(function(p){return norm(p.nome)===nm&&ids.has(personKey(p))});if(hit)return personKey(hit);hit=(S.colaboradores||[]).find(function(p){return norm(p.nome)===nm&&ids.has(String(p.id||''))});if(hit)return String(hit.id||'');return raw}
function rowActive(tr){var ids=canonical();if(!ids.size)return true;var id=resolveRowId(tr);return !!(id&&ids.has(id))}
function extendedIds(){var ids=canonical(),out=new Set();ids.forEach(function(x){out.add(String(x))});var names=activeNameMap();(S.pessoas||[]).forEach(function(p){if(names.has(norm(p.nome))){if(p.id)out.add(String(p.id));if(p.colaborador_id)out.add(String(p.colaborador_id))}});(S.colaboradores||[]).forEach(function(p){if(names.has(norm(p.nome))&&p.id)out.add(String(p.id))});document.querySelectorAll('#page-planejamento [data-plan-pane="13"] tbody tr[data-id],#page-planejamento [data-plan-pane="ferias"] tbody tr[data-id]').forEach(function(tr){if(names.has(norm(rowName(tr)))){var id=String(tr.dataset.id||'');if(id)out.add(id)}});return out}
function anchor(){var a=(window.RH_PERIOD&&RH_PERIOD.active&&RH_PERIOD.active.length?RH_PERIOD.active:(S.competencia?[S.competencia]:[])).slice().sort(function(x,y){return String(x.competencia||'').localeCompare(String(y.competencia||''))}),c=a[a.length-1],raw=c&&c.competencia,x=raw?new Date(String(raw).slice(0,10)+'T12:00:00'):null;return x&&!isNaN(x.getTime())?new Date(x.getFullYear(),x.getMonth()+1,0,12):new Date()}
function rates(){var e=(S.competencia&&S.competencia.encargos)||{},b=num(e.base_total_inss),rat=b?num(e.rat)/b:0,ter=b?num(e.terceiros)/b:0,pis=b?num(e.valor_pis)/b:0;return{inss:.20,rat:rat>0&&rat<.05?rat:.01,terc:ter>0&&ter<.12?ter:.058,fgts:.08,pis:pis>0&&pis<.04?pis:.01}}
function context(id,a){var k=id+'|'+a.getFullYear()+'-'+(a.getMonth()+1);if(ctxCache.has(k))return ctxCache.get(k);var p=typeof window.rhV34TerminationContext==='function'?Promise.resolve(window.rhV34TerminationContext(id,a)):Promise.resolve(null);ctxCache.set(k,p);return p}
function fallbackPerson(id,name){return (S.pessoas||[]).find(function(p){return personKey(p)===id||norm(p.nome)===norm(name)})||(S.colaboradores||[]).find(function(p){return String(p.id||'')===id||norm(p.nome)===norm(name)})||null}
function baseOf(c,p){var v=num(c&&c.latest&&c.latest.salario)+(c&&c.recurring||[]).reduce(function(s,x){return s+num(x.valor)},0)+num(c&&c.variableAvg);if(v>0)return r2(v);return r2(num(p&&p.salario))}
function writeText(el,text){text=String(text==null?'':text);if(el&&String(el.textContent||'')!==text)el.textContent=text}
function writeBold(el,text){text=String(text==null?'':text);if(!el)return;var b=el.querySelector(':scope > b');if(b&&el.children.length===1){writeText(b,text);return}var html='<b>'+text+'</b>';if(el.innerHTML!==html)el.innerHTML=html}
function setHidden(el,v){if(el&&el.hidden!==!!v)el.hidden=!!v}
function setKpi(pane,label,val,small){var value=money(val);pane.querySelectorAll('.kpi').forEach(function(k){var s=k.querySelector('span'),b=k.querySelector('strong'),sm=k.querySelector('small');if(s&&b&&norm(s.textContent)===norm(label)){writeText(b,value);if(sm&&small!=null)writeText(sm,small)}})}
function ensureRows(){var p13=document.querySelector('[data-plan-pane="13"]'),pf=document.querySelector('[data-plan-pane="ferias"]'),t13=p13&&p13.querySelector('table.rh26-wide'),tf=pf&&pf.querySelector('table.rh26-wide');var empty13=!t13||!t13.querySelector('tbody tr.rh26-row'),emptyF=!tf||!tf.querySelector('tbody tr.rh26-row');if((empty13||emptyF)&&typeof window.rhV26EnhancePlanning==='function'){var page=E('page-planejamento');if(page)delete page.dataset.v26;try{window.rhV26EnhancePlanning()}catch(e){console.warn('RH v54 rebuild:',e)}}}
async function refresh13(){var pane=document.querySelector('[data-plan-pane="13"]'),table=pane&&pane.querySelector('table.rh26-wide');if(!pane||!table)return{n:0};var all=Array.from(table.querySelectorAll('tbody tr.rh26-row'));all.forEach(function(tr){setHidden(tr,!rowActive(tr))});var trs=all.filter(rowActive),a=anchor(),rr=rates(),contexts=await Promise.all(trs.map(function(tr){return context(resolveRowId(tr),a)})),sum={pm:0,saldo:0,enc:0,total:0};trs.forEach(function(tr,i){var td=tr.children,id=resolveRowId(tr),p=fallbackPerson(id,rowName(tr));if(td.length<16)return;var b=baseOf(contexts[i],p),av=parseInt(String(td[3].textContent||'0'),10)||0,prev=parseMoney(td[4].textContent),pm=av?b/12:0,current=b/12*av,pago=parseMoney(td[7].textContent),adi=parseMoney(td[8].textContent),aj=current-prev-pm,saldo=Math.max(0,current-pago-adi),ei=saldo*rr.inss,er=saldo*rr.rat,et=saldo*rr.terc,ef=saldo*rr.fgts,ep=saldo*rr.pis,enc=ei+er+et+ef+ep,total=saldo+enc;[[2,b],[4,prev],[5,pm],[6,aj],[10,ei],[11,er],[12,et],[13,ef],[14,ep]].forEach(function(q){writeText(td[q[0]],money(q[1]))});writeBold(td[9],money(saldo));writeBold(td[15],money(total));sum.pm+=pm;sum.saldo+=saldo;sum.enc+=enc;sum.total+=total});setKpi(pane,'Saldo provisionado',sum.saldo,trs.length+' colaboradores ativos');setKpi(pane,'Provisão do mês',sum.pm,'08/2026');setKpi(pane,'Encargos sobre saldo',sum.enc,'INSS Emp. + RAT + Terceiros + FGTS + PIS');setKpi(pane,'Custo provisionado',sum.total,'saldo + encargos');return{n:trs.length,sum:sum}}
async function refreshFerias(){var pane=document.querySelector('[data-plan-pane="ferias"]'),table=pane&&pane.querySelector('table.rh26-wide');if(!pane||!table)return{n:0};var all=Array.from(table.querySelectorAll('tbody tr.rh26-row'));all.forEach(function(tr){setHidden(tr,!rowActive(tr))});var trs=all.filter(rowActive),a=anchor(),rr=rates(),contexts=await Promise.all(trs.map(function(tr){return context(resolveRowId(tr),a)})),sum={pm:0,saldo:0,enc:0,total:0};trs.forEach(function(tr,i){var td=tr.children,id=resolveRowId(tr),p=fallbackPerson(id,rowName(tr));if(td.length<19)return;var b=baseOf(contexts[i],p),av=parseInt(String(td[4].textContent||'0'),10)||0,prev=parseMoney(td[5].textContent),pm=b/12*4/3,fer=b/12*av,ter=fer/3,current=fer+ter,goz=parseMoney(td[10].textContent),ind=parseMoney(td[11].textContent),aj=current-prev-pm,saldo=Math.max(0,current-goz-ind),ei=saldo*rr.inss,er=saldo*rr.rat,et=saldo*rr.terc,ef=saldo*rr.fgts,ep=saldo*rr.pis,enc=ei+er+et+ef+ep,total=saldo+enc;[[5,prev],[6,pm],[7,aj],[8,fer],[9,ter],[13,ei],[14,er],[15,et],[16,ef],[17,ep]].forEach(function(q){writeText(td[q[0]],money(q[1]))});writeBold(td[12],money(saldo));writeBold(td[18],money(total));sum.pm+=pm;sum.saldo+=saldo;sum.enc+=enc;sum.total+=total});setKpi(pane,'Saldo provisionado',sum.saldo,trs.length+' colaboradores ativos');setKpi(pane,'Provisão do mês',sum.pm,'férias + 1/3');setKpi(pane,'Encargos sobre saldo',sum.enc,'INSS Emp. + RAT + Terceiros + FGTS + PIS');setKpi(pane,'Custo provisionado',sum.total,'saldo + encargos');return{n:trs.length,sum:sum}}
async function safeRefresh(){if(typeof originalRosterLoad==='function')await originalRosterLoad(false);ensureRows();var out=await Promise.all([refresh13(),refreshFerias()]);window.RH_V54_LAST_PROVISION={at:new Date().toISOString(),decimo:out[0],ferias:out[1],ativos:canonical().size};return window.RH_V54_LAST_PROVISION}
window.rhRosterActiveIds=extendedIds;
window.rhRosterNameIsActive=function(name){var ids=canonical();if(!ids.size)return typeof originalNameActive==='function'?originalNameActive(name):true;return activeNameMap().has(norm(name))};
window.rhRosterIsActive=function(p){var ids=canonical();if(!ids.size)return true;var id=personKey(p);return ids.has(id)||activeNameMap().has(norm(p&&p.nome))};
window.rhRosterFilter=function(list){return (list||[]).filter(window.rhRosterIsActive)};
window.rhProvisionRefresh=safeRefresh;
window.RH_PROVISION_SAFE_V54=true;
function kick(){if(inflight)return inflight;inflight=Promise.resolve(safeRefresh()).catch(function(e){console.warn('RH v54:',e)}).finally(function(){inflight=null});return inflight}
function firstKick(){setTimeout(kick,80)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',firstKick);else firstKick();
document.addEventListener('click',function(e){var b=e.target&&e.target.closest&&e.target.closest('[data-plan-tab="13"],[data-plan-tab="ferias"]');if(b)setTimeout(kick,100)},true);
})();
