/* RH v71 — remuneração automática, conferência e histórico reversível das férias. */
(function(){
'use strict';
var V71={token:0,current:null,loadingId:'',lastSignature:'',historyKey:'lnb_rh_vacation_previews_v71'};
window.RH_VACATION_REMUNERATION_V71=true;
function E71(id){return document.getElementById(id)}
function n71(v){var x=Number(v);return isFinite(x)?x:0}
function r71(v){return Math.round((n71(v)+Number.EPSILON)*100)/100}
function p71(v){return n71(String(v==null?'':v).replace(/R\$|\s/g,'').replace(/\./g,'').replace(',','.'))}
function m71(v){return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(n71(v))}
function val71(v){return r71(v).toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2})}
function esc71(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function norm71(v){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase()}
function key71(p){return String(p&&p.colaborador_id||p&&p.id||'')}
function person71(id){try{if(typeof window.rhV70People==='function')return window.rhV70People().find(function(p){return key71(p)===String(id)})||null}catch(e){}return null}
function isRecurring71(l){var name=norm71(String(l&&l.rubrica_codigo||l&&l.codigo||'')+' '+String(l&&l.rubrica_nome||l&&l.nome||'')),type=String(l&&l.tipo||'').toLowerCase();if(type&&type!=='provento'&&type!=='p')return false;return /DUPLA FUNCAO|ADICIONAL.*FUNCAO|GRATIFICACAO.*FUNCAO|INSALUBRIDADE|PERICULOSIDADE/.test(name)}
function compose71(p,ctx){ctx=ctx||{};var latest=ctx.latest||{},salary=n71(latest.salario)||n71(p&&p.salario_base)||n71(p&&p.salario),lines=(ctx.recurring||[]).map(function(x){return{codigo:String(x.codigo||''),nome:String(x.nome||'Adicional recorrente'),valor:r71(x.valor)}});if(!lines.length){var launches=ctx.latestLaunches||(p&&p.lancamentos)||[];lines=launches.filter(isRecurring71).map(function(x){return{codigo:String(x.rubrica_codigo||x.codigo||''),nome:String(x.rubrica_nome||x.nome||'Adicional recorrente'),valor:r71(x.valor)}})}var fixed=r71(lines.reduce(function(s,x){return s+n71(x.valor)},0)),average=r71(ctx.variableAvg),base=r71(salary+fixed+average),competence=String(latest._comp||ctx.last||'').slice(0,7);return{personId:key71(p),name:String(p&&p.nome||'Colaborador'),salary:r71(salary),lines:lines,fixed:fixed,average:average,base:base,competence:competence,source:latest&&latest.id?'Última folha importada':'Cadastro do colaborador',loadedAt:new Date().toISOString(),reviewed:false}}
window.rhV71ComposeRemuneration=compose71;
function input71(id,value){var e=E71(id);if(!e)return;e.value=val71(value);e.dataset.rh71Auto=String(r71(value))}
function currentValues71(){return{salary:p71(E71('rh70-salary')&&E71('rh70-salary').value),fixed:p71(E71('rh70-fixed')&&E71('rh70-fixed').value),average:p71(E71('rh70-average')&&E71('rh70-average').value)}}
function diff71(){var c=V71.current,v=currentValues71();if(!c)return{changed:false,rows:[]};var rows=[['Salário-base',c.salary,v.salary],['Adicionais recorrentes',c.fixed,v.fixed],['Média variável',c.average,v.average]].map(function(x){return{x:x[0],source:r71(x[1]),used:r71(x[2]),diff:r71(x[2]-x[1])}});return{changed:rows.some(function(x){return Math.abs(x.diff)>.009}),rows:rows}}
function sourceHtml71(loading,error){if(loading)return'<b>Carregando composição remuneratória...</b><span>Consultando a última folha, adicionais recorrentes e médias variáveis.</span>';if(error)return'<b>Base automática indisponível</b><span>'+esc71(error)+' Os campos continuam editáveis para conferência manual.</span>';var c=V71.current;if(!c)return'<b>Composição remuneratória</b><span>Selecione um colaborador para carregar salário, adicionais e médias.</span>';var lines=c.lines.length?c.lines.map(function(x){return'<div><span>'+esc71(x.nome)+(x.codigo?' · '+esc71(x.codigo):'')+'</span><strong>'+m71(x.valor)+'</strong></div>'}).join(''):'<div><span>Nenhum adicional salarial recorrente detectado</span><strong>'+m71(0)+'</strong></div>';return'<div class="rh71-source-head"><div><b>Base carregada automaticamente</b><span>'+esc71(c.source)+(c.competence?' · competência '+esc71(c.competence.slice(5,7)+'/'+c.competence.slice(0,4)):'')+'</span></div><strong>'+m71(c.base)+'</strong></div><div class="rh71-source-lines"><div><span>Salário-base vigente</span><strong>'+m71(c.salary)+'</strong></div>'+lines+'<div><span>Média variável dos meses disponíveis</span><strong>'+m71(c.average)+'</strong></div></div>'}
function renderSource71(loading,error){var box=E71('rh71-remuneration-source');if(box){box.classList.toggle('error',!!error);box.innerHTML=sourceHtml71(loading,error)}}
async function hydrate71(id){var p=person71(id),pid=key71(p);if(!p)return;if(V71.loadingId===pid)return;V71.loadingId=pid;V71.current=null;var token=++V71.token,button=E71('rh70-calc-vacation');if(button){button.disabled=true;button.textContent='Carregando remuneração...'}renderSource71(true);try{var dt=E71('rh70-start')&&E71('rh70-start').value?new Date(E71('rh70-start').value+'T12:00:00'):new Date(),ctx={};if(typeof window.rhV34TerminationContext==='function')ctx=await window.rhV34TerminationContext(pid,dt)||{};if(token!==V71.token)return;V71.current=compose71(p,ctx);input71('rh70-salary',V71.current.salary);input71('rh70-fixed',V71.current.fixed);input71('rh70-average',V71.current.average);renderSource71(false);updateManual71()}catch(e){if(token!==V71.token)return;V71.current=compose71(p,{});input71('rh70-salary',V71.current.salary);input71('rh70-fixed',V71.current.fixed);input71('rh70-average',V71.current.average);renderSource71(false,'Não foi possível consultar todo o histórico: '+(e.message||String(e)))}finally{if(token===V71.token){V71.loadingId='';if(button){button.disabled=false;button.textContent='Calcular prévia de férias'}}}}
function updateManual71(){var box=E71('rh71-manual-warning'),d=diff71();if(!box)return;box.hidden=!d.changed;box.innerHTML=d.changed?'<b>Ajuste manual identificado</b><span>O cálculo usará os valores editados. A diferença ficará registrada na memória de conferência desta prévia.</span>':''}
function installForm71(){var form=E71('rh70-person')&&E71('rh70-person').closest('.rh70-form');if(!form)return;if(!E71('rh71-remuneration-source')){var box=document.createElement('div');box.id='rh71-remuneration-source';box.className='rh71-source rh70-full';var fixed=E71('rh70-average')&&E71('rh70-average').closest('label');if(fixed)fixed.insertAdjacentElement('afterend',box);else form.insertBefore(box,form.firstChild);renderSource71(false)}if(!E71('rh71-manual-warning')){var w=document.createElement('div');w.id='rh71-manual-warning';w.className='rh71-manual rh70-full';w.hidden=true;var source=E71('rh71-remuneration-source');if(source)source.insertAdjacentElement('afterend',w)}['rh70-salary','rh70-fixed','rh70-average'].forEach(function(id){var e=E71(id);if(e&&!e.dataset.rh71Bound){e.dataset.rh71Bound='1';e.addEventListener('input',updateManual71)}})}
function validations71(){var missing=[],c=V71.current;if(!c||!c.salary)missing.push('remuneração de origem');if(!E71('rh70-acq-start')||!E71('rh70-acq-start').value)missing.push('início do período aquisitivo');if(!E71('rh70-acq-end')||!E71('rh70-acq-end').value)missing.push('fim do período aquisitivo');if(!E71('rh70-start')||!E71('rh70-start').value)missing.push('início das férias');[['rh70-cpf','CPF'],['rh70-pis','PIS/PASEP'],['rh70-ctps','CTPS']].forEach(function(x){if(!E71(x[0])||!String(E71(x[0]).value||'').trim())missing.push(x[1])});return missing}
function readHistory71(){try{return JSON.parse(sessionStorage.getItem(V71.historyKey)||'[]')}catch(e){return[]}}
function writeHistory71(rows){try{sessionStorage.setItem(V71.historyKey,JSON.stringify(rows.slice(0,12)))}catch(e){}}
function record71(){var panel=E71('rh70-vacation-result'),name=(panel&&panel.querySelector('h2')||{}).textContent||'',start=E71('rh70-start')&&E71('rh70-start').value,v=currentValues71(),text=panel&&panel.innerText||'',net=(text.match(/Líquido\s*R\$\s*([\d.,]+)/i)||[])[1]||'',signature=[name,start,v.salary,v.fixed,v.average,net].join('|');if(!name||!start||signature===V71.lastSignature)return;V71.lastSignature=signature;var rows=readHistory71();rows.unshift({id:Date.now(),name:name,start:start,base:r71(v.salary+v.fixed+v.average),net:net,status:'Rascunho'});writeHistory71(rows);renderHistory71()}
function renderHistory71(){var box=E71('rh71-history');if(!box)return;var rows=readHistory71().slice(0,5);box.innerHTML='<div class="rh71-meta-head"><div><b>Histórico reversível desta sessão</b><span>Não grava férias nem altera o cadastro.</span></div></div>'+(rows.length?rows.map(function(x){return'<div class="rh71-history-row"><span><b>'+esc71(x.name)+'</b><small>'+esc71(String(x.start||'').split('-').reverse().join('/'))+' · base '+m71(x.base)+'</small></span><strong>'+esc71(x.status)+'</strong></div>'}).join(''):'<p>Nenhuma prévia calculada nesta sessão.</p>')}
function attachResult71(){var result=E71('rh70-vacation-result');if(!result||!result.querySelector('#rh70-vacation-package')||E71('rh71-result-meta'))return;var d=diff71(),missing=validations71(),meta=document.createElement('section');meta.id='rh71-result-meta';meta.className='rh71-result-meta';meta.innerHTML='<div class="rh71-meta-head"><div><b>Conferência da base remuneratória</b><span>'+(V71.current?esc71(V71.current.source)+(V71.current.competence?' · '+esc71(V71.current.competence.slice(5,7)+'/'+V71.current.competence.slice(0,4)):''):'Origem não identificada')+'</span></div><button type="button" id="rh71-review" class="button secondary">Marcar como conferida</button></div><div class="rh71-compare"><div><span>Componente</span><b>Origem</b><b>Usado</b><b>Diferença</b></div>'+d.rows.map(function(x){return'<div><span>'+esc71(x.x)+'</span><b>'+m71(x.source)+'</b><b>'+m71(x.used)+'</b><b class="'+(Math.abs(x.diff)>.009?'warn':'ok')+'">'+m71(x.diff)+'</b></div>'}).join('')+'</div><div class="rh71-validation '+(missing.length?'warn':'ok')+'"><b>'+(missing.length?'Pendências para documento completo':'Dados essenciais conferidos')+'</b><span>'+(missing.length?esc71(missing.join(', ')):'A prévia possui base remuneratória e dados essenciais preenchidos.')+'</span></div><div id="rh71-history" class="rh71-history"></div>';var warning=result.querySelector('.rh-plan-warning');if(warning)warning.insertAdjacentElement('beforebegin',meta);else result.appendChild(meta);record71();renderHistory71()}
function review71(){var b=E71('rh71-review');if(!b)return;var reviewed=b.dataset.reviewed!=='1';b.dataset.reviewed=reviewed?'1':'0';b.textContent=reviewed?'Conferida · voltar a rascunho':'Marcar como conferida';var rows=readHistory71();if(rows.length){rows[0].status=reviewed?'Conferida':'Rascunho';writeHistory71(rows);renderHistory71()}}
function pdfMeta71(){var c=V71.current,d=diff71();return c?{source:c.source,competence:c.competence,salary:c.salary,fixed:c.fixed,average:c.average,base:r71(currentValues71().salary+currentValues71().fixed+currentValues71().average),lines:c.lines,difference:d.changed}:null}
window.rhV71VacationMeta=pdfMeta71;window.rhV71HydrateVacation=hydrate71;window.rhV71VacationDifference=diff71;
function style71(){if(E71('_rh71'))return;var s=document.createElement('style');s.id='_rh71';s.textContent='.rh71-source,.rh71-manual{padding:12px 14px;border:1px solid var(--line-soft);border-radius:11px;background:var(--surface-2)}.rh71-source>b,.rh71-manual b{color:var(--gold)}.rh71-source>span,.rh71-manual span{display:block;margin-top:3px;color:var(--muted);font-size:10px}.rh71-source.error{border-color:var(--red)}.rh71-source-head,.rh71-meta-head{display:flex;justify-content:space-between;gap:14px;align-items:flex-start}.rh71-source-head b,.rh71-meta-head b{display:block;color:var(--gold);font-size:11px}.rh71-source-head span,.rh71-meta-head span{display:block;margin-top:3px;color:var(--muted);font-size:9px}.rh71-source-head>strong{font-size:17px;white-space:nowrap}.rh71-source-lines{display:grid;gap:5px;margin-top:10px}.rh71-source-lines>div{display:flex;justify-content:space-between;gap:12px;padding-top:5px;border-top:1px solid var(--line-soft);font-size:10px}.rh71-result-meta{display:grid;gap:12px;margin-top:14px;padding:14px;border:1px solid var(--line-soft);border-radius:12px;background:var(--surface-2)}.rh71-compare{display:grid;gap:0;border:1px solid var(--line-soft);border-radius:9px;overflow:hidden}.rh71-compare>div{display:grid;grid-template-columns:1.4fr repeat(3,1fr);gap:8px;padding:8px 10px;border-bottom:1px solid var(--line-soft);font-size:9px}.rh71-compare>div:first-child{background:var(--surface);color:var(--muted);text-transform:uppercase}.rh71-compare>div:last-child{border-bottom:0}.rh71-compare b{text-align:right}.rh71-compare .warn,.rh71-validation.warn b{color:var(--gold)}.rh71-compare .ok,.rh71-validation.ok b{color:var(--emerald)}.rh71-validation{display:flex;gap:10px;padding:9px 11px;border:1px solid var(--line-soft);border-radius:9px;font-size:9px}.rh71-validation span{color:var(--muted)}.rh71-history{display:grid;gap:6px}.rh71-history-row{display:flex;justify-content:space-between;gap:12px;padding:8px 10px;border:1px solid var(--line-soft);border-radius:8px}.rh71-history-row span b,.rh71-history-row span small{display:block}.rh71-history-row small{margin-top:2px;color:var(--muted);font-size:8px}.rh71-history-row>strong{color:var(--gold);font-size:9px}@media(max-width:700px){.rh71-source-head,.rh71-meta-head{flex-direction:column}.rh71-compare>div{grid-template-columns:1fr 1fr}.rh71-compare>div>*:nth-child(2){display:none}}';document.head.appendChild(s)}
document.addEventListener('change',function(e){if(e.target&&e.target.id==='rh70-person')setTimeout(function(){hydrate71(e.target.value)},0)},true);
document.addEventListener('click',function(e){if(e.target&&e.target.closest&&e.target.closest('#rh71-review')){e.preventDefault();review71()}},true);
var mo71=new MutationObserver(function(){install71();setTimeout(attachResult71,0)});
function install71(){style71();installForm71();if(E71('rh70-person')&&E71('rh70-person').value&&!V71.current&&!V71.loadingId)hydrate71(E71('rh70-person').value)}
function init71(){install71();[250,800,1600].forEach(function(ms){setTimeout(install71,ms)});mo71.observe(document.body,{childList:true,subtree:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init71);else init71();
})();
