/* RH v38 — Planejamento: UI aprovada + quadro ativo da stability baseline */
(function(){
'use strict';
var V={timer:0};
function E(id){return document.getElementById(id)}
function norm(v){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\s+/g,' ').trim().toLowerCase()}
function parseMoney(v){return Number(String(v||'').replace(/R\$|\s/g,'').replace(/\./g,'').replace(',','.'))||0}
function money(v){try{return fmt(Number(v)||0)}catch(e){return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v)||0)}}
function setText(el,v){if(el&&el.textContent!==v)el.textContent=v}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function date(v){if(!v)return null;if(v instanceof Date)return new Date(v.getTime());var x=new Date(String(v).slice(0,10)+'T12:00:00');return isNaN(x.getTime())?null:x}
function br(v){var x=date(v);return x?String(x.getDate()).padStart(2,'0')+'/'+String(x.getMonth()+1).padStart(2,'0')+'/'+x.getFullYear():'—'}
function ids(){return typeof window.rhRosterActiveIds==='function'?window.rhRosterActiveIds():(window.RH_CURRENT_ACTIVE_IDS||new Set())}
function isActiveRow(tr){var set=ids();if(!set||!set.size)return true;var id=String(tr.dataset.id||tr.dataset.colaboradorId||'');if(id)return set.has(id);var td=tr.cells&&tr.cells[0],name=td&&td.textContent;return typeof window.rhRosterNameIsActive==='function'?window.rhRosterNameIsActive(name):true}
function person(id){var p=(S.pessoas||[]).find(function(x){return String(x.colaborador_id||x.id||'')===String(id)});if(p)return p;return (S.colaboradores||[]).find(function(x){return String(x.id||'')===String(id)})||null}
function contextDate(){var a=(window.RH_PERIOD&&RH_PERIOD.active&&RH_PERIOD.active.length?RH_PERIOD.active:(S.competencia?[S.competencia]:[])).slice().sort(function(x,y){return String(x.competencia||'').localeCompare(String(y.competencia||''))}),c=a[a.length-1],x=date(c&&c.competencia);if(x)return new Date(x.getFullYear(),x.getMonth()+1,0,12);var m=typeof window.rhRosterMeta==='function'?window.rhRosterMeta():window.RH_CURRENT_ACTIVE_META,y=date(m&&m.competencia);return y?new Date(y.getFullYear(),y.getMonth()+1,0,12):new Date()}
function removeExecutiveSummary(pane){Array.from(pane.querySelectorAll('article.table-panel')).forEach(function(article){var table=article.querySelector('table'),title=norm((article.querySelector('h2')||{}).textContent),kick=norm((article.querySelector('.panel-kicker')||{}).textContent);if((table&&!table.classList.contains('rh26-wide'))||title.indexOf('centro de custo')>=0||kick==='resumo executivo')article.remove()})}
function makeNameOnly(kind){
  var pane=document.querySelector('[data-plan-pane="'+kind+'"]');if(!pane)return;removeExecutiveSummary(pane);var table=pane.querySelector('table.rh26-wide');if(!table)return;table.classList.add('rh38-name-list');
  Array.from(table.querySelectorAll('tbody tr')).forEach(function(tr){if(tr.dataset.rh91OfficialIndex==null&&!isActiveRow(tr))tr.remove()});var thead=table.tHead;if(thead){Array.from(thead.querySelectorAll('.rh30-group-head')).forEach(function(x){x.remove()});if(thead.rows[0]&&thead.rows[0].cells[0])setText(thead.rows[0].cells[0],'Colaborador')}
  var article=table.closest('article.table-panel');if(article){setText(article.querySelector('.panel-head h2'),kind==='13'?'Colaboradores — provisão de 13º':'Colaboradores — provisão de férias');setText(article.querySelector('.detail-note'),'Clique no colaborador para abrir a memória de cálculo completa.')}
  var wrap=table.closest('.table-wrap');if(wrap){wrap.classList.remove('rh30-scroll');var prev=wrap.previousElementSibling;if(prev&&prev.classList.contains('rh30-scroll-note'))prev.remove()}
  Array.from(table.querySelectorAll('tbody tr')).forEach(function(tr){var first=tr.cells&&tr.cells[0];if(!first)return;Array.from(first.querySelectorAll('small')).forEach(function(s){s.style.display='none'});first.title='Clique para abrir a memória de cálculo'});
}
function filterForecast(){
  var pane=document.querySelector('[data-plan-pane="folha"]'),set=ids();if(!pane||!set||!set.size)return;var table=pane.querySelector('table');if(!table)return;Array.from(table.querySelectorAll('tbody tr')).forEach(function(tr){if(!isActiveRow(tr))tr.remove()});
  var rows=Array.from(table.querySelectorAll('tbody tr')),sum={prov:0,disc:0,liq:0,enc:0,ben:0,custo:0};rows.forEach(function(tr){var c=tr.cells||[];if(c.length>=8){sum.prov+=parseMoney(c[2].textContent);sum.disc+=parseMoney(c[3].textContent);sum.liq+=parseMoney(c[4].textContent);sum.enc+=parseMoney(c[5].textContent);sum.ben+=parseMoney(c[6].textContent);sum.custo+=parseMoney(c[7].textContent)}});
  Array.from(pane.querySelectorAll('.kpi')).forEach(function(card){var label=norm((card.querySelector('span')||{}).textContent),strong=card.querySelector('strong'),small=card.querySelector('small');if(!strong)return;if(label.indexOf('proventos previstos')>=0)setText(strong,money(sum.prov));else if(label.indexOf('liquido previsto')>=0)setText(strong,money(sum.liq));else if(label.indexOf('encargos + beneficios')>=0)setText(strong,money(sum.enc+sum.ben));else if(label.indexOf('custo previsto')>=0)setText(strong,money(sum.custo));if(small&&label.indexOf('proventos previstos')>=0)small.title=rows.length+' colaboradores ativos considerados'});
  var tf=table.querySelector('tfoot tr');if(tf&&tf.cells.length>=8){tf.cells[2].innerHTML='<b>'+money(sum.prov)+'</b>';tf.cells[3].innerHTML='<b>'+money(sum.disc)+'</b>';tf.cells[4].innerHTML='<b>'+money(sum.liq)+'</b>';tf.cells[5].innerHTML='<b>'+money(sum.enc)+'</b>';tf.cells[6].innerHTML='<b>'+money(sum.ben)+'</b>';tf.cells[7].innerHTML='<b>'+money(sum.custo)+'</b>'}
}
function filterTerminationSelect(){var set=ids();if(!set||!set.size)return;['rh26-person','rh-res-person'].forEach(function(id){var sel=E(id);if(!sel)return;var selected=sel.value;Array.from(sel.options).forEach(function(o){if(o.value&&!set.has(String(o.value)))o.remove()});if(!set.has(String(selected))&&sel.options.length)sel.selectedIndex=0});document.querySelectorAll('[data-plan-pane="rescisao"] select').forEach(function(sel){if(!/colaborador/i.test(String((sel.closest('label')||{}).textContent||'')))return;var selected=sel.value;Array.from(sel.options).forEach(function(o){if(o.value&&!set.has(String(o.value)))o.remove()});if(!set.has(String(selected))&&sel.options.length)sel.selectedIndex=0})}
function activeNote(){var page=E('page-planejamento'),m=typeof window.rhRosterMeta==='function'?window.rhRosterMeta():window.RH_CURRENT_ACTIVE_META;if(!page||!m)return;var warn=page.querySelector('.rh-plan-warning');if(!warn)return;var el=E('rh38-active-note');if(!el){el=document.createElement('span');el.id='rh38-active-note';warn.appendChild(el)}var comp=String(m.competencia||'').slice(0,7).split('-').reverse().join('/');setText(el,'Quadro atual: '+m.ativos+' colaboradores ativos em '+comp+'. Quem já foi desligado não entra em 13º, férias, próxima folha ou rescisões.')}
function memLine(label,value,cls){return '<div'+(cls?' class="'+cls+'"':'')+'><span>'+esc(label)+'</span><b>'+esc(value)+'</b></div>'}
async function rhProvisionOpenMemory(tr){
  if(!tr)return;var kind=tr.dataset.k,id=String(tr.dataset.id||''),p=person(id),c=tr.cells||[];
  if(kind==='ferias'&&tr.dataset.rh91OfficialIndex!=null&&typeof window.rhV91OpenVacationMemory==='function')return window.rhV91OpenVacationMemory(Number(tr.dataset.rh91OfficialIndex));
  if(typeof window.rhProvisionRefresh==='function')await window.rhProvisionRefresh();
  var ctx=typeof window.rhV34TerminationContext==='function'?await window.rhV34TerminationContext(id,contextDate()):null;
  var salary=Number(ctx&&ctx.latest&&ctx.latest.salario)||Number(p&&p.salario)||0,rec=(ctx&&ctx.recurring||[]),variable=Number(ctx&&ctx.variableAvg)||0,base=salary+rec.reduce(function(s,x){return s+(Number(x.valor)||0)},0)+variable;
  var first=tr.cells&&tr.cells[0],name=(first&&first.querySelector('b')&&first.querySelector('b').textContent)||(p&&p.nome)||'Colaborador',dep=(first&&first.querySelector('small')&&first.querySelector('small').textContent)||'',cc=(c[1]&&c[1].textContent)||'';
  var html='';html+=memLine('Admissão',br(p&&p.admissao));html+=memLine('Salário-base atual',money(salary));rec.forEach(function(x){html+=memLine(x.nome||'Verba recorrente',money(x.valor))});if(Math.abs(variable)>.004)html+=memLine('Média de verbas variáveis',money(variable));html+=memLine('Base remuneratória',money(base),'rh38-base-total');
  var enc='';
  if(kind==='13'){
    var av=(c[3]&&c[3].textContent)||'0/12',q=parseInt(av,10)||0,current=base*q/12;
    html+=memLine('Avos',av)+memLine('Saldo prov. anterior',c[4]?c[4].textContent:money(0))+memLine('Provisão do mês',c[5]?c[5].textContent:money(base/12))+memLine('Ajuste no mês',c[6]?c[6].textContent:money(0))+memLine('Valor 13º atual',money(current))+memLine('13º pago identificado',c[7]?c[7].textContent:money(0))+memLine('Adiantamento identificado',c[8]?c[8].textContent:money(0))+memLine('Saldo atual',c[9]?c[9].textContent:money(current));
    enc+=memLine('INSS Empresa',c[10]?c[10].textContent:money(0))+memLine('RAT',c[11]?c[11].textContent:money(0))+memLine('Terceiros',c[12]?c[12].textContent:money(0))+memLine('FGTS',c[13]?c[13].textContent:money(0))+memLine('PIS',c[14]?c[14].textContent:money(0))+memLine('Custo provisionado',c[15]?c[15].textContent:money(0),'total');
  }else{
    html+=memLine('Vencimento estimado',c[2]?c[2].textContent:'—')+memLine('Férias proporcionais',c[4]?c[4].textContent:'0/12')+memLine('Saldo prov. anterior',c[5]?c[5].textContent:money(0))+memLine('Provisão do mês',c[6]?c[6].textContent:money(base/12*4/3))+memLine('Ajuste no mês',c[7]?c[7].textContent:money(0))+memLine('Valor férias atual',c[8]?c[8].textContent:money(0))+memLine('1/3 férias atual',c[9]?c[9].textContent:money(0))+memLine('Gozadas identificadas',c[10]?c[10].textContent:money(0))+memLine('Indenizadas identificadas',c[11]?c[11].textContent:money(0))+memLine('Saldo atual',c[12]?c[12].textContent:money(0));
    enc+=memLine('INSS Empresa',c[13]?c[13].textContent:money(0))+memLine('RAT',c[14]?c[14].textContent:money(0))+memLine('Terceiros',c[15]?c[15].textContent:money(0))+memLine('FGTS',c[16]?c[16].textContent:money(0))+memLine('PIS',c[17]?c[17].textContent:money(0))+memLine('Custo provisionado',c[18]?c[18].textContent:money(0),'total');
  }
  var old=E('rh26-modal');if(old)old.remove();document.body.insertAdjacentHTML('beforeend','<div class="rh26-modal" id="rh26-modal"><div class="rh26-card"><button id="rh26-close">×</button><span class="eyebrow">MEMÓRIA DE CÁLCULO</span><h2>'+esc(name)+'</h2><p>'+esc(cc)+(dep?' · '+esc(dep):'')+'</p><div class="rh26-memory">'+html+'</div><h3>Encargos</h3><div class="rh26-memory">'+enc+'</div><p class="detail-note">Base remuneratória = salário vigente + verbas salariais recorrentes + médias variáveis aplicáveis. Valores históricos de salário não reduzem a base atual.</p></div></div>');var close=E('rh26-close');if(close)close.onclick=function(){var modal=E('rh26-modal');if(modal)modal.remove()}
}
async function enforceNow(){var page=E('page-planejamento');if(!page)return;if(typeof window.rhProvisionRefresh==='function')await window.rhProvisionRefresh();makeNameOnly('13');makeNameOnly('ferias');filterForecast();filterTerminationSelect();activeNote();if(typeof window.rhFitAllCardValues==='function')window.rhFitAllCardValues();if(typeof window.rhBaselineCheck==='function')window.rhBaselineCheck()}
function schedule(delay){clearTimeout(V.timer);V.timer=setTimeout(function(){Promise.resolve(typeof window.rhRosterLoad==='function'?window.rhRosterLoad(false):null).then(enforceNow).catch(function(e){console.warn('RH v38:',e)})},delay==null?35:delay)}
function styles(){if(E('_rh38'))return;var s=document.createElement('style');s.id='_rh38';s.textContent='\
#page-planejamento [data-plan-pane="13"] article.table-panel:has(table:not(.rh26-wide)),#page-planejamento [data-plan-pane="ferias"] article.table-panel:has(table:not(.rh26-wide)){display:none!important}\
#page-planejamento [data-plan-pane="13"] .rh30-scroll-note,#page-planejamento [data-plan-pane="ferias"] .rh30-scroll-note,#page-planejamento [data-plan-pane="13"] .rh30-group-head,#page-planejamento [data-plan-pane="ferias"] .rh30-group-head{display:none!important}\
#page-planejamento [data-plan-pane="13"] table.rh26-wide,#page-planejamento [data-plan-pane="ferias"] table.rh26-wide{min-width:0!important;width:100%!important;table-layout:auto!important;border-collapse:separate!important;border-spacing:0!important}\
#page-planejamento [data-plan-pane="13"] table.rh26-wide th:not(:first-child),#page-planejamento [data-plan-pane="13"] table.rh26-wide td:not(:first-child),#page-planejamento [data-plan-pane="13"] table.rh26-wide tfoot,#page-planejamento [data-plan-pane="ferias"] table.rh26-wide th:not(:first-child),#page-planejamento [data-plan-pane="ferias"] table.rh26-wide td:not(:first-child),#page-planejamento [data-plan-pane="ferias"] table.rh26-wide tfoot{display:none!important}\
#page-planejamento [data-plan-pane="13"] table.rh26-wide th:first-child,#page-planejamento [data-plan-pane="13"] table.rh26-wide td:first-child,#page-planejamento [data-plan-pane="ferias"] table.rh26-wide th:first-child,#page-planejamento [data-plan-pane="ferias"] table.rh26-wide td:first-child{position:relative!important;left:auto!important;width:100%!important;min-width:0!important;max-width:none!important;white-space:normal!important;box-shadow:none!important}\
#page-planejamento [data-plan-pane="13"] table.rh26-wide tbody td:first-child,#page-planejamento [data-plan-pane="ferias"] table.rh26-wide tbody td:first-child{padding:15px 48px 15px 18px!important;background:transparent!important}\
#page-planejamento [data-plan-pane="13"] table.rh26-wide tbody td:first-child small,#page-planejamento [data-plan-pane="ferias"] table.rh26-wide tbody td:first-child small{display:none!important}\
#page-planejamento [data-plan-pane="13"] table.rh26-wide tbody td:first-child:after,#page-planejamento [data-plan-pane="ferias"] table.rh26-wide tbody td:first-child:after{content:"›";position:absolute;right:20px;top:50%;transform:translateY(-50%);font-size:1.5rem;font-weight:900;color:var(--gold)}\
#page-planejamento [data-plan-pane="13"] .table-wrap:has(table.rh26-wide),#page-planejamento [data-plan-pane="ferias"] .table-wrap:has(table.rh26-wide){overflow:visible!important;padding-bottom:0!important}\
#rh38-active-note{display:block;margin-left:10px;color:var(--text);font-weight:750}\
#rh26-modal .rh38-base-total{border-color:color-mix(in srgb,var(--gold) 55%,transparent)!important;background:color-mix(in srgb,var(--gold) 7%,transparent)!important}\
#rh26-modal .rh38-base-total span,#rh26-modal .rh38-base-total b{color:var(--gold)!important}\
';document.head.appendChild(s)}
function init(){styles();schedule(0);document.addEventListener('click',function(e){if(!e.target||!e.target.closest)return;var tr=e.target.closest('#page-planejamento .rh38-name-list tbody tr.rh26-row');if(tr){e.preventDefault();e.stopImmediatePropagation();rhProvisionOpenMemory(tr).catch(function(err){console.warn('RH memória provisão:',err)});return}if(e.target.closest('#page-planejamento [data-plan-tab]'))schedule(0)},true);var old=window.renderAll;if(typeof old==='function'&&!old._rh38){var wrapped=function(){var r=old.apply(this,arguments);schedule(0);return r};wrapped._rh38=1;window.renderAll=wrapped}}
window.rhV38LoadRoster=function(){return typeof window.rhRosterLoad==='function'?window.rhRosterLoad(false):Promise.resolve(null)};window.rhV38EnforcePlanningUI=function(){schedule(0)};window.rhProvisionOpenMemory=rhProvisionOpenMemory;
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
