/* RH & Folha — hotfix v8 consolidado: contraste, filtros globais Departamento/Vínculo, Esc e Custo Real */

var RH_SCOPE=window.__lnbRhScopeState||(window.__lnbRhScopeState={dept:'',vinculo:''});

chartColors=function(){
  var css=getComputedStyle(document.body),root=getComputedStyle(document.documentElement);
  function v(name,fallback){return (css.getPropertyValue(name)||root.getPropertyValue(name)||fallback||'').trim();}
  return {text:v('--chart-text',document.body.classList.contains('light')?'#102f49':'#e7eef7'),grid:v('--chart-grid',document.body.classList.contains('light')?'rgba(18,49,76,.22)':'rgba(187,205,225,.16)'),gold:v('--gold','#e8b93c'),emerald:v('--emerald','#1fc48d'),red:v('--red','#e53945'),blue:v('--blue','#347fd1'),orange:v('--orange','#d56a12'),purple:v('--purple','#7651c9')};
};

function rhScopeDeptOptions(){
  var seen={},out=[];
  S.pessoas.forEach(function(p){var raw=String(p.departamento==null?'':p.departamento),label=departmentName(p.departamento);if(!raw||seen[raw])return;seen[raw]=1;out.push({value:raw,label:label});});
  return out.sort(function(a,b){return a.label.localeCompare(b.label,'pt-BR',{sensitivity:'base'});});
}
function rhScopePeople(){
  return S.pessoas.filter(function(p){
    if(RH_SCOPE.dept&&String(p.departamento)!==String(RH_SCOPE.dept))return false;
    if(RH_SCOPE.vinculo&&rhVinculoCategory(p)!==RH_SCOPE.vinculo)return false;
    return true;
  });
}
filteredPessoas=function(){return rhScopePeople();};
function rhScopeTotals(rows){var t={proventos:0,descontos:0,liquido:0,fgts:0};(rows||[]).forEach(function(p){t.proventos+=Number(p.proventos)||0;t.descontos+=Number(p.descontos)||0;t.liquido+=Number(p.liquido)||0;t.fgts+=Number(p.valor_fgts)||0;});return t;}
function rhScopeVincCounts(rows){var v={clt:0,estagiario:0,outros:0};(rows||[]).forEach(function(p){var k=rhVinculoCategory(p);v[k]=(v[k]||0)+1;});return v;}
function rhScopeDepartments(rows){var m={};(rows||rhScopePeople()).forEach(function(p){var k=departmentName(p.departamento);if(!m[k])m[k]={nome:k,proventos:0,descontos:0,liquido:0};m[k].proventos+=Number(p.proventos)||0;m[k].descontos+=Number(p.descontos)||0;m[k].liquido+=Number(p.liquido)||0;});return Object.keys(m).map(function(k){return m[k];}).sort(function(a,b){return b.liquido-a.liquido;});}
departments=function(){return rhScopeDepartments();};
function rhScopeRubrics(rows){var map={};(rows||rhScopePeople()).forEach(function(p){(p.lancamentos||[]).forEach(function(x){var k=(x.rubrica_codigo||'')+'|'+(x.rubrica_nome||'')+'|'+(x.tipo||'');if(!map[k])map[k]={codigo:x.rubrica_codigo,nome:x.rubrica_nome,tipo:x.tipo,valor:0};map[k].valor+=Number(x.valor)||0;});});return Object.keys(map).map(function(k){return map[k];}).sort(function(a,b){return b.valor-a.valor;});}

function rhDeptOptionsHtml(){return '<option value="">Todos os departamentos</option>'+rhScopeDeptOptions().map(function(o){return '<option value="'+esc(o.value)+'">'+esc(o.label)+'</option>';}).join('');}
function rhVincOptionsHtml(){return '<option value="">Todos os vínculos</option><option value="clt">CLT</option><option value="estagiario">Estagiário</option><option value="outros">Outros</option>';}
function rhSetScope(dept,vinc){RH_SCOPE.dept=dept||'';RH_SCOPE.vinculo=vinc||'';rhSyncScopeControls();rhRefreshScope();}
function rhSyncScopeControls(){
  var md=$('filter-dept'),mv=$('filter-vinculo');if(md)md.value=RH_SCOPE.dept;if(mv)mv.value=RH_SCOPE.vinculo;
  document.querySelectorAll('[data-rh-scope-dept]').forEach(function(s){s.value=RH_SCOPE.dept;});
  document.querySelectorAll('[data-rh-scope-vinc]').forEach(function(s){s.value=RH_SCOPE.vinculo;});
}
function rhPopulateScopeControls(){
  var dh=rhDeptOptionsHtml(),vh=rhVincOptionsHtml(),md=$('filter-dept'),mv=$('filter-vinculo');
  if(md){md.innerHTML=dh;md.value=RH_SCOPE.dept;}if(mv){mv.innerHTML=vh;mv.value=RH_SCOPE.vinculo;}
  document.querySelectorAll('[data-rh-scope-dept]').forEach(function(s){s.innerHTML=dh;s.value=RH_SCOPE.dept;});
  document.querySelectorAll('[data-rh-scope-vinc]').forEach(function(s){s.innerHTML=vh;s.value=RH_SCOPE.vinculo;});
}
function rhCreateScreenFilters(pageId){
  var page=$(pageId);if(!page)return;var head=page.querySelector('.page-head');if(!head)return;
  var actions=head.querySelector('.head-actions');if(!actions){actions=document.createElement('div');actions.className='head-actions';head.appendChild(actions);}
  var key=pageId.replace('page-','');
  if(!page.querySelector('[data-rh-scope-dept]')){var ld=document.createElement('label');ld.className='rh-scope-label';ld.innerHTML='Departamento<select id="rh-scope-dept-'+key+'" data-rh-scope-dept></select>';actions.insertBefore(ld,actions.firstChild);}
  if(!page.querySelector('[data-rh-scope-vinc]')){var lv=document.createElement('label');lv.className='rh-scope-label';lv.innerHTML='Vínculo<select id="rh-scope-vinc-'+key+'" data-rh-scope-vinc></select>';actions.insertBefore(lv,actions.firstChild);}
}
function rhEnsureScopeFilters(){
  ['page-visao','page-colaboradores','page-folha','page-rubricas','page-encargos','page-movimentacoes','page-rateio','page-custoreal'].forEach(rhCreateScreenFilters);
  var legacy=$('painel-filters');if(legacy)legacy.remove();
  var old=document.querySelector('.payroll-vinculo-bar');if(old)old.remove();
  rhPopulateScopeControls();
  var md=$('filter-dept'),mv=$('filter-vinculo');
  if(md)md.onchange=function(){RH_SCOPE.dept=md.value||'';rhSyncScopeControls();rhRefreshScope();};
  if(mv)mv.onchange=function(){RH_SCOPE.vinculo=mv.value||'';rhSyncScopeControls();rhRefreshScope();};
  document.querySelectorAll('[data-rh-scope-dept]').forEach(function(s){s.onchange=function(){RH_SCOPE.dept=s.value||'';rhSyncScopeControls();rhRefreshScope();};});
  document.querySelectorAll('[data-rh-scope-vinc]').forEach(function(s){s.onchange=function(){RH_SCOPE.vinculo=s.value||'';rhSyncScopeControls();rhRefreshScope();};});
  var reset=$('filter-reset');if(reset)reset.onclick=function(){RH_SCOPE.dept='';RH_SCOPE.vinculo='';rhSyncScopeControls();rhRefreshScope();};
}
function rhRefreshScope(){
  try{renderKpis();renderPeople();renderPayroll();renderRubrics();renderCharges();renderMovements();renderDepartments();renderCharts();renderCustoReal();}catch(e){console.error('Falha ao aplicar filtros globais do RH',e);}
}

renderKpis=function(){
  if(!S.competencia)return;var rows=rhScopePeople(),t=rhScopeTotals(rows),v=rhScopeVincCounts(rows);
  if($('kpi-proventos'))$('kpi-proventos').textContent=fmt(t.proventos);if($('kpi-descontos'))$('kpi-descontos').textContent=fmt(t.descontos);if($('kpi-liquido'))$('kpi-liquido').textContent=fmt(t.liquido);if($('kpi-pessoas'))$('kpi-pessoas').textContent=nfmt(rows.length);if($('kpi-vinculos'))$('kpi-vinculos').textContent=v.clt+' CLT · '+v.estagiario+' Estagiários · '+v.outros+' Outros';
  if($('payroll-kpis'))$('payroll-kpis').innerHTML=[['Proventos',t.proventos],['Descontos',t.descontos],['Líquido',t.liquido],['FGTS',t.fgts]].map(function(x){return '<div class="kpi"><span>'+x[0]+'</span><strong>'+fmt(x[1])+'</strong><small>'+formatCompetence(S.competencia.competencia)+'</small></div>';}).join('');
  if(typeof rhBindOverviewCards==='function')rhBindOverviewCards();
};

renderPayroll=function(){
  if(!$('payroll-rows'))return;var rows=rhScopePeople().slice().sort(function(a,b){return String(a.nome||'').localeCompare(String(b.nome||''),'pt-BR',{sensitivity:'base'});});
  $('payroll-rows').innerHTML=rows.length?rows.map(function(p){return '<tr><td><b>'+esc(p.nome)+'</b><br><small>'+esc(departmentName(p.departamento))+'</small></td><td class="money">'+fmt(p.salario)+'</td><td class="money">'+fmt(p.proventos)+'</td><td class="money">'+fmt(p.descontos)+'</td><td class="money"><b>'+fmt(p.liquido)+'</b></td><td><button class="detail-button" data-person="'+esc(p.id)+'">Detalhar</button></td></tr>';}).join(''):emptyRow(6,'Nenhum colaborador para os filtros selecionados.');bindPersonButtons();
};

renderRubrics=function(){
  if(!$('rubric-rows'))return;var a=rhScopeRubrics();$('rubric-rows').innerHTML=a.length?a.map(function(x,i){return '<tr class="detail-clickable" data-rh-rubric="'+i+'"><td>'+esc(x.codigo||'—')+'</td><td><b>'+esc(rhFixTextValue(x.nome))+'</b><small class="click-hint">Clique para ver a composição</small></td><td><span class="status">'+esc(x.tipo)+'</span></td><td class="money">'+fmt(x.valor)+'</td></tr>';}).join(''):emptyRow(4,'Sem rubricas para os filtros selecionados.');document.querySelectorAll('[data-rh-rubric]').forEach(function(tr){tr.onclick=function(){openRubricBreakdown(a[Number(tr.dataset.rhRubric)]);};});
};
openRubricBreakdown=function(x){if(!x)return;var rows=[];rhScopePeople().forEach(function(p){var val=(p.lancamentos||[]).filter(function(l){return String(l.rubrica_codigo||'')===String(x.codigo||'')&&String(l.rubrica_nome||'')===String(x.nome||'')&&String(l.tipo||'')===String(x.tipo||'');}).reduce(function(a,l){return a+(Number(l.valor)||0);},0);if(val)rows.push({nome:p.nome,dep:departmentName(p.departamento),cc:p.centro_custo||'Sem centro de custo',valor:val});});rows.sort(function(a,b){return b.valor-a.valor;});var total=rows.reduce(function(a,r){return a+r.valor;},0);openGenericDetail(x.nome||'Rubrica','COMPOSIÇÃO E RATEIO DA RUBRICA',rows.length?'<table class="modal-table-inner responsive-table" data-rh-authoritative-composition="1"><thead><tr><th>Colaborador</th><th>Departamento</th><th>Centro de custo</th><th class="money">Valor</th><th class="money">% do total</th></tr></thead><tbody>'+rows.map(function(r){return '<tr><td>'+esc(r.nome)+'</td><td>'+esc(r.dep)+'</td><td>'+esc(r.cc)+'</td><td class="money">'+fmt(r.valor)+'</td><td class="money">'+(total?r.valor/total*100:0).toFixed(2).replace('.',',')+'%</td></tr>';}).join('')+'</tbody>'+rhFoot(['TOTAL','','',fmt(total),'100,00%'])+'</table>':'<p class="detail-empty">Sem composição para os filtros selecionados.</p>');};

renderDepartments=function(){
  if(!$('department-rows'))return;var a=rhScopeDepartments();$('department-rows').innerHTML=a.length?a.map(function(x,i){return '<tr class="detail-clickable" data-rh-dept-row="'+i+'"><td><b>'+esc(x.nome)+'</b></td><td class="money">'+fmt(x.proventos)+'</td><td class="money">'+fmt(x.descontos)+'</td><td class="money">'+fmt(x.liquido)+'</td></tr>';}).join(''):emptyRow(4,'Sem rateio para os filtros selecionados.');document.querySelectorAll('[data-rh-dept-row]').forEach(function(tr){tr.onclick=function(){openDepartmentBreakdown(a[Number(tr.dataset.rhDeptRow)].nome);};});
};
openDepartmentBreakdown=function(nome){var key=rhDeptKey(nome),rows=rhScopePeople().filter(function(p){return rhDeptKey(departmentName(p.departamento))===key;}).sort(function(a,b){return (Number(b.proventos)||0)-(Number(a.proventos)||0);}),t=rhScopeTotals(rows);openGenericDetail(nome,'COMPOSIÇÃO E RATEIO DO DEPARTAMENTO',rows.length?'<table class="modal-table-inner responsive-table" data-rh-authoritative-composition="1"><thead><tr><th>Colaborador</th><th>Centro de custo</th><th class="money">Proventos</th><th class="money">Descontos</th><th class="money">Líquido</th><th class="money">% do líquido</th></tr></thead><tbody>'+rows.map(function(p){return '<tr><td>'+esc(p.nome)+'</td><td>'+esc(p.centro_custo||'Sem centro de custo')+'</td><td class="money">'+fmt(p.proventos)+'</td><td class="money">'+fmt(p.descontos)+'</td><td class="money">'+fmt(p.liquido)+'</td><td class="money">'+(t.liquido?(Number(p.liquido)||0)/t.liquido*100:0).toFixed(2).replace('.',',')+'%</td></tr>';}).join('')+'</tbody>'+rhFoot(['TOTAL','',fmt(t.proventos),fmt(t.descontos),fmt(t.liquido),'100,00%'])+'</table>':'<p class="detail-empty">Nenhum colaborador para os filtros selecionados.</p>');};

function rhScopedCharges(){
  var rows=rhScopePeople(),e=(S.competencia&&S.competencia.encargos)||{},allBase=S.pessoas.reduce(function(a,p){return a+(Number(p.base_inss)||0);},0),selBase=rows.reduce(function(a,p){return a+(Number(p.base_inss)||0);},0),baseTotal=Number(e.base_total_inss)||0,pat=baseTotal*0.20,rat=Number(e.rat)||(baseTotal*0.01),ter=Number(e.terceiros)||(baseTotal*0.058),official=Number(e.total_inss)||0,retAll=Math.max(0,official-pat-rat-ter),ratio=allBase>0?selBase/allBase:0,inss=retAll*ratio,fgts=0,pis=0,irrf=0;
  rows.forEach(function(p){fgts+=Number(p.valor_fgts)||0;pis+=Number(rhPisForPerson(p))||0;irrf+=Number(p.valor_irrf)||0;rhEmployerCharges(p).itens.forEach(function(it){var k=cleanSearch(it[0]);if(k.indexOf('inss patronal')>=0||k==='rat'||k.indexOf('terceiros')>=0)inss+=Number(it[1])||0;});});
  if(!irrf&&Number(e.valor_irrf_folha||e.valor_irrf)>0){var allI=S.pessoas.reduce(function(a,p){return a+(Number(p.base_irrf)||0);},0),selI=rows.reduce(function(a,p){return a+(Number(p.base_irrf)||0);},0);irrf=Number(e.valor_irrf_folha||e.valor_irrf)*(allI>0?selI/allI:0);}
  return {rows:rows,inss:inss,fgts:fgts,pis:pis,irrf:irrf,total:inss+fgts+pis+irrf,baseInss:selBase,retAll:retAll,allBase:allBase};
}
chargeData=function(){var c=rhScopedCharges();return [['INSS total',c.inss],['FGTS',c.fgts],['PIS',c.pis],['IRRF folha',c.irrf]];};
renderCharges=function(){
  if(!$('charges-kpis')||!$('charge-list'))return;var a=chargeData(),total=a.reduce(function(s,x){return s+(Number(x[1])||0);},0),handlers=[openInssBreakdown,openFgtsBreakdown,openPisBreakdown,openIrrfBreakdown];
  $('charge-list').innerHTML=a.map(function(x,i){return '<button class="metric-row clickable" data-rh-charge="'+i+'"><span>'+x[0]+'</span><strong>'+fmt(x[1])+'</strong><small>clique para detalhar</small></button>';}).join('')+'<div class="metric-row"><span><b>Total recolhimentos</b></span><strong>'+fmt(total)+'</strong></div>';
  $('charges-kpis').innerHTML=a.map(function(x,i){return '<button class="kpi clickable" data-rh-charge="'+i+'"><span>'+x[0]+'</span><strong>'+fmt(x[1])+'</strong><small>clique para detalhar</small></button>';}).join('')+'<div class="kpi featured"><span>Total recolhimentos</span><strong>'+fmt(total)+'</strong></div>';
  document.querySelectorAll('[data-rh-charge]').forEach(function(b){b.onclick=function(){var fn=handlers[Number(b.dataset.rhCharge)];if(fn)fn();};});
};

openInssBreakdown=function(){
  var modal=$('inss-modal');if(!modal)return;var sc=rhScopedCharges(),rows=sc.rows.filter(function(p){return Number(p.base_inss)>0;}),scopeBase=rows.reduce(function(a,p){return a+(Number(p.base_inss)||0);},0),retScope=sc.retAll*(sc.allBase>0?sc.baseInss/sc.allBase:0),tp=0,tr=0,tt=0,tret=0;
  var body=rows.map(function(p){var base=Number(p.base_inss)||0,shareScope=scopeBase>0?base/scopeBase:0,ret=retScope*shareScope,pp=0,rr=0,te=0;rhEmployerCharges(p).itens.forEach(function(it){var k=cleanSearch(it[0]);if(k.indexOf('inss patronal')>=0)pp+=Number(it[1])||0;else if(k==='rat')rr+=Number(it[1])||0;else if(k.indexOf('terceiros')>=0)te+=Number(it[1])||0;});tret+=ret;tp+=pp;tr+=rr;tt+=te;return '<tr><td>'+esc(p.nome)+'</td><td>'+esc(departmentName(p.departamento))+'</td><td>'+esc(p.centro_custo||'Sem centro de custo')+'</td><td class="money">'+fmt(base)+'</td><td class="money">'+fmt(ret)+'</td><td class="money">'+fmt(pp)+'</td><td class="money">'+fmt(rr)+'</td><td class="money">'+fmt(te)+'</td></tr>';}).join('');
  modal.querySelector('.im-total-inss').textContent=fmt(sc.inss);modal.querySelector('.im-base').textContent=fmt(scopeBase);modal.querySelector('.im-body').innerHTML='<table class="modal-table-inner responsive-table" data-rh-authoritative-composition="1"><thead><tr><th>Colaborador</th><th>Departamento</th><th>Centro de custo</th><th class="money">Base</th><th class="money">Retido</th><th class="money">Patronal</th><th class="money">RAT</th><th class="money">Terceiros</th></tr></thead><tbody>'+body+'</tbody>'+rhFoot(['TOTAL','','',fmt(scopeBase),fmt(tret),fmt(tp),fmt(tr),fmt(tt)])+'</table>';modal.hidden=false;rhSweepText(modal);
};window._openInss=function(){openInssBreakdown();};
openFgtsBreakdown=function(){var modal=$('fgts-modal');if(!modal)return;var rows=rhScopePeople().filter(function(p){return Number(p.valor_fgts)>0;}),tb=rows.reduce(function(a,p){return a+(Number(p.base_fgts)||0);},0),tv=rows.reduce(function(a,p){return a+(Number(p.valor_fgts)||0);},0);modal.querySelector('.fgts-total').textContent=fmt(tv);modal.querySelector('.fgts-base').textContent=fmt(tb);modal.querySelector('.fgts-body').innerHTML='<table class="modal-table-inner responsive-table" data-rh-authoritative-composition="1"><thead><tr><th>Colaborador</th><th>Departamento</th><th>Centro de custo</th><th class="money">Base FGTS</th><th class="money">FGTS pago</th></tr></thead><tbody>'+rows.map(function(p){return '<tr><td>'+esc(p.nome)+'</td><td>'+esc(departmentName(p.departamento))+'</td><td>'+esc(p.centro_custo||'Sem centro de custo')+'</td><td class="money">'+fmt(p.base_fgts)+'</td><td class="money">'+fmt(p.valor_fgts)+'</td></tr>';}).join('')+'</tbody>'+rhFoot(['TOTAL','','',fmt(tb),fmt(tv)])+'</table>';modal.hidden=false;};window._openFgts=function(){openFgtsBreakdown();};
openPisBreakdown=function(){var rows=rhScopePeople().filter(function(p){return Number(p.base_fgts)>0;}),tb=0,tp=0;var body=rows.map(function(p){var v=Number(rhPisForPerson(p))||0;tb+=Number(p.base_fgts)||0;tp+=v;return '<tr><td>'+esc(p.nome)+'</td><td>'+esc(departmentName(p.departamento))+'</td><td>'+esc(p.centro_custo||'Sem centro de custo')+'</td><td class="money">'+fmt(p.base_fgts)+'</td><td class="money">'+fmt(v)+'</td></tr>';}).join('');openGenericDetail('PIS por Colaborador','DETALHAMENTO PIS','<table class="modal-table-inner responsive-table" data-rh-authoritative-composition="1"><thead><tr><th>Colaborador</th><th>Departamento</th><th>Centro de custo</th><th class="money">Base PIS</th><th class="money">PIS atribuído</th></tr></thead><tbody>'+body+'</tbody>'+rhFoot(['TOTAL','','',fmt(tb),fmt(tp)])+'</table>');};window._openPis=function(){openPisBreakdown();};
openIrrfBreakdown=function(){var modal=$('irrf-modal');if(!modal)return;var rows=rhScopePeople().filter(function(p){return Number(p.base_irrf)>0||Number(p.valor_irrf)>0;}).map(function(p){var b=Number(p.base_irrf)||0,c=calcIrrf(b),f=Number(p.valor_irrf)||0;return {p:p,n:p.nome,b:b,c:c,f:f,d:c-f};}),tb=0,tc=0,tf=0,td=0;rows.forEach(function(r){tb+=r.b;tc+=r.c;tf+=r.f;td+=r.d;});modal.querySelector('.irrf-total-folha').textContent=fmt(tf);modal.querySelector('.irrf-total-calc').textContent=fmt(tc);modal.querySelector('.irrf-body').innerHTML='<div class="irrf-official-note">Composição restrita aos filtros selecionados. RPA permanece fora desta etapa.</div><table class="modal-table-inner responsive-table" data-rh-authoritative-composition="1"><thead><tr><th>Colaborador</th><th>Departamento</th><th>Centro de custo</th><th class="money">Base IRRF</th><th class="money">Calculado</th><th class="money">Folha</th><th class="money">Dif.</th></tr></thead><tbody>'+rows.map(function(r){return '<tr><td>'+esc(r.n)+'</td><td>'+esc(departmentName(r.p.departamento))+'</td><td>'+esc(r.p.centro_custo||'Sem centro de custo')+'</td><td class="money">'+fmt(r.b)+'</td><td class="money">'+fmt(r.c)+'</td><td class="money">'+fmt(r.f)+'</td><td class="money">'+fmt(r.d)+'</td></tr>';}).join('')+'</tbody>'+rhFoot(['TOTAL','','',fmt(tb),fmt(tc),fmt(tf),fmt(td)])+'</table>';modal.hidden=false;};window._openIrrf=function(){openIrrfBreakdown();};

openMetricBreakdown=function(metric){var labels={proventos:'Proventos',descontos:'Descontos',liquido:'Líquido'},rows=rhScopePeople().filter(function(p){return Number(p[metric])!==0;}).sort(function(a,b){return (Number(b[metric])||0)-(Number(a[metric])||0);}),total=rows.reduce(function(a,p){return a+(Number(p[metric])||0);},0);openGenericDetail(labels[metric]||metric,'COMPOSIÇÃO E RATEIO POR COLABORADOR','<table class="modal-table-inner responsive-table" data-rh-authoritative-composition="1"><thead><tr><th>Colaborador</th><th>Departamento</th><th>Centro de custo</th><th class="money">Valor</th><th class="money">% do total</th></tr></thead><tbody>'+rows.map(function(p){var v=Number(p[metric])||0;return '<tr><td>'+esc(p.nome)+'</td><td>'+esc(departmentName(p.departamento))+'</td><td>'+esc(p.centro_custo||'Sem centro de custo')+'</td><td class="money">'+fmt(v)+'</td><td class="money">'+(total?v/total*100:0).toFixed(2).replace('.',',')+'%</td></tr>';}).join('')+'</tbody>'+rhFoot(['TOTAL','','',fmt(total),'100,00%'])+'</table>');};
openVinculoBreakdown=function(kind){var target=kind==='CLT'?'clt':kind==='Estagiários'?'estagiario':'outros',rows=rhScopePeople().filter(function(p){return rhVinculoCategory(p)===target;}),total=rows.reduce(function(a,p){return a+(Number(p.liquido)||0);},0);openGenericDetail(kind,'COLABORADORES POR VÍNCULO','<table class="modal-table-inner responsive-table"><thead><tr><th>Colaborador</th><th>Departamento</th><th class="money">Líquido</th></tr></thead><tbody>'+rows.map(function(p){return '<tr><td>'+esc(p.nome)+'</td><td>'+esc(departmentName(p.departamento))+'</td><td class="money">'+fmt(p.liquido)+'</td></tr>';}).join('')+'</tbody>'+rhFoot(['TOTAL ('+rows.length+' pessoas)','',fmt(total)])+'</table>');};
rhOpenPeopleOverview=function(){var rows=rhScopePeople().slice().sort(function(a,b){return String(a.nome||'').localeCompare(String(b.nome||''),'pt-BR',{sensitivity:'base'});});openGenericDetail('Pessoas na Folha','COMPOSIÇÃO DO QUADRO','<table class="modal-table-inner responsive-table"><thead><tr><th>Colaborador</th><th>Vínculo</th><th>Departamento</th></tr></thead><tbody>'+rows.map(function(p){return '<tr><td>'+esc(p.nome)+'</td><td>'+esc(p.vinculo||'—')+'</td><td>'+esc(departmentName(p.departamento))+'</td></tr>';}).join('')+'</tbody><tfoot><tr class="detail-total-row"><td><b>TOTAL</b></td><td><b>'+nfmt(rows.length)+' pessoas</b></td><td></td></tr></tfoot></table>');};

renderMovements=function(){if(!$('movement-rows'))return;var rows=rhScopePeople(),moves=rows.filter(function(p){return /demit/i.test(p.situacao||'')||(p.admissao||'').slice(0,7)===S.competencia.competencia.slice(0,7);}),ad=moves.filter(function(p){return !/demit/i.test(p.situacao||'');}).length,de=moves.filter(function(p){return /demit/i.test(p.situacao||'');}).length,fe=rows.filter(function(p){return /ferias|férias/i.test(p.situacao||'');}).length,tr=Math.max(0,rows.length-de-fe);if($('movement-kpis'))$('movement-kpis').innerHTML=[['Admissões',ad],['Desligamentos',de],['Em férias',fe],['Trabalhando',tr]].map(function(x){return '<div class="kpi"><span>'+x[0]+'</span><strong>'+nfmt(x[1])+'</strong><small>Nos filtros atuais</small></div>';}).join('');$('movement-rows').innerHTML=moves.length?moves.map(function(p){var dem=/demit/i.test(p.situacao||'');return '<tr><td>'+esc(p.nome)+'</td><td><span class="status '+(dem?'danger':'success')+'">'+(dem?'Desligamento':'Admissão')+'</span></td><td>'+esc(dem?'Na competência':dateBR(p.admissao))+'</td><td>'+esc(departmentName(p.departamento))+'</td></tr>';}).join(''):emptyRow(4,'Nenhuma movimentação nos filtros selecionados.');};

renderCharts=function(){
  if(!S.competencia||!window.Chart)return;var c=chartColors(),rows=rhScopePeople(),t=rhScopeTotals(rows),d=rhScopeDepartments(rows),v=rhScopeVincCounts(rows),rub=rhScopeRubrics(rows).slice(0,10),charges=chargeData();
  chart('chart-composicao','bar',{labels:['Proventos','Descontos','Líquido'],datasets:[{label:'Valor',data:[t.proventos,t.descontos,t.liquido],backgroundColor:[c.gold,c.red,c.emerald],borderRadius:8}]},{plugins:{legend:{display:false}}},function(e,x){if(x.length)openMetricBreakdown(['proventos','descontos','liquido'][x[0].index]);});
  chart('chart-departamentos','bar',{labels:d.map(function(x){return x.nome;}),datasets:[{label:'Líquido',data:d.map(function(x){return x.liquido;}),backgroundColor:c.emerald,borderRadius:7}]},{indexAxis:'y',plugins:{legend:{display:false}}},function(e,x){if(x.length)openDepartmentBreakdown(d[x[0].index].nome);});
  chart('chart-vinculos','doughnut',{labels:['CLT · '+v.clt,'Estagiários · '+v.estagiario,'Outros · '+v.outros],datasets:[{data:[v.clt,v.estagiario,v.outros],backgroundColor:[c.blue,c.gold,c.purple],borderColor:getComputedStyle(document.body).getPropertyValue('--surface'),borderWidth:3}]},{cutout:'66%',plugins:{legend:{position:'bottom'}}},function(e,x){if(x.length)openVinculoBreakdown(['CLT','Estagiários','Outros'][x[0].index]);});
  chart('chart-rubricas','bar',{labels:rub.map(function(x){return rhFixTextValue(x.nome);}),datasets:[{label:'Valor',data:rub.map(function(x){return x.valor;}),backgroundColor:rub.map(function(x){return x.tipo==='D'||x.tipo==='desconto'?c.red:c.gold;})}]},{indexAxis:'y',plugins:{legend:{display:false}}},function(e,x){if(x.length)openRubricBreakdown(rub[x[0].index]);});
  chart('chart-encargos','bar',{labels:charges.map(function(x){return x[0];}),datasets:[{label:'Valor',data:charges.map(function(x){return Number(x[1])||0;}),backgroundColor:[c.blue,c.gold,c.emerald,c.purple]}]},{plugins:{legend:{display:false}}},function(e,x){if(!x.length)return;[openInssBreakdown,openFgtsBreakdown,openPisBreakdown,openIrrfBreakdown][x[0].index]();});
  chart('chart-rateio','bar',{labels:d.map(function(x){return x.nome;}),datasets:[{label:'Proventos',data:d.map(function(x){return x.proventos;}),backgroundColor:c.gold},{label:'Descontos',data:d.map(function(x){return x.descontos;}),backgroundColor:c.red},{label:'Líquido',data:d.map(function(x){return x.liquido;}),backgroundColor:c.emerald}]},{indexAxis:'y'},function(e,x){if(x.length)openDepartmentBreakdown(d[x[0].index].nome);});
  ['chart-composicao','chart-departamentos','chart-vinculos','chart-rubricas','chart-encargos','chart-rateio'].forEach(function(id){if($(id))$(id).style.cursor='pointer';});
};

rhCostTotals=function(){var t={proventos:0,fgts:0,inss:0,rat:0,terceiros:0,pis:0,beneficios:0,total:0};rhScopePeople().forEach(function(p){t.proventos+=Number(p.proventos)||0;rhEmployerCharges(p).itens.forEach(function(it){var k=cleanSearch(it[0]),v=Number(it[1])||0;if(k==='fgts')t.fgts+=v;else if(k.indexOf('inss patronal')>=0)t.inss+=v;else if(k==='rat')t.rat+=v;else if(k.indexOf('terceiros')>=0)t.terceiros+=v;else if(k==='pis')t.pis+=v;});var c=custoEmpresa(p);c.itens.forEach(function(it){if(it[2]==='benefício')t.beneficios+=Number(it[1])||0;});t.total+=c.total;});return t;};
rhOpenBenefits=function(){var rows=[],ts=0,tm=0,tvr=0,tvt=0,tt=0,vrAvailable=false;rhScopePeople().forEach(function(p){var b=rhPersonBenefit(p);if(!b)return;var s=Number(b.seguro_vida)||0,m=Number(b.assistencia_medica||b.assist_medica)||0,vr=Number(b.vr_caixa)||0,vt=Number(b.vale_transporte)||0,t=s+m+vr+vt;if(b.vr_valor_disponivel||vr>0)vrAvailable=true;if(t>0)rows.push({nome:p.nome,seg:s,med:m,vr:vr,vt:vt,total:t});ts+=s;tm+=m;tvr+=vr;tvt+=vt;tt+=t;});rows.sort(function(a,b){return b.total-a.total;});var html='<table class="modal-table-inner responsive-table benefit-detail-table"><thead><tr><th>Colaborador</th><th class="money">Seguro</th><th class="money">Saúde</th>'+(vrAvailable?'<th class="money">VR/VA/Cesta</th>':'')+'<th class="money">VT</th><th class="money">Total</th></tr></thead><tbody>'+rows.map(function(r){return '<tr><td>'+esc(r.nome)+'</td><td class="money">'+fmt(r.seg)+'</td><td class="money">'+fmt(r.med)+'</td>'+(vrAvailable?'<td class="money">'+fmt(r.vr)+'</td>':'')+'<td class="money">'+fmt(r.vt)+'</td><td class="money"><b>'+fmt(r.total)+'</b></td></tr>';}).join('')+'</tbody><tfoot><tr class="detail-total-row"><td><b>TOTAL</b></td><td class="money">'+fmt(ts)+'</td><td class="money">'+fmt(tm)+'</td>'+(vrAvailable?'<td class="money">'+fmt(tvr)+'</td>':'')+'<td class="money">'+fmt(tvt)+'</td><td class="money"><b>'+fmt(tt)+'</b></td></tr></tfoot></table>';openGenericDetail('Benefícios por Colaborador','COMPOSIÇÃO DOS BENEFÍCIOS',html);};

renderCustoReal=function(){
  if(!$('custo-real-rows')||!S.competencia)return;var rows=rhScopePeople().slice().sort(function(a,b){return custoEmpresa(b).total-custoEmpresa(a).total;}),hasBen=rows.some(function(p){var b=rhPersonBenefit(p);return b&&(Number(b.seguro_vida)||Number(b.assistencia_medica||b.assist_medica)||Number(b.vr_caixa)||Number(b.vale_transporte));}),tc=0,tp=0,tf=0,te=0,tb=0;
  rows.forEach(function(p){var c=custoEmpresa(p);tc+=c.total;tp+=Number(p.proventos)||0;rhEmployerCharges(p).itens.forEach(function(it){var k=cleanSearch(it[0]),v=Number(it[1])||0;if(k==='fgts')tf+=v;else te+=v;});c.itens.forEach(function(it){if(it[2]==='benefício')tb+=Number(it[1])||0;});});
  $('custo-real-kpis').innerHTML=[['Custo total LNB',tc],['Salários brutos',tp],['FGTS + Encargos patronais',tf+te]].concat(hasBen?[['Benefícios',tb]]:[]).map(function(x){return '<div class="kpi"><span>'+x[0]+'</span><strong>'+fmt(x[1])+'</strong><small>'+formatCompetence(S.competencia.competencia)+'</small></div>';}).join('');
  $('custo-real-head').innerHTML='<th>Colaborador</th><th class="money">Proventos</th><th class="money">FGTS</th><th class="money">Encargos patronais</th>'+(hasBen?'<th class="money">Benefícios</th>':'')+'<th class="money">Custo total</th>';
  $('custo-real-rows').innerHTML=rows.length?rows.map(function(p){var c=custoEmpresa(p),fg=0,enc=0,ben=0;rhEmployerCharges(p).itens.forEach(function(it){var k=cleanSearch(it[0]),v=Number(it[1])||0;if(k==='fgts')fg+=v;else enc+=v;});c.itens.forEach(function(it){if(it[2]==='benefício')ben+=Number(it[1])||0;});return '<tr><td><b>'+esc(p.nome)+'</b><small>'+esc(departmentName(p.departamento))+'</small></td><td class="money">'+fmt(p.proventos)+'</td><td class="money">'+fmt(fg)+'</td><td class="money">'+fmt(enc)+'</td>'+(hasBen?'<td class="money">'+fmt(ben)+'</td>':'')+'<td class="money"><b>'+fmt(c.total)+'</b></td></tr>';}).join('')+'<tr class="detail-total-row"><td><b>TOTAL</b></td><td class="money">'+fmt(tp)+'</td><td class="money">'+fmt(tf)+'</td><td class="money">'+fmt(te)+'</td>'+(hasBen?'<td class="money">'+fmt(tb)+'</td>':'')+'<td class="money"><b>'+fmt(tc)+'</b></td></tr>':emptyRow(hasBen?6:5,'Nenhum colaborador para os filtros selecionados.');
  if(window.Chart&&rows.length){var cc=chartColors(),top=rows.slice(0,15),ds=[{label:'Salários / Proventos',data:top.map(function(p){return Number(p.proventos)||0;}),backgroundColor:cc.blue},{label:'FGTS',data:top.map(function(p){return Number(p.valor_fgts)||0;}),backgroundColor:cc.gold},{label:'Encargos patronais',data:top.map(function(p){return Math.max(0,rhEmployerCharges(p).total-(Number(p.valor_fgts)||0));}),backgroundColor:cc.red}];if(hasBen)ds.push({label:'Benefícios',data:top.map(function(p){var b=0;custoEmpresa(p).itens.forEach(function(it){if(it[2]==='benefício')b+=Number(it[1])||0;});return b;}),backgroundColor:cc.purple});chart('chart-custo-real','bar',{labels:top.map(function(p){return p.nome.split(' ')[0];}),datasets:ds},{indexAxis:'y',scales:{x:{stacked:true},y:{stacked:true}}},function(e,x){if(x.length)openPerson(top[x[0].index].id);});}
  if(typeof rhBindCostCards==='function')rhBindCostCards();rhSweepText($('page-custoreal'));
};

var _rhV8BaseSetupUI=setupUI;
setupUI=function(){
  _rhV8BaseSetupUI();
  if(!$('_rh_hotfix_v8_styles')){var st=document.createElement('style');st.id='_rh_hotfix_v8_styles';st.textContent='body.light{--bg:#f4f7f9;--bg-2:#e9eff4;--surface:#fff;--surface-2:#edf3f7;--surface-soft:rgba(255,255,255,.98);--text:#071a2c;--muted:#29445d;--faint:#49657d;--line:rgba(118,82,5,.48);--line-soft:rgba(16,49,78,.24);--gold:#6e4a00;--gold-2:#765000;--emerald:#087451;--blue:#145fa7;--red:#b4232e;--orange:#9b4a00;--purple:#57349f;--chart-grid:rgba(18,49,76,.22);--chart-text:#102f49}body.light .topbar{background:rgba(244,247,249,.96)!important}body.light .sidebar{background:linear-gradient(180deg,#f8fafb,#eef3f6)!important}body.light .nav-item{color:#213d56!important}body.light .nav-item.active,body.light .nav-item:hover{color:#071a2c!important;background:#e3ebf1!important}body.light .page-head p,body.light .brand small,body.light .user-name,body.light .kpi span,body.light .kpi small,body.light .metric-row span,body.light .validation-row span,body.light .row-person small,body.light .sidebar-note span,body.light .click-hint,body.light .detail-note{color:#29445d!important}body.light .kpi,body.light .panel,body.light .table-panel{border-color:rgba(16,49,78,.22)!important;box-shadow:0 10px 28px rgba(22,52,78,.10)!important}body.light .kpi strong,body.light h1,body.light h2,body.light h3,body.light td,body.light .metric-row strong,body.light .detail-button,body.light .button{color:#071a2c!important}body.light th{background:#dce7ee!important;color:#173851!important;border-color:rgba(16,49,78,.24)!important;font-weight:900!important}body.light td{border-color:rgba(16,49,78,.18)!important}body.light tbody tr:hover{background:#e4edf3!important}body.light .head-actions label{color:#29445d!important}body.light .head-actions select,body.light .search{background:#fff!important;color:#071a2c!important;border-color:rgba(16,49,78,.30)!important}body.light .modal-card,body.light .rh-detail-card{background:#fff!important;color:#071a2c!important;border-color:rgba(16,49,78,.28)!important}body.light canvas{opacity:1!important;filter:none!important}.rh-scope-label select{min-width:160px}.head-actions{flex-wrap:wrap}@media(min-width:1200px){#charges-kpis{grid-template-columns:repeat(5,minmax(0,1fr))!important;gap:14px!important}}';document.head.appendChild(st);}
  rhEnsureScopeFilters();
  if(!window.__lnbRhEscPopupBound){window.__lnbRhEscPopupBound=true;document.addEventListener('keydown',function(e){if(e.key!=='Escape'&&e.key!=='Esc')return;var open=Array.prototype.slice.call(document.querySelectorAll('.modal')).filter(function(m){return m&&!m.hidden&&getComputedStyle(m).display!=='none';});if(open.length){open[open.length-1].hidden=true;e.preventDefault();e.stopPropagation();}},true);}
};

var _rhV8BaseApplyTheme=applyTheme;
applyTheme=function(){_rhV8BaseApplyTheme();if(S.competencia)setTimeout(function(){try{renderCharts();renderCustoReal();}catch(e){}},0);};

renderAll=function(){
  $('empty-state').hidden=true;$('dashboard').hidden=false;
  if(typeof populatePainelFilters==='function')populatePainelFilters();
  rhEnsureScopeFilters();
  renderKpis();renderPeople();renderPayroll();renderRubrics();renderCharges();renderMovements();renderDepartments();renderValidations();renderCharts();renderCustoReal();
};
