/* RH v52 — Próxima Folha com fonte única de totalizadores */
(function(){'use strict';
var timer=0;
function E(id){return document.getElementById(id)}
function r(v){v=Number(v)||0;return Math.round((v+Number.EPSILON)*100)/100}
function p(v){var s=String(v||'').replace(/R\$/g,'').replace(/\s/g,'').replace(/\./g,'').replace(',','.');return Number(s)||0}
function m(v){return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',minimumFractionDigits:2,maximumFractionDigits:2}).format(r(v))}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]})}
function live(){return document.querySelector('#page-planejamento [data-plan-pane="folha"] #rh47-forecast-summary>.rh47-summary-grid')}
function card(key){var g=live();return g&&g.querySelector('.rh47-summary-card[data-rh47-key="'+key+'"]')}
function val(key){var c=card(key),s=c&&c.querySelector('strong');return r(p(s&&s.textContent))}
function txt(key,sel,fallback){var c=card(key),x=c&&c.querySelector(sel);return String(x&&x.textContent||fallback||'').trim()}
function read(){var g=live();if(!g)return null;var prov=val('prov'),disc=val('disc'),ret=val('ret'),company=val('company'),ben=val('ben');if(!(prov>0))return null;return{prov:prov,disc:disc,liq:r(prov-disc),ret:ret,company:company,ben:ben,tax:r(ret+company),cost:r(prov+company+ben),ref:txt('prov','small','Projeção mensal'),benLabel:txt('ben','span','Benefícios confirmados (parcial)'),benSub:txt('ben','small','fonte parcial')}}
function sig(t){return t?[t.prov,t.disc,t.ret,t.company,t.ben].map(function(v){return r(v).toFixed(2)}).join('|'):''}
function one(label,value,sub,key,featured){return '<button type="button" class="rh47-summary-card rh52-card '+(featured?'featured':'')+'" data-rh47-key="'+esc(key)+'"><span>'+esc(label)+'</span><strong>'+m(value)+'</strong><small>'+esc(sub)+'</small></button>'}
function render(t){if(!t)return;var old=E('rh51-forecast-cards');if(old)old.remove();var source=E('rh47-forecast-summary');if(!source||!source.parentNode)return;var host=E('rh52-forecast-cards');if(!host){host=document.createElement('section');host.id='rh52-forecast-cards';host.className='rh52-forecast-cards';source.parentNode.insertBefore(host,source)}var s=sig(t);if(host.dataset.sig===s)return;host.dataset.sig=s;host.innerHTML='<div class="rh52-grid">'+one('Proventos previstos',t.prov,t.ref,'prov')+one('Descontos previstos',t.disc,'retenções + demais descontos','disc')+one('Líquido previsto',t.liq,'proventos − descontos','liq',true)+one('Impostos retidos',t.ret,'INSS segurados + IRRF','ret')+one('Encargos empresa',t.company,'INSS patronal + RAT + terceiros + PIS + FGTS','company')+one(t.benLabel,t.ben,t.benSub,'ben')+one('Tributos / recolhimentos',t.tax,'retidos + encargos da empresa','tax')+one('Custo total estimado',t.cost,'proventos + encargos + benefícios','cost',true)+'</div>'}
function settle(delay){clearTimeout(timer);var tries=0,prev='';function step(){tries++;var t=read(),s=sig(t);if(s&&s===prev){render(t);return}prev=s;if(tries<10)timer=setTimeout(step,260);else if(t)render(t)}timer=setTimeout(step,delay||700)}
function styles(){if(E('_rh52'))return;var s=document.createElement('style');s.id='_rh52';s.textContent='#page-planejamento [data-plan-pane="folha"] #rh-plan-folha-kpis{display:none!important}#page-planejamento [data-plan-pane="folha"] #rh47-forecast-summary>.rh47-summary-grid{display:none!important}#page-planejamento [data-plan-pane="folha"] #rh51-forecast-cards{display:none!important}.rh52-forecast-cards{margin:0 0 12px!important}.rh52-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.rh52-card{height:126px!important;min-height:126px!important;box-sizing:border-box!important;overflow:hidden!important;transform:none!important;animation:none!important}.rh52-card strong{font-size:28px!important;line-height:32px!important;letter-spacing:-.02em!important;white-space:nowrap!important;font-variant-numeric:tabular-nums!important;transition:none!important;animation:none!important;transform:none!important}@media(max-width:1120px){.rh52-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:760px){.rh52-grid{grid-template-columns:1fr}.rh52-card{height:auto!important;min-height:118px!important}}';document.head.appendChild(s)}
function init(){styles();var old=E('rh51-forecast-cards');if(old)old.remove();settle(900);setTimeout(function(){if(!E('rh52-forecast-cards'))settle(0)},2400);document.addEventListener('click',function(e){if(e.target&&e.target.closest&&(e.target.closest('#rh-plan-recalc')||e.target.closest('[data-plan-tab="folha"]')))settle(700)},true);new MutationObserver(function(ms){ms.forEach(function(x){Array.prototype.forEach.call(x.addedNodes||[],function(n){if(n&&n.nodeType===1&&n.id==='rh51-forecast-cards')n.remove()})})}).observe(document.body,{childList:true,subtree:true})}
window.RH_FORECAST_SINGLE_SOURCE_V52=true;window.rhV52Refresh=function(){settle(0)};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();})();