/* RH v34 — motor remuneratório, férias adquiridas, histórico FGTS e custo rescisório completo */
(function(){
'use strict';
function E(id){return document.getElementById(id)}
function n(v){var x=Number(v);return isFinite(x)?x:0}
function r2(v){return Math.round((n(v)+Number.EPSILON)*100)/100}
function d(v){if(!v)return null;if(v instanceof Date)return new Date(v.getTime());var x=new Date(String(v).slice(0,10)+'T12:00:00');return isNaN(x)?null:x}
function br(v){var x=d(v);return x?String(x.getDate()).padStart(2,'0')+'/'+String(x.getMonth()+1).padStart(2,'0')+'/'+x.getFullYear():'—'}
function money(v){try{return fmt(n(v))}catch(e){return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(n(v))}}
function esc2(v){try{return esc(String(v==null?'':v))}catch(e){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}}
function pbr(v){return Number(String(v||'').replace(/R\$|\s/g,'').replace(/\./g,'').replace(',','.'))||0}
function key(p){return String(p&&p.colaborador_id||p&&p.id||'')}
function person(id){var p=(S.pessoas||[]).find(function(x){return key(x)===String(id)});if(p)return p;return (S.colaboradores||[]).find(function(x){return String(x.id)===String(id)})||null}
function norm(s){return String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase()}
function isProvento(l){return String(l&&l.tipo||'').toLowerCase()==='provento'}
function lname(l){return norm(String(l&&l.rubrica_codigo||l&&l.codigo||'')+' '+String(l&&l.rubrica_nome||l&&l.nome||''))}
function recurringLine(l){var x=lname(l);if(!isProvento(l))return false;if(/FERIAS|13O|13º|DECIMO|RESCISAO|AVISO|ABONO|ADIANTAMENTO|SALARIO MATERNIDADE/.test(x))return false;return /ADICIONAL.*FUNCAO|DUPLA FUNCAO|GRATIFICACAO.*FUNCAO|INSALUBRIDADE|PERICULOSIDADE/.test(x)}
function variableLine(l){var x=lname(l);if(!isProvento(l)||recurringLine(l))return false;if(/FERIAS|13O|13º|DECIMO|RESCISAO|AVISO|ABONO|ADIANTAMENTO/.test(x))return false;return /HORA EXTRA|HORAS EXTRAS|COMISSAO|ADICIONAL NOTURNO|DSR|PREMIO|GRATIFICACAO VARIAVEL/.test(x)}
function monthDiff(a,b){a=d(a);b=d(b);if(!a||!b)return 0;return Math.max(0,(b.getFullYear()-a.getFullYear())*12+b.getMonth()-a.getMonth())}
function years(adm,end){adm=d(adm);end=d(end);if(!adm||!end)return 0;var y=end.getFullYear()-adm.getFullYear(),ann=new Date(end.getFullYear(),adm.getMonth(),adm.getDate(),12);if(end<ann)y--;return Math.max(0,y)}
function avos13(y,adm,end,through){adm=d(adm);end=d(end);var q=0;for(var i=0;i<Math.min(12,through);i++){var s=new Date(y,i,1,12),e=new Date(y,i+1,0,12),a=s,b=e;if(adm&&adm>a)a=adm;if(end&&end<b)b=end;if(b>=a&&Math.floor((b-a)/86400000)+1>=15)q++}return q}
function avosFerias(adm,end){adm=d(adm);end=d(end);if(!adm||!end||end<adm)return 0;var start=new Date(end.getFullYear(),adm.getMonth(),adm.getDate(),12);if(start>end)start.setFullYear(start.getFullYear()-1);if(start<adm)start=adm;var q=0,c=new Date(start);while(c<=end&&q<12){var nx=new Date(c.getFullYear(),c.getMonth()+1,c.getDate(),12),pe=new Date(nx-86400000);if(pe>end)pe=end;if(Math.floor((pe-c)/86400000)+1>=15)q++;c=nx}return Math.min(12,q)}
function noticeProjection(dt,days){var x=d(dt);if(!x)return null;return new Date(x.getTime()+days*86400000)}
function inssBands(dt){var y=dt.getFullYear();if(y>=2026)return [[1621,.075],[2902.84,.09],[4354.27,.12],[8475.55,.14]];if(y===2025)return [[1518,.075],[2793.88,.09],[4190.83,.12],[8157.41,.14]];if(y===2024)return [[1412,.075],[2666.68,.09],[4000.03,.12],[7786.02,.14]];if(y===2023)return [[1320,.075],[2571.29,.09],[3856.94,.12],[7507.49,.14]];return [[1412,.075],[2666.68,.09],[4000.03,.12],[7786.02,.14]]}
function inss(base,dt){base=Math.max(0,n(base));var b=inssBands(dt),prev=0,total=0;for(var i=0;i<b.length&&base>prev;i++){var top=b[i][0],rate=b[i][1],slice=Math.min(base,top)-prev;if(slice>0)total+=slice*rate;prev=top}return Math.floor((total+1e-9)*100)/100}
function irrfCfg(dt){var y=dt.getFullYear(),m=dt.getMonth()+1;if(y>=2026||y===2025&&m>=5)return [[2428.80,0,0],[2826.65,.075,182.16],[3751.05,.15,394.16],[4664.68,.225,675.49],[Infinity,.275,908.73]];if(y===2025||y===2024)return [[2259.20,0,0],[2826.65,.075,169.44],[3751.05,.15,381.44],[4664.68,.225,662.77],[Infinity,.275,896.00]];if(y===2023&&m>=5)return [[2112,0,0],[2826.65,.075,158.40],[3751.05,.15,370.40],[4664.68,.225,651.73],[Infinity,.275,884.96]];return [[1903.98,0,0],[2826.65,.075,142.80],[3751.05,.15,354.80],[4664.68,.225,636.13],[Infinity,.275,869.36]]}
function irrf(gross,inssVal,dt){var base=Math.max(0,n(gross)-n(inssVal)),cfg=irrfCfg(dt),tax=0;for(var i=0;i<cfg.length;i++){if(base<=cfg[i][0]){tax=Math.max(0,base*cfg[i][1]-cfg[i][2]);break}}if(dt.getFullYear()>=2026){var rend=n(gross),red=0;if(rend<=5000)red=tax;else if(rend<=7350)red=Math.max(0,978.62-(.133145*rend));tax=Math.max(0,tax-red)}return Math.floor((tax+1e-9)*100)/100}
function rates(){var e=(S.competencia&&S.competencia.encargos)||{},b=n(e.base_total_inss);return{inss:b&&n(e.inss_empresa)>0?n(e.inss_empresa)/b:.20,rat:b&&n(e.rat)>0?n(e.rat)/b:.01,terc:b&&n(e.terceiros)>0?n(e.terceiros)/b:.058,pis:b&&n(e.valor_pis)>0?n(e.valor_pis)/b:.01}}
async function getContext(pid,dt){
  var from='1900-01-01',p=person(pid);if(p&&p.admissao)from=String(p.admissao).slice(0,7)+'-01';
  var until=dt.getFullYear()+'-'+String(dt.getMonth()+1).padStart(2,'0')+'-01';
  var comps=await api('rh_competencias?competencia=gte.'+from+'&competencia=lte.'+until+'&select=id,competencia&order=competencia.asc');
  comps=comps||[];if(!comps.length)return{rows:[],latest:null,latestLaunches:[],recurring:[],variableAvg:0,fgtsKnown:0,first:null,last:null,gaps:0,salaryHistory:[]};
  var ids=comps.map(function(c){return c.id});
  var fs=await api('rh_folha_colaboradores?colaborador_id=eq.'+encodeURIComponent(pid)+'&competencia_id=in.('+ids.join(',')+')&select=id,competencia_id,salario,proventos,descontos,liquido,base_inss,base_fgts,valor_fgts');
  fs=fs||[];var cm={};comps.forEach(function(c){cm[String(c.id)]=c.competencia});fs.forEach(function(f){f._comp=cm[String(f.competencia_id)]||''});
  fs.sort(function(a,b){return String(a._comp).localeCompare(String(b._comp))});
  var latest=fs[fs.length-1]||null,last12=fs.slice(-12),launches=[];
  if(last12.length){var fids=last12.map(function(f){return f.id});launches=await api('rh_lancamentos?folha_colaborador_id=in.('+fids.join(',')+')&select=*')||[]}
  var fm={};last12.forEach(function(f){fm[String(f.id)]=f._comp});launches.forEach(function(l){l._comp=fm[String(l.folha_colaborador_id)]||''});
  var latestLaunches=latest?launches.filter(function(l){return String(l.folha_colaborador_id)===String(latest.id)}):[];
  var recurring=latestLaunches.filter(recurringLine).map(function(l){return{codigo:String(l.rubrica_codigo||l.codigo||''),nome:String(l.rubrica_nome||l.nome||'Verba recorrente'),valor:n(l.valor)}});
  var monthSums={};launches.filter(variableLine).forEach(function(l){var k=l._comp||'sem';monthSums[k]=(monthSums[k]||0)+n(l.valor)});
  var represented=Math.max(1,last12.length),variableAvg=Object.keys(monthSums).reduce(function(s,k){return s+monthSums[k]},0)/represented;
  var fgtsKnown=fs.reduce(function(s,f){return s+n(f.valor_fgts)},0),first=fs.length?fs[0]._comp:null,last=fs.length?fs[fs.length-1]._comp:null,gaps=0;
  if(p&&p.admissao&&first)gaps=monthDiff(String(p.admissao).slice(0,7)+'-01',first);
  var salaryHistory=[],lastSal=null;fs.forEach(function(f){var sal=n(f.salario);if(lastSal===null||Math.abs(sal-lastSal)>.004){salaryHistory.push({competencia:f._comp,salario:sal});lastSal=sal}});
  return{rows:fs,latest:latest,latestLaunches:latestLaunches,recurring:recurring,variableAvg:r2(variableAvg),fgtsKnown:r2(fgtsKnown),first:first,last:last,gaps:gaps,salaryHistory:salaryHistory};
}
async function historicalTermination(pid,dt){try{if(typeof window.rhV31HistoricalTermination==='function')return await window.rhV31HistoricalTermination(pid,dt)}catch(e){}return null}
function ensureForm(){
  var pane=document.querySelector('[data-plan-pane="rescisao"]');if(!pane)return false;
  var over=E('rh26-over');if(over){var lab=over.closest('label');if(lab){var text=lab.childNodes[0];if(text&&text.nodeType===3)text.nodeValue='Períodos adquiridos e não gozados';else lab.insertAdjacentText('afterbegin','Períodos adquiridos e não gozados')}}
  var fg=E('rh26-fgts');if(fg){var fl=fg.closest('label');if(fl){var ft=fl.childNodes[0];if(ft&&ft.nodeType===3)ft.nodeValue='Saldo/Base FGTS oficial (opcional)'}}
  var form=E('rh26-calc')&&E('rh26-calc').closest('.rh-plan-form');if(!form)return false;
  if(!E('rh34-double')){var lbl=document.createElement('label');lbl.innerHTML='Períodos fora do prazo concessivo<input id="rh34-double" type="number" min="0" value="0">';var anchor=over&&over.closest('label');if(anchor)anchor.insertAdjacentElement('afterend',lbl);else form.insertBefore(lbl,E('rh26-calc'))}
  if(!E('rh34-varavg')){var lbl2=document.createElement('label');lbl2.innerHTML='Média variável para reflexos (opcional)<input id="rh34-varavg" inputmode="decimal" placeholder="Automática">';var cct=E('rh26-cct')&&E('rh26-cct').closest('label');if(cct)cct.insertAdjacentElement('beforebegin',lbl2);else form.insertBefore(lbl2,E('rh26-calc'))}
  if(!E('rh34-base-preview')){var note=document.createElement('div');note.id='rh34-base-preview';note.className='rh34-base-preview';note.innerHTML='<b>Base remuneratória</b><span>Ao gerar, o sistema busca salário vigente, verbas salariais recorrentes, médias variáveis e histórico de FGTS.</span>';form.insertBefore(note,E('rh26-calc'))}
  var btn=E('rh26-calc');if(btn&&!btn.dataset.v34){var clone=btn.cloneNode(true);clone.dataset.v31='1';clone.dataset.v32='1';clone.dataset.v33='1';clone.dataset.v34='1';btn.replaceWith(clone);clone.onclick=function(e){if(e)e.preventDefault();render().catch(function(err){try{toast('Não foi possível calcular a rescisão: '+err.message,true)}catch(ignore){}})}}
  var type=E('rh26-type'),notice=E('rh26-notice');if(type&&notice&&!type.dataset.v34){type.dataset.v34='1';type.addEventListener('change',function(){var t=String(type.value||'');if(t==='pedido'){var op=Array.from(notice.options).find(function(o){return o.value==='na'});if(op)notice.value=op.value}})}
  return true;
}
function cards(a){return '<div class="kpi-grid slim rh26-kpis">'+a.map(function(x){return '<div class="kpi '+(x[3]||'')+'"><span>'+esc2(x[0])+'</span><strong>'+esc2(x[1])+'</strong><small>'+esc2(x[2]||'')+'</small></div>'}).join('')+'</div>'}
function lines(a){return '<div class="rh-res-lines">'+a.filter(function(x){return Math.abs(n(x[1]))>.004}).map(function(x){return '<div><span>'+esc2(x[0])+'</span><b>'+money(x[1])+'</b></div>'}).join('')+'</div>'}
function compareRows(x,h){if(!h)return '';var rows=[['Total bruto',x.bruto,h.gross],['Deduções',x.ded,h.discounts],['Líquido',x.liq,h.net],['FGTS da rescisão',x.fgNew,h.fgts]];return '<article class="panel rh31-compare"><div class="panel-head"><div><span class="panel-kicker">CONFERÊNCIA COM HISTÓRICO IMPORTADO</span><h3>Simulado x Rescisão real</h3></div></div><div class="table-wrap"><table><thead><tr><th>Item</th><th class="money">Simulado</th><th class="money">Real importado</th><th class="money">Diferença</th></tr></thead><tbody>'+rows.map(function(q){var diff=r2(q[1]-q[2]);return '<tr><td>'+esc2(q[0])+'</td><td class="money">'+money(q[1])+'</td><td class="money">'+money(q[2])+'</td><td class="money '+(Math.abs(diff)<=.02?'rh31-ok':'rh31-warn')+'"><b>'+money(diff)+'</b></td></tr>'}).join('')+'</tbody></table></div></article>'}
function salaryHistory(ctx){if(!ctx.salaryHistory.length)return '';return '<article class="panel rh34-history"><div class="panel-head"><div><span class="panel-kicker">HISTÓRICO SALARIAL</span><h3>Evolução do salário-base</h3><p>Os reajustes anteriores ficam no histórico; a rescisão fixa usa o salário vigente na data.</p></div></div><div class="rh34-history-grid">'+ctx.salaryHistory.slice(-8).map(function(x){return '<div><span>'+esc2(String(x.competencia||'').slice(5,7)+'/'+String(x.competencia||'').slice(0,4))+'</span><b>'+money(x.salario)+'</b></div>'}).join('')+'</div></article>'}
async function calc(){
  var p=person(E('rh26-person')&&E('rh26-person').value);if(!p)throw new Error('Colaborador não encontrado.');
  var dt=d(E('rh26-date')&&E('rh26-date').value)||new Date(),type=E('rh26-type')?E('rh26-type').value:'pedido',notice=E('rh26-notice')?E('rh26-notice').value:'na';
  if(type==='pedido'&&notice==='indenizado')notice='na';
  var ctx=await getContext(key(p),dt),hist=await historicalTermination(key(p),dt),salary=n(ctx.latest&&ctx.latest.salario)||n(p.salario);
  var recurringTotal=r2(ctx.recurring.reduce(function(s,x){return s+n(x.valor)},0)),manualAvg=pbr(E('rh34-varavg')&&E('rh34-varavg').value),avg=manualAvg>0?manualAvg:ctx.variableAvg;
  var fixedBase=r2(salary+recurringTotal),reflectionBase=r2(fixedBase+avg),days=Math.min(30,dt.getDate()),saldo=r2(fixedBase/30*days);
  var yd=years(p.admissao,dt),noticeDays=Math.min(90,30+yd*3),aviso=type==='empregador'&&notice==='indenizado'?r2(reflectionBase/30*noticeDays):0,proj=aviso?noticeProjection(dt,noticeDays):dt;
  var a13=avos13(dt.getFullYear(),p.admissao,dt,dt.getMonth()+1),a13Proj=avos13(dt.getFullYear(),p.admissao,proj,proj.getMonth()+1),extra13=Math.max(0,a13Proj-a13),v13=r2(reflectionBase/12*a13),v13Aviso=r2(reflectionBase/12*extra13);
  var avf=avosFerias(p.admissao,dt),avfProj=avosFerias(p.admissao,proj),extraFerias=Math.max(0,avfProj-avf),vf=r2(reflectionBase/12*avf),vfAviso=r2(reflectionBase/12*extraFerias);
  var acquired=Math.max(0,n(E('rh26-over')&&E('rh26-over').value)),overdue=Math.max(0,n(E('rh34-double')&&E('rh34-double').value)),feriasAdq=r2(reflectionBase*acquired),ter=r2((feriasAdq+vf+vfAviso)/3),dobroExtra=r2(reflectionBase*4/3*overdue);
  var cct=pbr(E('rh26-cct')&&E('rh26-cct').value),cred=pbr(E('rh26-cred')&&E('rh26-cred').value),manualDisc=pbr(E('rh26-disc')&&E('rh26-disc').value),officialFg=pbr(E('rh26-fgts')&&E('rh26-fgts').value);
  var inssM=hist?hist.inss:inss(saldo,dt),inss13=hist?hist.inss13:inss(v13+v13Aviso,dt),irrfM=hist?hist.irrf:irrf(saldo,inssM,dt),irrf13=hist?hist.irrf13:irrf(v13+v13Aviso,inss13,dt),operational=manualDisc>0?manualDisc:(hist?hist.other:0),noticeDisc=type==='pedido'&&notice==='desconto'?fixedBase:0;
  var bruto=r2(saldo+v13+v13Aviso+vf+vfAviso+feriasAdq+ter+dobroExtra+aviso+cct+cred),ded=r2(inssM+inss13+irrfM+irrf13+operational+noticeDisc),liq=r2(bruto-ded);
  var fgm=r2(saldo*.08),fg13=r2((v13+v13Aviso)*.08),fgav=r2(aviso*.08),fgNew=r2(fgm+fg13+fgav),fgHist=officialFg>0?officialFg:ctx.fgtsKnown,multaBase=r2(fgHist+fgNew),multa=type==='empregador'?r2(multaBase*.40):0;
  var rr=rates(),patBase=r2(saldo+v13+v13Aviso),patInss=r2(patBase*rr.inss),patRat=r2(patBase*rr.rat),patTerc=r2(patBase*rr.terc),patPis=r2(patBase*rr.pis),patTotal=r2(patInss+patRat+patTerc+patPis),custo=r2(bruto+fgNew+multa+patTotal);
  return{p:p,date:dt,type:type,notice:notice,ctx:ctx,hist:hist,salary:salary,recurringTotal:recurringTotal,avg:avg,fixedBase:fixedBase,reflectionBase:reflectionBase,days:days,saldo:saldo,noticeDays:noticeDays,proj:proj,aviso:aviso,a13:a13,extra13:extra13,v13:v13,v13Aviso:v13Aviso,avf:avf,extraFerias:extraFerias,vf:vf,vfAviso:vfAviso,acquired:acquired,overdue:overdue,feriasAdq:feriasAdq,ter:ter,dobroExtra:dobroExtra,cct:cct,cred:cred,inss:inssM,inss13:inss13,irrf:irrfM,irrf13:irrf13,operational:operational,noticeDisc:noticeDisc,bruto:bruto,ded:ded,liq:liq,fgOfficial:officialFg,fgHist:fgHist,fgm:fgm,fg13:fg13,fgav:fgav,fgNew:fgNew,multaBase:multaBase,multa:multa,patBase:patBase,patInss:patInss,patRat:patRat,patTerc:patTerc,patPis:patPis,patTotal:patTotal,custo:custo};
}
async function render(){
  ensureForm();var box=E('rh26-result');if(!box)return;box.innerHTML='<div class="empty-state"><h2>Calculando...</h2><p>Buscando remuneração vigente, médias, histórico de FGTS e incidências.</p></div>';
  var x=await calc();window.rhV34TerminationResult=x;
  var recur=x.ctx.recurring.length?x.ctx.recurring.map(function(v){return '<div><span>'+esc2(v.nome)+'</span><b>'+money(v.valor)+'</b></div>'}).join(''):'<div><span>Verbas recorrentes adicionais</span><b>'+money(0)+'</b></div>';
  var fgNote=x.fgOfficial>0?'Saldo oficial informado manualmente.':(x.ctx.gaps>0?'Estimativa mínima: faltam '+x.ctx.gaps+' competência(s) anteriores à primeira folha importada.':'Histórico importado cobre o vínculo conhecido.');
  box.innerHTML=
    '<div class="panel-head"><div><span class="panel-kicker">RELATÓRIO ANALÍTICO · '+(x.hist?'CONFERÊNCIA HISTÓRICA':'ESTIMATIVA GERENCIAL')+'</span><h2>'+esc2(x.p.nome||'Colaborador')+'</h2><p>'+(x.type==='empregador'?'Despedida sem justa causa pelo empregador':'Pedido de demissão')+' · '+br(x.date)+'</p></div></div>'+
    cards([['Total bruto',money(x.bruto),'verbas rescisórias'],['Deduções',money(x.ded),x.hist?'impostos + descontos históricos':'impostos estimados + descontos'],['Líquido',money(x.liq),'estimativa a pagar','featured'],['Custo empregador',money(x.custo),'bruto + FGTS + multa + encargos']])+
    '<article class="panel rh34-rem"><div class="panel-head"><div><span class="panel-kicker">BASE REMUNERATÓRIA</span><h3>Remuneração usada nos reflexos</h3><p>Salários antigos ficam no histórico e não reduzem a base fixa atual.</p></div></div><div class="rh26-memory"><div><span>Salário-base vigente</span><b>'+money(x.salary)+'</b></div>'+recur+'<div><span>Média variável '+(pbr(E('rh34-varavg')&&E('rh34-varavg').value)>0?'informada':'detectada')+'</span><b>'+money(x.avg)+'</b></div><div class="total"><span>Base para aviso / 13º / férias</span><b>'+money(x.reflectionBase)+'</b></div></div></article>'+
    '<div class="rh26-term"><div><h3>Verbas rescisórias</h3>'+lines([['Saldo de salário '+x.days+' dias',x.saldo],['13º proporcional '+x.a13+'/12',x.v13],['13º sobre projeção do aviso '+x.extra13+'/12',x.v13Aviso],['Férias proporcionais '+x.avf+'/12',x.vf],['Férias sobre projeção do aviso '+x.extraFerias+'/12',x.vfAviso],['Período(s) adquirido(s) e não gozado(s)',x.feriasAdq],['1/3 constitucional',x.ter],['Adicional por férias fora do prazo (estim.)',x.dobroExtra],['Aviso-prévio indenizado '+x.noticeDays+' dias',x.aviso],['Indenização CCT / outra verba',x.cct],['Outros créditos',x.cred]])+'</div><div><h3>Deduções</h3>'+lines([['INSS mensal',x.inss],['INSS 13º',x.inss13],['IRRF mensal',x.irrf],['IRRF 13º',x.irrf13],['Descontos operacionais / benefícios',x.operational],['Aviso descontado',x.noticeDisc]])+'</div></div>'+
    '<article class="panel rh26-base"><h3>FGTS e multa rescisória</h3><div class="rh26-memory"><div><span>FGTS histórico conhecido</span><b>'+money(x.fgHist)+'</b></div><div><span>FGTS do mês</span><b>'+money(x.fgm)+'</b></div><div><span>FGTS 13º</span><b>'+money(x.fg13)+'</b></div><div><span>FGTS aviso</span><b>'+money(x.fgav)+'</b></div><div><span>Novo FGTS da rescisão</span><b>'+money(x.fgNew)+'</b></div><div><span>Base conhecida para multa</span><b>'+money(x.multaBase)+'</b></div><div class="total"><span>Multa de 40% '+(x.fgOfficial>0?'':'(mínima estimada)')+'</span><b>'+money(x.multa)+'</b></div></div><p class="detail-note">'+esc2(fgNote)+(x.ctx.first?' · Histórico: '+esc2(String(x.ctx.first).slice(5,7)+'/'+String(x.ctx.first).slice(0,4))+' a '+esc2(String(x.ctx.last).slice(5,7)+'/'+String(x.ctx.last).slice(0,4)):'')+'</p></article>'+
    '<article class="panel rh34-patronal"><h3>Encargos e custo do empregador</h3><div class="rh26-memory"><div><span>Base patronal estimada</span><b>'+money(x.patBase)+'</b></div><div><span>INSS patronal</span><b>'+money(x.patInss)+'</b></div><div><span>RAT</span><b>'+money(x.patRat)+'</b></div><div><span>Terceiros</span><b>'+money(x.patTerc)+'</b></div><div><span>PIS folha</span><b>'+money(x.patPis)+'</b></div><div><span>FGTS novo</span><b>'+money(x.fgNew)+'</b></div><div><span>Multa FGTS</span><b>'+money(x.multa)+'</b></div><div class="total"><span>Custo total estimado</span><b>'+money(x.custo)+'</b></div></div></article>'+
    salaryHistory(x.ctx)+compareRows(x,x.hist)+
    '<div class="rh-plan-warning"><b>Estimativa gerencial</b><span>O cálculo usa a remuneração vigente, adiciona verbas salariais recorrentes detectadas, médias variáveis quando identificadas, diferencia férias adquiridas de férias fora do prazo e estima a multa de FGTS com o histórico disponível. Para pagamento oficial, conferir FGTS Digital, CCT, médias, estabilidade e incidências da folha.</span></div>';
  var prev=E('rh34-base-preview');if(prev)prev.innerHTML='<b>Base remuneratória atual</b><span>'+money(x.salary)+' salário + '+money(x.recurringTotal)+' recorrentes + '+money(x.avg)+' média = <strong>'+money(x.reflectionBase)+'</strong></span>';
  try{if(typeof rhFitAllCardValues==='function')setTimeout(rhFitAllCardValues,0)}catch(ignore){}
}
function style(){if(E('_rh34'))return;var s=document.createElement('style');s.id='_rh34';s.textContent='.rh34-base-preview{grid-column:1/-1;display:flex;gap:10px;align-items:center;padding:11px 12px;border:1px solid var(--line-soft);border-radius:11px;background:var(--surface-2);font-size:.78rem}.rh34-base-preview b{color:var(--gold);white-space:nowrap}.rh34-base-preview span{color:var(--muted)}.rh34-rem,.rh34-patronal,.rh34-history{margin-top:16px}.rh34-history-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:8px}.rh34-history-grid>div{display:flex;justify-content:space-between;gap:10px;padding:10px 12px;border:1px solid var(--line-soft);border-radius:10px;background:var(--surface-2)}.rh34-history-grid span{color:var(--muted)}.rh34-history-grid b{white-space:nowrap}@media(max-width:900px){.rh34-base-preview{align-items:flex-start;flex-direction:column}}';document.head.appendChild(s)}
var obs=new MutationObserver(function(){style();ensureForm()});
function init(){style();ensureForm();obs.observe(document.body,{childList:true,subtree:true})}
window.rhV34TerminationContext=getContext;window.rhV34CalcTermination=calc;window.rhV34RenderTermination=render;window.rhV34EnsureTerminationForm=ensureForm;
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();