/* RH & Folha v62 — corrige os fluxos que dependiam do escopo privado do v57. */
(function(){
'use strict';
window.RH_DP_V62=true;
var V62={roster:null,busy:false,openSeq:0};
function el62(id){return document.getElementById(id)}
function esc62(v){return esc(String(v==null?'':v))}
function num62(v){var n=Number(v);return isFinite(n)?n:0}
function money62(v){return fmt(num62(v))}
function norm62(v){return cleanSearch(String(v||'')).replace(/\s+/g,' ').trim()}
function off62(v){return /demit|deslig|rescis|rescind|inativ|transferid/.test(norm62(v))}
function active62(v){return !off62(v)}
function date62(v){return v?dateBR(String(v).slice(0,10)):'—'}
function iso62(v){return v?String(v).slice(0,10):null}
function value62(id){return String((el62(id)||{}).value||'').trim()}
function parseMoney62(v){return Number(String(v||'').replace(/R\$|\s/g,'').replace(/\./g,'').replace(',','.'))||0}
function notify62(msg,error){try{toast(msg,!!error)}catch(e){if(error)console.error(msg)}}
function collaboratorId62(p){return String(p&&p.colaborador_id||p&&p.id||'')}
function currentCollaborator62(id){return (S.colaboradores||[]).find(function(c){return String(c.id)===String(id)})||null}
function payrollFor62(id){return (S.pessoas||[]).find(function(p){return String(p.colaborador_id||'')===String(id)})||null}
function statusRank62(v){return /^trabalhando$/i.test(String(v||''))?0:(/afast|ferias|férias/i.test(String(v||''))?1:2)}

function style62(){
  if(el62('rh62-style'))return;var s=document.createElement('style');s.id='rh62-style';s.textContent=
    '#rh62-modal{position:fixed;inset:0;z-index:15000;display:grid;place-items:center;padding:18px;background:rgba(2,10,19,.80);backdrop-filter:blur(9px)}'+
    '.rh62-card{width:min(var(--rh62-width,820px),calc(100vw - 36px));max-height:calc(100vh - 36px);display:flex;flex-direction:column;overflow:hidden;border:1px solid var(--line);border-radius:19px;background:var(--surface);color:var(--text);box-shadow:0 28px 80px rgba(0,0,0,.55)}'+
    '.rh62-head{display:flex;justify-content:space-between;gap:16px;padding:19px 22px 15px;border-bottom:1px solid var(--line-soft)}.rh62-head span{color:var(--gold-2);font-size:9px;font-weight:900;letter-spacing:.13em}.rh62-head h2{margin:5px 0 3px;font-size:23px}.rh62-head p{margin:0;color:var(--muted);font-size:11px}.rh62-close{width:38px;height:38px;border:1px solid var(--line-soft);border-radius:10px;background:var(--surface-2);color:var(--text);font-size:22px;cursor:pointer}'+
    '.rh62-body{min-height:0;overflow:auto;padding:18px 22px 22px}.rh62-form{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.rh62-form label{display:grid;gap:5px;color:var(--muted);font-size:10px;font-weight:800;text-transform:uppercase}.rh62-form input,.rh62-form select,.rh62-form textarea{width:100%;box-sizing:border-box;padding:9px 10px;border:1px solid var(--line-soft);border-radius:9px;background:var(--surface-2);color:var(--text)}'+
    '.rh62-checks,.rh62-full{grid-column:1/-1}.rh62-checks{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.rh62-checks label{display:flex;align-items:center;gap:8px;text-transform:none}.rh62-checks input{width:auto}.rh62-note{padding:11px 12px;border:1px solid var(--line-soft);border-radius:10px;background:var(--surface-2);color:var(--muted);font-size:11px;line-height:1.5}'+
    '.rh62-info{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:9px;margin-bottom:14px}.rh62-info div{padding:10px;border:1px solid var(--line-soft);border-radius:10px;background:var(--surface-2)}.rh62-info span{display:block;color:var(--muted);font-size:9px;text-transform:uppercase}.rh62-info strong{display:block;margin-top:4px;font-size:12px}'+
    '.rh62-actions{display:flex;gap:8px;flex-wrap:wrap;align-items:center}.rh62-row-slip{display:inline-flex;margin-top:5px;padding:3px 7px;border:1px solid var(--line-soft);border-radius:7px;background:var(--surface-2);color:var(--gold-2);font-size:9px;font-weight:850;cursor:pointer}.rh62-click{cursor:pointer;box-shadow:0 0 0 1px currentColor inset}.rh62-scroll{width:100%;overflow:auto}.rh62-scroll table{width:100%;min-width:760px;border-collapse:collapse}.rh62-scroll th,.rh62-scroll td{padding:9px 10px;border-bottom:1px solid var(--line-soft);font-size:11px}.rh62-scroll th{color:var(--muted);font-size:9px;text-transform:uppercase}.rh62-vac-summary{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0}'+
    '@media(max-width:760px){#rh62-modal{padding:7px}.rh62-card{width:calc(100vw - 14px);max-height:calc(100vh - 14px)}.rh62-form{grid-template-columns:1fr}.rh62-full,.rh62-checks{grid-column:1}.rh62-checks{grid-template-columns:1fr}.rh62-info{grid-template-columns:1fr 1fr}}'+
    'html[data-lnb-mobile-shell] #rh62-modal{inset:var(--lnb-mobile-top) 0 var(--lnb-mobile-bottom);z-index:999980;padding:7px;place-items:stretch center;overflow:hidden}'+
    'html[data-lnb-mobile-shell] #rh62-modal .rh62-card{width:100%;max-width:100%;height:100%;max-height:100%;min-height:0;border-radius:18px}'+
    'html[data-lnb-mobile-shell] #rh62-modal .rh62-head{position:relative;z-index:3;flex:0 0 auto;align-items:flex-start;padding:12px 13px;background:var(--surface)}'+
    'html[data-lnb-mobile-shell] #rh62-modal .rh62-head>div{min-width:0}html[data-lnb-mobile-shell] #rh62-modal .rh62-head h2{font-size:19px;line-height:1.15;overflow-wrap:anywhere}'+
    'html[data-lnb-mobile-shell] #rh62-modal .rh62-close{display:grid;place-items:center;flex:0 0 44px;width:44px;height:44px;margin:0;padding:0;position:relative;z-index:4}'+
    'html[data-lnb-mobile-shell] #rh62-modal .rh62-body{flex:1;min-height:0;padding:12px 12px 10px;overflow-y:auto;overflow-x:hidden;overscroll-behavior:contain}'+
    'html[data-lnb-mobile-shell] #rh62-modal .rh62-form{padding-bottom:4px}html[data-lnb-mobile-shell] #rh62-modal .rh62-form button[type="submit"]{position:sticky;z-index:5;bottom:0;width:100%;min-height:50px;margin-top:4px;box-shadow:0 -10px 22px var(--surface)}';document.head.appendChild(s)
}
function close62(internal){if(!internal)V62.openSeq++;var m=el62('rh62-modal');if(m)m.remove()}
function modal62(title,subtitle,html,width){
  close62(true);style62();var m=document.createElement('div');m.id='rh62-modal';m.setAttribute('role','dialog');m.setAttribute('aria-modal','true');m.innerHTML='<section class="rh62-card" style="--rh62-width:'+(width||820)+'px"><header class="rh62-head"><div><span>RH & FOLHA · ADMINISTRAÇÃO DE PESSOAL</span><h2>'+esc62(title)+'</h2><p>'+esc62(subtitle||'')+'</p></div><button type="button" class="rh62-close" data-rh62-close aria-label="Fechar">×</button></header><div class="rh62-body">'+html+'</div></section>';document.body.appendChild(m);m.addEventListener('click',function(e){if(e.target===m)close62()})
}

function filteredCollaborators62(){
  var q=norm62(value62('employee-search')),pay={};(S.pessoas||[]).forEach(function(p){pay[String(p.colaborador_id||'')]=p});
  return (S.colaboradores||[]).map(function(c){return {c:c,p:pay[String(c.id)]||null}}).filter(function(r){var c=r.c;if(RH_SCOPE.dept&&String(c.departamento)!==String(RH_SCOPE.dept))return false;if(RH_SCOPE.vinculo&&rhVinculoCategory(c)!==RH_SCOPE.vinculo)return false;if(RH_SCOPE.situacao&&rhSituacaoCategory(c)!==RH_SCOPE.situacao)return false;return !q||norm62([c.nome,c.matricula,c.departamento,c.cargo].join(' ')).indexOf(q)>=0}).sort(function(a,b){return statusRank62(a.c.situacao)-statusRank62(b.c.situacao)||String(a.c.nome||'').localeCompare(String(b.c.nome||''),'pt-BR',{sensitivity:'base'})})
}
function renderCollaborators62(){
  var body=el62('employee-rows');if(!body)return;var rows=filteredCollaborators62();body.innerHTML=rows.length?rows.map(function(r){var c=r.c,p=r.p,off=off62(c.situacao),cost=p?custoEmpresa(p):null,payrollId=p&&p.id||'';return '<tr><td><div class="row-person"><span class="avatar">'+esc62(initials(c.nome))+'</span><span><b class="link-name" data-person="'+esc62(payrollId||c.id)+'" data-rh62-employee="'+esc62(c.id)+'">'+esc62(c.nome)+'</b><small>'+esc62(c.cargo||c.cpf_mascarado||'')+'</small></span></div></td><td>'+esc62(c.matricula||'—')+'</td><td>'+esc62(c.vinculo||'—')+'</td><td>'+esc62(departmentName(c.departamento))+'</td><td><span class="status rh62-click '+(off?'danger':'success')+'" data-rh62-employee="'+esc62(c.id)+'">'+esc62(c.situacao||'—')+'</span></td><td class="money">'+(p?money62(p.proventos):'—')+'</td><td class="money">'+(p?'<button class="detail-button enc-btn" data-encargos="'+esc62(p.id)+'">'+money62(cost.total)+'</button>':'—')+'</td><td class="money"><b>'+(p?money62(p.liquido):'—')+'</b></td></tr>'}).join(''):emptyRow(8,'Nenhum colaborador para os filtros selecionados.');bindEncargosButtons();decorate62()
}

function cleanup61(){
  document.querySelectorAll('.rh61-actions').forEach(function(x){x.remove()});var old=el62('rh61-payslips');if(old)old.remove();document.querySelectorAll('[data-rh61-status]').forEach(function(x){x.removeAttribute('data-rh61-status')})
}
function vacationRows62(){
  var now=new Date(),rows=[];(S.colaboradores||[]).filter(function(c){return c.admissao&&active62(c.situacao)}).forEach(function(c){var ad=new Date(String(c.admissao).slice(0,10)+'T12:00:00');if(isNaN(ad))return;var years=now.getFullYear()-ad.getFullYear();if(now.getMonth()<ad.getMonth()||(now.getMonth()===ad.getMonth()&&now.getDate()<ad.getDate()))years--;if(years<1)return;var start=new Date(ad),end=new Date(ad),limit=new Date(ad);start.setFullYear(ad.getFullYear()+years-1);end.setFullYear(ad.getFullYear()+years);end.setDate(end.getDate()-1);limit.setFullYear(ad.getFullYear()+years+1);limit.setDate(limit.getDate()-1);var days=Math.ceil((limit-now)/86400000);rows.push({c:c,start:start,end:end,limit:limit,days:days,level:days<0?'over':(days<=90?'near':'ok')})});return rows.sort(function(a,b){return a.limit-b.limit})
}
function ensureUi62(){
  style62();cleanup61();var page=el62('page-colaboradores'),head=page&&page.querySelector('.page-head'),actions=head&&head.querySelector('.head-actions');if(actions&&!el62('rh62-actions')){var box=document.createElement('div');box.id='rh62-actions';box.className='rh62-actions';box.innerHTML='<button type="button" class="button primary admin-only" id="rh62-new">Novo colaborador</button><button type="button" class="button secondary export-only" id="rh62-batch">Holerites em lote</button><button type="button" class="button secondary admin-only" id="rh62-sync">Sincronizar cadastros</button><button type="button" class="button ghost" id="rh62-vacations">Alertas de férias</button>';actions.appendChild(box)}var vb=el62('rh62-vacations');if(vb){var vr=vacationRows62(),n=vr.filter(function(r){return r.level!=='ok'}).length;vb.textContent='Alertas de férias'+(n?' ('+n+')':'')}try{setupPermissions()}catch(e){}
}
function decorate62(){document.querySelectorAll('.link-name[data-rh62-employee],.status[data-rh62-employee]').forEach(function(x){x.title='Clique para consultar admissão, desligamento e situação atual'})}

function newCollaborator62(){
  modal62('Novo colaborador','Cadastro funcional, dados de DP e opções de benefícios.','<form class="rh62-form" id="rh62-new-form"><label>Matrícula *<input id="rh62-matricula" maxlength="40" required></label><label>Nome completo *<input id="rh62-nome" maxlength="160" required></label><label>Data de admissão *<input id="rh62-admissao" type="date" required></label><label>Vínculo *<select id="rh62-vinculo"><option>Celetista</option><option>Estagiário</option><option>Aprendiz</option><option>PJ</option><option>Diretor</option><option>Outro</option></select></label><label>Cargo<input id="rh62-cargo" maxlength="120"></label><label>Departamento<input id="rh62-departamento" maxlength="120"></label><label>Centro de custo<input id="rh62-cc" maxlength="80"></label><label>Gestor responsável<input id="rh62-gestor" maxlength="120"></label><label>Nascimento<input id="rh62-nascimento" type="date"></label><label>E-mail corporativo<input id="rh62-email" type="email" maxlength="160"></label><label>Telefone<input id="rh62-telefone" maxlength="30"></label><label>Salário-base<input id="rh62-salario" inputmode="decimal" placeholder="0,00"></label><label>Jornada semanal<input id="rh62-jornada" type="number" min="1" max="60" step="0.5" value="40"></label><label>Observações<textarea id="rh62-observacoes" maxlength="500" rows="2"></textarea></label><div class="rh62-checks"><label><input id="rh62-vt" type="checkbox"> Optou por Vale Transporte</label><label><input id="rh62-vr" type="checkbox"> Optou por VR/VA</label><label><input id="rh62-med" type="checkbox"> Optou por Plano de Saúde</label><label><input id="rh62-seg" type="checkbox"> Optou por Seguro de Vida</label></div><div class="rh62-note rh62-full">O cadastro será incluído como <b>Trabalhando</b> e aparecerá imediatamente em Colaboradores, mesmo antes da primeira folha.</div><button type="submit" class="button primary rh62-full" id="rh62-new-save">Salvar colaborador</button></form>',790)
}
async function saveNew62(){
  var b=el62('rh62-new-save'),body={p_matricula:value62('rh62-matricula'),p_nome:value62('rh62-nome'),p_admissao:iso62(value62('rh62-admissao')),p_vinculo:value62('rh62-vinculo'),p_cargo:value62('rh62-cargo')||null,p_departamento:value62('rh62-departamento')||null,p_centro_custo:value62('rh62-cc')||null,p_data_nascimento:iso62(value62('rh62-nascimento')),p_email:value62('rh62-email')||null,p_telefone:value62('rh62-telefone')||null,p_salario_base:parseMoney62(value62('rh62-salario'))||null,p_jornada_horas_semanais:num62(value62('rh62-jornada'))||null,p_gestor:value62('rh62-gestor')||null,p_opta_vale_transporte:!!el62('rh62-vt').checked,p_opta_vr_va:!!el62('rh62-vr').checked,p_opta_plano_saude:!!el62('rh62-med').checked,p_opta_seguro_vida:!!el62('rh62-seg').checked,p_observacoes:value62('rh62-observacoes')||null};if(!body.p_matricula||!body.p_nome||!body.p_admissao)return notify62('Preencha matrícula, nome e data de admissão.',true);b.disabled=true;try{var out=await rpc('rh_criar_colaborador',body);close62();notify62('Colaborador cadastrado e auditado.');if(S.competencia)await selectCompetence(S.competencia.id);renderCollaborators62();var id=out&&out.colaborador_id;if(id)openEmployee62(id)}catch(e){notify62(e.message||String(e),true)}finally{b.disabled=false}
}

async function roster62(force){if(V62.roster&&!force)return V62.roster;V62.roster=await rpc('rh_quadro_atual',{});return V62.roster||[]}
async function openEmployee62(id){
  var mobile=!!document.documentElement.dataset.lnbMobileShell,request=mobile?++V62.openSeq:V62.openSeq;if(mobile)modal62('Carregando colaborador','Buscando cadastro e situação funcional.','<div class="rh62-note">Carregando informações…</div>',820);
  try{var rows=await roster62(true);if(mobile&&(request!==V62.openSeq||!el62('rh62-modal')))return;var r=rows.find(function(x){return String(x.colaborador_id)===String(id)}),c=currentCollaborator62(id),p=payrollFor62(id);if(!r&&c)r={colaborador_id:c.id,nome:c.nome,matricula:c.matricula,vinculo:c.vinculo,departamento:c.departamento,admissao:c.admissao,situacao:c.situacao,desligamento:c.desligamento,status_origem:c.status_origem};if(!r)throw new Error('Colaborador não encontrado.');var inferred=r.desligamento_origem==='ultima_folha';var info=[['Matrícula',r.matricula||'—'],['Vínculo',r.vinculo||'—'],['Departamento',departmentName(r.departamento)],['Admissão',date62(r.admissao)],['Situação',r.situacao||'—'],['Desligamento',date62(r.desligamento)+(inferred?' · inferido pela folha':'')],['Última folha',r.ultima_competencia?formatCompetence(r.ultima_competencia):'—'],['Origem do status',r.status_origem||'—']].map(function(x){return '<div><span>'+esc62(x[0])+'</span><strong>'+esc62(x[1])+'</strong></div>'}).join('');var form=canAdmin()?'<form class="rh62-form" id="rh62-status-form" data-employee="'+esc62(r.colaborador_id)+'"><label>Situação atual<select id="rh62-status"><option>Trabalhando</option><option>Férias</option><option>Afastado</option><option>Desligado</option></select></label><label>Data do desligamento<input id="rh62-dismissal" type="date" value="'+esc62(r.desligamento||'')+'"></label><label class="rh62-full">Motivo / observação *<input id="rh62-status-reason" maxlength="180" placeholder="Obrigatório para auditoria"></label><div class="rh62-note rh62-full">Quando o colaborador deixa de constar da última folha, o sistema define o desligamento no primeiro dia da competência seguinte à última presença. Uma alteração manual posterior é preservada.</div><button type="submit" class="button primary rh62-full" id="rh62-status-save">Salvar situação</button></form>':'<div class="rh62-note">Seu perfil possui acesso somente para consulta.</div>';var actions='<div class="rh62-actions" style="margin-bottom:14px">'+(p?'<button type="button" class="button secondary export-only" data-rh63-pdf="'+esc62(id)+'">Baixar holerite individual</button><button type="button" class="button secondary export-only" data-rh63-email="'+esc62(id)+'">Enviar holerite por e-mail</button><button type="button" class="button ghost" data-rh62-payroll="'+esc62(p.id)+'">Ver composição da folha</button>':'<span class="status">Sem folha nesta competência</span>')+'<button type="button" class="button ghost" data-rh63-dp-person="'+esc62(id)+'">Controles de DP</button></div>';if(mobile&&request!==V62.openSeq)return;modal62(r.nome,'Cadastro e situação funcional',actions+'<div class="rh62-info">'+info+'</div>'+form,820);var s=el62('rh62-status');if(s){s.value=off62(r.situacao)?'Desligado':(r.situacao||'Trabalhando');toggleDismissal62()}try{setupPermissions()}catch(e){}}
  catch(e){if(!mobile||request===V62.openSeq){if(mobile)close62(true);notify62(e.message||String(e),true)}}
}
function toggleDismissal62(){var s=el62('rh62-status'),d=el62('rh62-dismissal');if(!s||!d)return;var off=s.value==='Desligado';d.disabled=!off;if(off&&!d.value)d.value=new Date().toISOString().slice(0,10);if(!off)d.value=''}
async function saveStatus62(form){var b=el62('rh62-status-save'),status=value62('rh62-status'),date=iso62(value62('rh62-dismissal')),reason=value62('rh62-status-reason');if(!reason)return notify62('Informe o motivo da alteração.',true);if(status==='Desligado'&&!date)return notify62('Informe a data do desligamento.',true);b.disabled=true;try{await rpc('rh_atualizar_status_colaborador',{p_colaborador_id:form.dataset.employee,p_situacao:status,p_desligamento:date,p_motivo:reason});V62.roster=null;close62();notify62('Situação atualizada e auditada.');if(S.competencia)await selectCompetence(S.competencia.id);renderCollaborators62()}catch(e){notify62(e.message||String(e),true)}finally{b.disabled=false}}

async function sync62(b){if(V62.busy)return;V62.busy=true;b.disabled=true;var old=b.textContent;b.textContent='Sincronizando…';try{var r=await rpc('rh_sincronizar_cadastros_beneficios',{});var n=await rpc('rh_reconciliar_quadro_atual',{});V62.roster=null;notify62((r.correspondencias_seguras||0)+' cadastro(s) conciliado(s) e '+num62(n)+' situação(ões) atualizada(s).');if(S.competencia)await selectCompetence(S.competencia.id);renderCollaborators62()}catch(e){notify62(e.message||String(e),true)}finally{V62.busy=false;b.disabled=false;b.textContent=old}}

function vacationModal62(){var rows=vacationRows62(),over=rows.filter(function(r){return r.level==='over'}).length,near=rows.filter(function(r){return r.level==='near'}).length;modal62('Alertas de férias','Controle preventivo calculado ao abrir Colaboradores.','<div class="rh62-note"><b>Como funciona:</b> amarelo quando faltam até 90 dias para o limite concessivo e vermelho depois do limite. Neste estágio, a apuração usa a data de admissão e é uma estimativa; recibos e períodos já gozados ainda precisam ser conferidos.</div><div class="rh62-vac-summary"><span class="status danger">'+over+' vencida(s) para revisar</span><span class="status">'+near+' em até 90 dias</span></div><div class="rh62-scroll"><table><thead><tr><th>Colaborador</th><th>Período aquisitivo estimado</th><th>Limite estimado</th><th>Alerta</th></tr></thead><tbody>'+rows.map(function(r){var cls=r.level==='over'?'danger':(r.level==='near'?'':'success'),label=r.days<0?Math.abs(r.days)+' dia(s) após o limite':r.days+' dia(s) até o limite';return '<tr><td><b>'+esc62(r.c.nome)+'</b><br><small>'+esc62(departmentName(r.c.departamento))+'</small></td><td>'+date62(r.start.toISOString())+' a '+date62(r.end.toISOString())+'</td><td>'+date62(r.limit.toISOString())+'</td><td><span class="status '+cls+'">'+esc62(label)+'</span></td></tr>'}).join('')+'</tbody></table></div>',980)}

async function ensurePdf62(){if(!LIBRARIES.jspdf)LIBRARIES.jspdf={url:'https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js',ready:function(){return !!(window.jspdf&&window.jspdf.jsPDF)}};if(!LIBRARIES.autotable)LIBRARIES.autotable={url:'https://cdnjs.cloudflare.com/ajax/libs/jspdf-autotable/3.8.4/jspdf.plugin.autotable.min.js',ready:function(){return !!(window.jspdf&&window.jspdf.jsPDF&&window.jspdf.jsPDF.API.autoTable)}};await loadLibrary('jspdf');await loadLibrary('autotable')}
function launches62(p){return (p.lancamentos||[]).slice().sort(function(a,b){return String(a.tipo).localeCompare(String(b.tipo))||num62(b.valor)-num62(a.valor)}).map(function(l){return[l.rubrica_codigo||'—',l.rubrica_nome||'Rubrica',l.referencia==null?'—':String(l.referencia).replace('.',','),l.tipo==='provento'?money62(l.valor):'',l.tipo==='desconto'?money62(l.valor):'']})}
async function generatePayslips62(people,fileLabel){if(!people.length)throw new Error('Nenhuma folha individual disponível para o filtro atual.');await ensurePdf62();var doc=new window.jspdf.jsPDF({orientation:'portrait',unit:'mm',format:'a4',compress:true});people.forEach(function(p,i){if(i)doc.addPage();doc.setFillColor(7,26,44);doc.rect(0,0,210,27,'F');doc.setTextColor(255,255,255);doc.setFont('helvetica','bold');doc.setFontSize(15);doc.text('LNB — Demonstrativo de Pagamento',12,12);doc.setFontSize(8);doc.text('Competência '+formatCompetence(S.competencia.competencia)+' · RH & Folha',12,20);doc.setTextColor(20,35,50);doc.setFontSize(9);doc.text('Colaborador: '+String(p.nome||''),12,36);doc.text('Matrícula: '+String(p.matricula||'—')+'   Vínculo: '+String(p.vinculo||'—'),12,42);doc.text('Cargo: '+String(p.cargo||'—')+'   Departamento: '+String(departmentName(p.departamento)),12,48);doc.autoTable({startY:54,head:[['Cód.','Descrição','Referência','Proventos','Descontos']],body:launches62(p),theme:'grid',styles:{fontSize:8,cellPadding:2},headStyles:{fillColor:[13,43,66]},columnStyles:{3:{halign:'right'},4:{halign:'right'}}});var y=(doc.lastAutoTable&&doc.lastAutoTable.finalY||80)+8;if(y>245){doc.addPage();y=28}doc.setFillColor(234,242,246);doc.roundedRect(12,y,186,25,2,2,'F');doc.setFontSize(9);doc.setFont('helvetica','bold');doc.text('Total de proventos: '+money62(p.proventos),16,y+8);doc.text('Total de descontos: '+money62(p.descontos),16,y+15);doc.setFontSize(12);doc.text('Líquido: '+money62(p.liquido),130,y+15);doc.setFontSize(7);doc.setFont('helvetica','normal');doc.text('Bases: INSS '+money62(p.base_inss)+' · FGTS '+money62(p.base_fgts)+' · IRRF '+money62(p.base_irrf),12,y+32)});doc.save('LNB_Holerite'+(people.length>1?'s':'')+'_'+fileLabel+'_'+formatCompetence(S.competencia.competencia).replace('/','-')+'.pdf')}
function currentPayrollScope62(){try{return rhScopePeople().filter(function(p){return !!p.colaborador_id})}catch(e){return (S.pessoas||[]).slice()}}
async function slip62(id,b){var p=payrollFor62(id);if(!p)return notify62('Este colaborador não possui folha na competência selecionada.',true);var old=b&&b.textContent;if(b){b.disabled=true;b.textContent='Gerando…'}try{await generatePayslips62([p],String(p.nome||'Individual').replace(/[^A-Za-z0-9À-ÿ]+/g,'_'));notify62('Holerite individual gerado.')}catch(e){notify62(e.message||String(e),true)}finally{if(b){b.disabled=false;b.textContent=old}}}
async function batch62(b){var people=currentPayrollScope62(),old=b.textContent;b.disabled=true;b.textContent='Gerando lote…';try{await generatePayslips62(people,'Lote');notify62(people.length+' holerite(s) gerado(s) conforme os filtros atuais.')}catch(e){notify62(e.message||String(e),true)}finally{b.disabled=false;b.textContent=old}}

renderPeople=renderCollaborators62;
var basePayroll62=renderPayroll;renderPayroll=function(){var r=basePayroll62.apply(this,arguments);cleanup61();ensureUi62();return r};
var baseDeptOptions62=rhScopeDeptOptions;rhScopeDeptOptions=function(){var seen={},out=[];(S.colaboradores||[]).forEach(function(c){var raw=String(c.departamento==null?'':c.departamento),label=departmentName(c.departamento);if(!raw||seen[raw])return;seen[raw]=1;out.push({value:raw,label:label})});return out.length?out.sort(function(a,b){return a.label.localeCompare(b.label,'pt-BR',{sensitivity:'base'})}):baseDeptOptions62()};

document.addEventListener('click',function(e){var t=e.target.closest&&e.target.closest('#rh62-new,#rh62-batch,#rh62-sync,#rh62-vacations,[data-rh62-employee],[data-rh62-slip],[data-rh62-payroll],[data-rh62-close]');if(!t)return;e.preventDefault();e.stopImmediatePropagation();if(t.matches('[data-rh62-close]'))close62();else if(t.id==='rh62-new')newCollaborator62();else if(t.id==='rh62-batch')batch62(t);else if(t.id==='rh62-sync')sync62(t);else if(t.id==='rh62-vacations')vacationModal62();else if(t.hasAttribute('data-rh62-slip'))slip62(t.dataset.rh62Slip,t);else if(t.hasAttribute('data-rh62-payroll')){var id=t.dataset.rh62Payroll;close62();openPerson(id)}else openEmployee62(t.dataset.rh62Employee)},true);
document.addEventListener('change',function(e){if(e.target&&e.target.id==='rh62-status')toggleDismissal62()},true);
document.addEventListener('submit',function(e){if(!e.target)return;if(e.target.id==='rh62-new-form'){e.preventDefault();e.stopImmediatePropagation();saveNew62()}else if(e.target.id==='rh62-status-form'){e.preventDefault();e.stopImmediatePropagation();saveStatus62(e.target)}},true);
document.addEventListener('keydown',function(e){if(e.key==='Escape'&&el62('rh62-modal'))close62()},true);
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){ensureUi62();if(S.competencia)renderCollaborators62()});else ensureUi62();
})();
